### ISSUE TITLE
Make error with EVP_CIPHER_CTX_FLAG_UNWRAP_WITHPAD undeclared

### ISSUE THREAD

**Issue by Rasstrelnikov** [cisco/libacvp#129]
I am running 64 bit Ubuntu 18.04. Calling make exits with this error:

app_main.c: In function ‘app_aes_keywrap_handler’:
app_main.c:2969:50: error: ‘EVP_CIPHER_CTX_FLAG_UNWRAP_WITHPAD’ undeclared (first use in this function); did you mean ‘EVP_CIPHER_CTX_FLAG_WRAP_ALLOW’?
             EVP_CIPHER_CTX_set_flags(cipher_ctx, EVP_CIPHER_CTX_FLAG_UNWRAP_WITHPAD);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  EVP_CIPHER_CTX_FLAG_WRAP_ALLOW
app_main.c:2969:50: note: each undeclared identifier is reported only once for each function it appears in
At top level:
app_main.c:5402:19: warning: ‘base64en’ defined but not used [-Wunused-const-variable=]
 static const char base64en[] = {
                   ^~~~~~~~
Makefile:401: recipe for target 'app_main.o' failed
make[1]: *** [app_main.o] Error 1
make[1]: Leaving directory '/home/my_name/libacvp/app'
Makefile:387: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

And then make install subsequently also fails and acvp_app is not built. gcc also returns this error on Centos7. Ubuntu has openssl 1.1.0 and Centos7 has openssl 1.0.2. Taking the compiler's suggestion and replacing EVP_CIPHER_CTX_FLAG_UNWRAP_WITHPAD with EVP_CIPHER_CTX_FLAG_WRAP_ALLOW works and allows me to connect to the demo server on both Ubuntu and Centos7. Although the substitution works they do not seem interchangeable- I would be interested to know if others can replicate this error on their setup.

**Comment by bfussell** [comment]
My mistake. I enabled some keywrap options, ie with wrap, that are not supported by openssl.
Just comment that handler out and you should be fine.

Barry
