### ISSUE TITLE
ACVP_NO_RUNTIME

### ISSUE THREAD

**Issue by hexiangqwqwqw** [cisco/libacvp#141]
I dont understand the mean of ACVP_NO_RUNTIME.
What is effect  to acvp when i define ACVP_NO_RUNTIME

**Comment by bfussell** [comment]
ACVP_NO_RUNTIME is used for builds, for the case of openssl,  with a FIPS Object Module(FOM) where some intermediate parameters or randomness are exposed. For example, RSA key generation.  Normally, you do not expose an API to RSA key generation that allows "introduced" randomness.  These types of APIs into a crypto module are generally not allowed in production code, hence "no runtime".

**Comment by bfussell** [comment]
We have not tested with a base openssl FOM, we use a variant of the FOM.
Could you share what compile errors you encountered ?

**Comment by hexiangqwqwqw** [comment]
app/app_main.c:959:9: error: implicit declaration of function 'FIPS_cipher_ctx_new' [-Werror=implicit-function-declaration]
app/app_main.c:959:24: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:1084:5: error: implicit declaration of function 'FIPS_cipher_ctx_free' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'app_aes_handler_aead':
app/app_main.c:3130:16: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c: In function 'app_sha_handler':
app/app_main.c:3297:5: error: implicit declaration of function 'FIPS_md_ctx_create' [-Werror=implicit-function-declaration]
app/app_main.c:3297:12: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:3344:5: error: implicit declaration of function 'FIPS_md_ctx_destroy' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'app_dsa_handler':
app/app_main.c:3853:25: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:3853:25: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c:3915:21: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:3915:21: error: passing argument 9 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'long unsigned int *' but argument is of type 'int *'
app/app_main.c:3915:21: error: passing argument 10 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'struct BN_GENCB *' but argument is of type 'long unsigned int *'
app/app_main.c:3915:21: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c:3948:21: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:3948:21: error: passing argument 9 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'long unsigned int *' but argument is of type 'int *'
app/app_main.c:3948:21: error: passing argument 10 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'struct BN_GENCB *' but argument is of type 'long unsigned int *'
app/app_main.c:3948:21: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c:4070:25: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:4070:25: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c:4135:23: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:4135:23: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c:4151:43: error: passing argument 7 of 'fips_dsa_builtin_paramgen2' makes pointer from integer without a cast [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'unsigned char *' but argument is of type 'int'
app/app_main.c:4151:43: error: passing argument 8 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'int *' but argument is of type 'unsigned char *'
app/app_main.c:4151:43: error: passing argument 9 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'long unsigned int *' but argument is of type 'int *'
app/app_main.c:4151:43: error: passing argument 10 of 'fips_dsa_builtin_paramgen2' from incompatible pointer type [-Werror]
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: expected 'struct BN_GENCB *' but argument is of type 'long unsigned int *'
app/app_main.c:4151:43: error: too many arguments to function 'fips_dsa_builtin_paramgen2'
/net/peknetapp01/xianghe/work/project/mm-dev/mm-dev_005/openssl-regular/openssl-1.0.1c/include/openssl/fips.h:322:5: note: declared here
app/app_main.c: In function 'make_peer':
app/app_main.c:4187:5: error: implicit declaration of function 'FIPS_ec_point_new' [-Werror=implicit-function-declaration]
app/app_main.c:4187:10: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4192:5: error: implicit declaration of function 'fips_bn_ctx_new' [-Werror=implicit-function-declaration]
app/app_main.c:4192:7: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4197:5: error: implicit declaration of function 'FIPS_ec_method_get_field_type' [-Werror=implicit-function-declaration]
app/app_main.c:4197:5: error: implicit declaration of function 'FIPS_ec_group_method_of' [-Werror=implicit-function-declaration]
app/app_main.c:4199:9: error: implicit declaration of function 'fips_ec_point_set_affine_coordinates_gfp' [-Werror=implicit-function-declaration]
app/app_main.c:4201:9: error: implicit declaration of function 'fips_ec_point_set_affine_coordinates_gf2m' [-Werror=implicit-function-declaration]
app/app_main.c:4204:5: error: implicit declaration of function 'fips_bn_ctx_free' [-Werror=implicit-function-declaration]
app/app_main.c:4208:5: error: implicit declaration of function 'FIPS_ec_point_free' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'ec_print_key':
app/app_main.c:4222:9: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4227:5: error: implicit declaration of function 'fips_bn_ctx_get' [-Werror=implicit-function-declaration]
app/app_main.c:4227:8: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4228:8: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4234:5: error: implicit declaration of function 'FIPS_ec_key_get0_group' [-Werror=implicit-function-declaration]
app/app_main.c:4234:9: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4235:5: error: implicit declaration of function 'FIPS_ec_key_get0_public_key' [-Werror=implicit-function-declaration]
app/app_main.c:4235:8: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4236:5: error: implicit declaration of function 'FIPS_ec_key_get0_private_key' [-Werror=implicit-function-declaration]
app/app_main.c:4236:7: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4237:10: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4239:9: error: implicit declaration of function 'FIPS_ec_point_get_affine_coordinates_gfp' [-Werror=implicit-function-declaration]
app/app_main.c:4241:9: error: implicit declaration of function 'FIPS_ec_point_get_affine_coordinates_gf2m' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'app_kas_ecc_handler':
app/app_main.c:4338:5: error: implicit declaration of function 'FIPS_ec_group_new_by_curve_name' [-Werror=implicit-function-declaration]
app/app_main.c:4338:11: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4344:5: error: implicit declaration of function 'FIPS_ec_key_new' [-Werror=implicit-function-declaration]
app/app_main.c:4344:8: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4346:9: error: implicit declaration of function 'fips_ec_group_free' [-Werror=implicit-function-declaration]
app/app_main.c:4350:5: error: implicit declaration of function 'FIPS_ec_key_set_flags' [-Werror=implicit-function-declaration]
app/app_main.c:4350:26: error: 'EC_FLAG_COFACTOR_ECDH' undeclared (first use in this function)
app/app_main.c:4350:26: note: each undeclared identifier is reported only once for each function it appears in
app/app_main.c:4351:5: error: implicit declaration of function 'FIPS_ec_key_set_group' [-Werror=implicit-function-declaration]
app/app_main.c:4386:9: error: implicit declaration of function 'FIPS_ec_key_set_public_key_affine_coordinates' [-Werror=implicit-function-declaration]
app/app_main.c:4387:9: error: implicit declaration of function 'FIPS_ec_key_set_private_key' [-Werror=implicit-function-declaration]
app/app_main.c:4397:5: error: implicit declaration of function 'FIPS_ec_group_get_degree' [-Werror=implicit-function-declaration]
app/app_main.c:4407:5: error: implicit declaration of function 'FIPS_ecdh_compute_key' [-Werror=implicit-function-declaration]
app/app_main.c:4417:9: error: implicit declaration of function 'FIPS_digest' [-Werror=implicit-function-declaration]
app/app_main.c:4418:9: error: implicit declaration of function 'M_EVP_MD_size' [-Werror=implicit-function-declaration]
app/app_main.c:4424:9: error: implicit declaration of function 'FIPS_openssl_cleanse' [-Werror=implicit-function-declaration]
app/app_main.c:4426:5: error: implicit declaration of function 'FIPS_free' [-Werror=implicit-function-declaration]
app/app_main.c:4427:5: error: implicit declaration of function 'FIPS_ec_key_free' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'app_kas_ffc_handler':
app/app_main.c:4470:5: error: implicit declaration of function 'FIPS_dh_new' [-Werror=implicit-function-declaration]
app/app_main.c:4470:8: error: assignment makes pointer from integer without a cast [-Werror]
app/app_main.c:4511:5: error: implicit declaration of function 'FIPS_bn_num_bits' [-Werror=implicit-function-declaration]
app/app_main.c:4517:5: error: implicit declaration of function 'FIPS_dh_compute_key_padded' [-Werror=implicit-function-declaration]
app/app_main.c:4537:5: error: implicit declaration of function 'FIPS_bn_clear_free' [-Werror=implicit-function-declaration]
app/app_main.c:4542:5: error: implicit declaration of function 'FIPS_dh_free' [-Werror=implicit-function-declaration]
app/app_main.c: In function 'app_drbg_handler':
app/app_main.c:4989:9: error: implicit declaration of function 'progress' [-Werror=implicit-function-declaration]
app/app_main.c: At top level:
app/app_lcl.h:117:13: error: 'fips_algtest_init_nofips' defined but not used [-Werror=unused-function]
app/app_main.c:4856:20: error: 'app_drbg_handler' defined but not used [-Werror=unused-function]
app/app_main.c:266:20: error: 'app_des_keywrap_handler' declared 'static' but never defined [-Werror=unused-function]
app/app_main.c:267:20: error: 'app_aes_keywrap_handler' declared 'static' but never defined [-Werror=unused-function]
cc1: all warnings being treated as errors

**Comment by bfussell** [comment]
What was you configure script command line and where did you install your FOM ?
