### ISSUE TITLE
CA invalid 

### ISSUE THREAD

**Issue by hexiangqwqwqw** [cisco/libacvp#144]
Please check the log:

root@hexiang-VirtualBox:/work/lib/libacvp# ./acvp_app 

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: acvp/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

POST [
    {
        "acvVersion": "0.4"
    },
    {
        "password": "09726792"
    }
]
***ACVP [ERR][acvp_curl_http_post:265]--> Curl failed with code 60 (Peer certificate cannot be authenticated with given CA certificates)

***ACVP [ERR][acvp_curl_http_post:281]--> HTTP response: 0

***ACVP [ERR][acvp_send_login:568]--> Unable to register with ACVP server. curl rv=0

***ACVP [STATUS][acvp_register:994]--> Login Response Failed (null)
***ACVP [STATUS][acvp_register:997]--> Login Send Failed
Failed to register with ACVP server (rv=3)

**Comment by bfussell** [comment]
Try using the mozzila CA file in the certs/ directory

**Comment by elliemdaw** [comment]
Have you tried with the mozilla_trust_anchors in the certs folder? That is the one I usually use for CA :)

**Comment by elliemdaw** [comment]
Good timing @bfussell haha
