### ISSUE TITLE
DSA Parameter Generation 2 error for 2

### ISSUE THREAD

**Issue by hexiangqwqwqw** [cisco/libacvp#150]
The error log is "DSA Parameter Generation 2 error for 2"
How to solve that?

**Comment by bfussell** [comment]
Looking at app_main.c that appears to be a PQGEN operation using PROBABLE pq generation method.  That works properly using our FOM. It could be that the older openssl FOM you are using does not support all the options that are being registered by our default app. I would recommend that you reduce the PQGEN registrations and see if that is the case.
