### ISSUE TITLE
Error running the configure script

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libacvp#162]
**Excerpt from config.log**

> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_get_error@OPENSSL_1.0.0'

> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_get_certificate@OPENSSL_1.0.0'

> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `UI_method_get_reader@OPENSSL_1.0.0'

> ...
> ...
> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `X509_LOOKUP_file@OPENSSL_1.0.0'

> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `SSL_set_fd@OPENSSL_1.0.0'

> /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libcurl.so: undefined reference to `ENGINE_get_id@OPENSSL_1.0.0'

> collect2: error: ld returned 1 exit status

**My settings/paths to libs are shown below:**

> amritha@thorath-vm:~/cavp_tool$ set | grep LIBRARY
> LD_LIBRARY_PATH=/home/amritha/ssl/lib
> 
> 
> amritha@thorath-vm:~/cavp_tool$ curl -V
> curl 7.59.0 (x86_64-pc-linux-gnu) libcurl/7.59.0 OpenSSL/1.0.2j zlib/1.2.8
> Release-Date: 2018-03-14
> Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
> Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP UnixSockets HTTPS-proxy
> 
> amritha@thorath-vm:~/cavp_tool$ ls /home/amritha/ssl/
> aes   des  ecdh   fipsalgtest.pl  fips.c           fipsld       fips_premain.c       fips_test_suite.c  include   mkfipsscr.pl  sha    utl
> bin   dh   ecdsa  fips_auth.h     fips_canister.c  fips_locl.h  fips_premain.c.sha1  fips_utl.h         lib       rand          ssl
> cmac  dsa  fips   fips_auth.in    fips.h           fips_post.c  fipssyms.h           hmac               Makefile  rsa           tools
> 
> 
> amritha@thorath-vm:~/cavp_tool$ ls /home/amritha/ssl/lib/
> engines         fipscanister.o.sha1  fips_premain.c.sha1  libcrypto.so        libssl.a   libssl.so.1.0.0
> fipscanister.o  fips_premain.c       libcrypto.a          libcrypto.so.1.0.0  libssl.so  pkgconfig
> 
> 
> amritha@thorath-vm:~/cavp_tool/libacvp-master$ ./configure --with-ssl-dir=/home/amritha/ssl --with-libcurl-dir=/home/amritha/cavp_tool/curl-7.59.0
> ...
> ...
> configure: error: in `/home/amritha/cavp_tool/libacvp-master':
> configure: error: --with-libcurl was given, but test for libcurl failed
> See `config.log' for more details

**Comment by elliemdaw** [comment]
Hi there! This looks like it could be an issue with missing header files. Our library needs the header files for openssl and curl. Is that what you are pointing to in your config line? I know you can install the curl development headers via apt-get on linux (for example 'apt-get install libcurl4-openssl-dev')

**Comment by amrithathorath** [comment]
The Openssl headers (include folder)are under /home/amritha/ssl which is the path that I've specified for "--with-ssl-dir". 
Curl headers (include folder) are under /home/amritha/cavp_tool/curl-7.59.0 which is the path I've specified for "with-libcurl-dir".

**Comment by elliemdaw** [comment]
Hmmm, just curious - can you try running the config without "with-libcurl-dir" just to see what happens?

**Comment by amrithathorath** [comment]
Wow! Seems like that was the cause. Looks like it succeeded...

> checking that generated files are newer than configure... done
> configure: creating ./config.status
> config.status: creating Makefile
> config.status: creating safe_c_stub/Makefile
> config.status: creating safe_c_stub/lib/Makefile
> config.status: creating src/Makefile
> config.status: creating app/Makefile
> config.status: executing depfiles commands
> config.status: executing libtool commands

**Comment by amrithathorath** [comment]
Spoke too soon...
The next step where I run make (after make clean) gives curl related errors:

> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_global_cleanup'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_getinfo'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_perform'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_slist_append'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_init'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_strerror'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_slist_free_all'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_setopt'
> /home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_cleanup'
>

**Comment by elliemdaw** [comment]
Is curl in your LD_LIBRARY_PATH?

**Comment by amrithathorath** [comment]
No...
LD_LIBRARY_PATH is set to /home amritha/ssl which is where my ssl directory is located...
Curl is in a different location.
Am I supposed to have Curl under /home/amritha/ssl? I ask this because ssl was created when I built OpenSSL...

**Comment by elliemdaw** [comment]
You can append to your LD_LIBRARY_PATH in the same way that you might append to PATH. export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<path to curl>

**Comment by elliemdaw** [comment]
Oh that just ate some formatted text... 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/curl

**Comment by amrithathorath** [comment]
Updated the path in LD_LIBRARY_PATH:

> amritha@thorath-vm:~/cavp_tool/libacvp-master$ export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/amritha/cavp_tool/curl-7.59.0
> amritha@thorath-vm:~/cavp_tool/libacvp-master$ set | grep LIBRARY
> LD_LIBRARY_PATH=/home/amritha/ssl/lib:/home/amritha/cavp_tool/curl-7.59.0

After updating path, I still see the same error.
I tried to re-run configure again but with Curl path this time but it failed as before...

**Comment by elliemdaw** [comment]
The curl path might need to include /lib just like ssl

**Comment by amrithathorath** [comment]
This is what the path looks like now but see no improvement :(

amritha@thorath-vm:~/cavp_tool/libacvp-master$ set | grep LD_LIBRARY_PATH
LD_LIBRARY_PATH=/home/amritha/ssl/lib:/home/amritha/cavp_tool/curl-7.59.0/lib

**Comment by elliemdaw** [comment]
Just so that I understand - 
the LD_LIBRARY_PATH is updated to also include the curl library path, you re-configured without with-libcurl-dir, make clean, make and it is still failing? With the same error?

**Comment by amrithathorath** [comment]
Correct! Updated LD_LIBRARY_PATH to include curl library path, re-configured without curldir option, make clean and then make. The error is shown below:

/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_global_cleanup'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_getinfo'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_perform'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_slist_append'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_init'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_strerror'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_slist_free_all'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_setopt'
/home/amritha/cavp_tool/libacvp-master/src/.libs/libacvp.so: undefined reference to `curl_easy_cleanup'

**Comment by elliemdaw** [comment]
And if you include the with-curldir option in the configure it still doesn't work?

Can you post the gcc command before these failures when you 'make'? Sounds like it isn't including -lcurl (likely because this is left out of the configure options)

**Comment by amrithathorath** [comment]
Correct. If I run configure with curldir option it fails.
Here's the gcc command:

gcc -DPACKAGE_NAME=\"libacvp\" -DPACKAGE_TARNAME=\"libacvp\" -DPACKAGE_VERSION=\"0.5\" -DPACKAGE_STRING=\"libacvp\ 0.5\" -DPACKAGE_BUGREPORT=\"ccsm-support@cisco.com\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libacvp\" -DVERSION=\"0.5\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LIBCRYPTO=1 -DHAVE_LIBSSL=1 -I.    -I../include  -fPIC -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -I/home/amritha/ssl/include -z,noexecstack -MT ../src/libsafe_lib_a-safe_mem_stub.o -MD -MP -MF ../src/.deps/libsafe_lib_a-safe_mem_stub.Tpo -c -o ../src/libsafe_lib_a-safe_mem_stub.o `test -f '../src/safe_mem_stub.c' || echo './'`../src/safe_mem_stub.c

**Comment by amrithathorath** [comment]
Hi,
Is there anything else that I can try to resolve this issue?

**Comment by fliphil** [comment]
Hi! To make sure I understand correctly:
1. You are using the system Curl, i.e. installed via apt-get or yum.
2. The OpenSSL that you are using is built and installed by yourself.
3. What is the version of OpenSSL?

**Comment by amrithathorath** [comment]
1 and 2 are correct... 
OpenSSL versions are openssl-1.0.2j and openssl-fips-2.0.12.

**Comment by fliphil** [comment]
For the curl install you are using /home/amritha/cavp_tool/curl-7.59.0, is that something you installed yourself? I assume that's different than the system curl version.
1. What is show when you run `ls -al /home/amritha/cavp_tool/curl-7.59.0/lib`
2. What is shown when you run `which curl`
3. Now update LD_LIBRARY_PATH="/home/amritha/cavp_tool/curl-7.59.0/lib:/home/amritha/ssl/lib" and do number 2 again.

**Comment by fliphil** [comment]
Okay we need to figure out where the libcurl.so exists. Do you see it in the output from number 1?
If not, try running `find /home/amritha/cavp_tool/curl-7.59.0 -name "libcurl*.so". That should tell us where the shared library is sitting. It sounds like you might have installed Curl to the source directory which is a bit more confusing to navigate. Can you provide the commands that you used to configure and install curl? You can use shift-ctrl-r to do a reverse search through your previous command history.

**Comment by amrithathorath** [comment]
libcurl.so is located in "/home/amritha/cavp_tool/curl-7.59.0/lib/.libs/libcurl.so"

Steps used to configure and install curl:

- ./configure --with-ssl=/home/amritha/ssl (In my case /home/amritha/ssl was the location where my OpenSSL files were present)
- sudo make
- sudo make install
- sudo ldconfig

**Comment by fliphil** [comment]
Ah okay I see what's happening now. Since you didn't use --prefix, it defaults to installing at /usr/local/curl. You should be to either specify that location for the libacvp --with-libcurl-dir=/usr/local/curl or re configure curl using the --prefix /home/amwintha/curl_install or wherever you want and then run thorough the make, make install again. Also make sure to do `export LD_LIBRARY_PATH`

**Comment by amrithathorath** [comment]
That fixed my issue. Really thankful to you guys for helping me work through this issue...
