### ISSUE TITLE
Peer certificate cannot be authenticated: Failed to register with ACVP server

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libacvp#164]
This is the error I'm seeing when I try ti connect to ACVP server. When I use "acvp.nist.gov" for ACV_SERVER I get "Couldn't resolve host name" error which is why I'm using demo server.

> amritha@thorath-vm:~/cavp_tool/libacvp-master$ ./app/acvp_app
> 
> Using the following parameters:
> 
>     ACV_SERVER:     demo.acvts.nist.gov
>     ACV_PORT:       443
>     ACV_URI_PREFIX: acvp
>     ACV_CA_FILE:    certs/demo.server.crt
>     ACV_CERT_FILE:  certs/CSR_athorath-corsec.cer
>     ACV_KEY_FILE:   certs/privateKey.pem
> 
> 
> POST [
>     {
>         "acvVersion": "0.4"
>     },
>     {
>         "password": "38026102"
>     }
> ]
> ***ACVP [ERR][acvp_curl_http_post:267]--> Curl failed with code 60 (Peer certificate cannot be authenticated with given CA certificates)
> 
> ***ACVP [ERR][acvp_curl_http_post:283]--> HTTP response: 0
> 
> ***ACVP [ERR][acvp_send_login:616]--> Unable to register with ACVP server. curl rv=0
> 
> ***ACVP [STATUS][acvp_register:1069]--> Login Response Failed (null)
> ***ACVP [STATUS][acvp_register:1072]--> Login Send Failed
> Failed to register with ACVP server (rv=3)

All the certificates and keys are under certs folder:

> amritha@thorath-vm:~/cavp_tool/libacvp-master$ ls -l certs/
> total 284
> -rw-rw-r-- 1 amritha amritha   1566 Oct 15 15:10 acvp.nist.gov.crt
> -rw-rw-r-- 1 amritha amritha   1398 Oct 15 15:11 CSR_athorath-corsec.cer
> -rw-rw-r-- 1 amritha amritha   2256 Oct 22 13:07 demo.server.crt
> -rw-rw-r-- 1 amritha amritha 274340 Oct 15 15:10 mozzila_trust_anchors.pem
> -r--r----- 1 amritha amritha   1704 Oct 15 15:11 privateKey.pem

Any help is appreciated!

**Comment by amrithathorath** [comment]
Got answer to this issue on another thread!

**Comment by bfussell** [comment]
ACV_URI_PREFIX acvp/

not

ACV_URI_PREFIX acvp
