### ISSUE TITLE
Validating response files

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libacvp#169]
When I run this command "./app/acvp_app --no_aes --no_tdes --no_cmac --no_hmac" it is successful. It says KATs passed. How can I upload my own response files to get it validated?

**Comment by elliemdaw** [comment]
Are you wanting to upload a different set of answers? If it says the KATs passed then the results have already been uploaded by the application and the server has responded with a passing disposition!

**Comment by amrithathorath** [comment]
Yes, I have a set of response files, I want to upload them...

**Comment by elliemdaw** [comment]
Our client only supports real-time uploads as of right now.

**Comment by amrithathorath** [comment]
When you say real time, do you mean only KATs where we cannot upload any results?

**Comment by elliemdaw** [comment]
The application uploads results for you already. When you run
"./app/acvp_app --no_aes --no_tdes --no_cmac --no_hmac",
it advertises the SHA capability to the ACVP server, downloads the test vectors, processes them, uploads the responses, and checks the disposition - all in "real time". It sounds like all of your tests are passing if your KAT results say "passed"!

**Comment by amrithathorath** [comment]
Ok so here's the scenario. I've a set of request files. I run them using a certain library and generated the response files for those request files. So now I need to validate those response files. Is there no way to do that?

**Comment by elliemdaw** [comment]
Not at this time.

**Comment by amrithathorath** [comment]
Got it, thanks!!
