### ISSUE TITLE
Request vectors, test and validate

### ISSUE THREAD

**Issue by amrithathorath** [cisco/libacvp#170]
Hi,

I want to request test vectors, use them to run some tests on my system and generate results. Upload these results back so that they can be validated. How do I do that?

**Comment by elliemdaw** [comment]
Our client doesn't support that at this time. You can plug your own crypto module's API into the client application code in app/app_main.c in place of the example openssl APIs, but we do not support what you are suggesting right now.

**Comment by lisarabe** [comment]
I had the same question.  I thought the ACVP system would generate .req files, give them to us to run, and then validate the results after we uploaded the .rsp files.  Is this functionality going to be available eventually?

**Comment by bfussell** [comment]
Currently, this open source library only works in real time.  The flow is documented in the README.  The ACVP protocol does allow what you desire, however that is not a requirement in every environment. Since our library is designed for testing openssl or openssl FOM, real time operation is all that is needed.

**Comment by lisarabe** [comment]
OK, thanks.  What about testing other libraries?  Especially libraries that aren't written in C?  Is there a way to do that?

**Comment by bfussell** [comment]
I would think its possible to take the callbacks in app_main.c and replace them with something that could call non-C code as long as you can link it in.

**Comment by bfussell** [comment]
No, I'm not sure if kernel crypto has been tested. Maybe others on the call today may know.

**Comment by amrithathorath** [comment]
> I would think its possible to take the callbacks in app_main.c and replace them with something that could call non-C code as long as you can link it in.

Has this been tried by anyone?

**Comment by bfussell** [comment]
This is open source code so I'm sure people take it do all sorts of things with it, but there is not way for us to track what they may be doing.

**Comment by fliphil** [comment]
Agree with @bfussell . For instance, someone could try embedding Python within the callback function: https://docs.python.org/2/extending/embedding.html As far as we know, no one has tried using the library with other languages. It sounds feasible though and we encourage users to experiment according to their needs.

**Comment by Rasstrelnikov** [comment]
I would also be very interested in knowing if there is going to be non-real time functionality eventually. We almost exclusively test hardware modules and the module vendor normally produces the responses to the .req files on their own.  As it is we would need to make a lot of changes to produce the CAVS-like functionality we need and the switch from CAVS will be challenging for us (although many aspects of the new protocol will also be very time-saving for us as well).

**Comment by bfussell** [comment]
Non-realtime is definitely on our roadmap. However, the primary goal of this open source project is to prove the ACV protocol is viable and provide NIST with interoperability feedback. We don't anticipate the project becoming the source for features for all possible deployment scenarios. It should be used as a reference implementation for all in the industry. We won't be bound by any publicized schedules and features will be added on a best effort basis.  Our team is simply not staffed to provide anything beyond that.  We do encourage participation from the community with bugfixes and even feature enhancements and we are currently working towards defining and communicating a process for that.

**Comment by fadaile** [comment]
dear all
I want to request test vectors, use them to run some tests on my system and generate results. Upload these results back so that they can be validated. How do I do that?

**Comment by bfussell** [comment]
As you can see in the above conversation, that capability is not yet available in our open source client.
Since it is open source you are welcome to enhance it to meet your needs.

**Comment by bfussell** [comment]
This capability was added recently. By using the following commands it can be accomplished.  More details will be added to the README soon as well.

            To test offline:
               a) Download vectors on network accessible device
                   ./app/acvp_app --<algs of choice or all_algs> --vector_req <filename1>
               b) Copy vectors and acvp_app to target
                   ./app/acvp_app --all_algs --vector_req <filename1> --vector_rsp <filename2>
               c) Copy respones(filename2) to network accessible device
                   ./app/acvp_app --all_algs --vector_upload <filename2>

Note: if target device in step b does not have libcurl, build with libmurl and copy that as well.
We will be investigating how to minimize the library dependencies for step b soon.

**Comment by amrithathorath** [comment]
@bfussell : Thanks so much for the update...
