### ISSUE TITLE
include html docs unzipped?

### ISSUE THREAD

**Issue by letoams** [cisco/libacvp#2]
assuming this software would itself be compressed (eg using zip or gzip or bzip2 or xc) it does not make sense to ship the documentation inside it as a zip file. It would be better to shiip these unzipped.

**Comment by jfigus** [comment]
It makes sense from the perspective of keeping all the HTML files together in a single bundle.  If someone wanted to install the HTML files somewhere, they would have to bundle them, move them to the new location, and unbundle them.

Keep in mind this is an early prototype project.  We're a long ways away from doing the first release.
