### ISSUE TITLE
nist_setup parameters not sticking

### ISSUE THREAD

**Issue by iabent** [cisco/libacvp#201]
Hey there,

Hoping this is an error on my part but I am trying out the newest code to simply show acvp working on Openssl but have hit a snag.

I successfully built acvp_app using the steps shown on the main page, updated my scripts/nist_setup.sh with the info I had from the last time I ran it (back in Sept/Oct), ran it (./scripts/nist_setup.sh) and then tried running ./app/acvp_app but I'm seeing this:

Using the following parameters:

    ACV_SERVER:     127.0.0.1
    ACV_PORT:       443
    ACV_URI_PREFIX:
    ACV_CA_FILE:    certs/acvp-private-root-ca.crt.pem
    ACV_CERT_FILE:  certs/my-client-cert.pem
    ACV_KEY_FILE:   certs/my-client-key.pem

Failed to get TOTP seed

POST [
    {
        "acvVersion": "0.5"
    },
    {
        "password": ""
    }
]
***ACVP [ERR][acvp_curl_http_post:270]--> Curl failed with code 7 (Couldn't connect to server)

***ACVP [ERR][acvp_curl_http_post:286]--> HTTP response: 0

***ACVP [ERR][acvp_send_internal:512]--> Unable to register |https://127.0.0.1:443/login| with ACVP server. curl rv=0

(null)***ACVP [STATUS][acvp_register:1202]--> Login Send Failed (null)
Failed to register with ACVP server (rv=3)

Which is odd because in my scripts/nist_setup.sh file I have the CA_FILE, CERT_FILE and KEY_FILE all a different names to what is shown above (which looks like defaults, or do they get renamed?) Is this intentional? Also, since it's been a while since I last successfully ran the demo, would I need to poke NIST again for a new TOTP seed? Or should the one I have suffice?

Thanks so much!

**Comment by elliemdaw** [comment]
Try 'source ./scripts/nist_setup.sh' :)

**Comment by iabent** [comment]
That's what it was, I knew I was missing something! Hahaha
Also changed the ACV_SERVER to demo.acvts.nist.gov to get the demo working. I assume the preset acvp.nist.gov is for the "live" version?

**Comment by elliemdaw** [comment]
Right, the demo server is 'demo.acvts.nist.gov'!

**Comment by iabent** [comment]
I just closed this but now I'm seeing the server request failing every time it tries:

***ACVP [STATUS][acvp_retrieve_vector_set:782]--> GET https://demo.acvts.nist.gov:443/acvp//acvp/v1/testSessions/1571/vectorSets/8230
***ACVP [STATUS][acvp_retrieve_vector_set:796]--> KAT vector set response received
***ACVP [STATUS][acvp_process_vsid:1820]--> 200 OK [ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 8230,
  "retry" : 30
} ]

***ACVP [STATUS][acvp_retry_handler:1713]--> 200 OK KAT values not ready, server requests we wait and try again...
***ACVP [STATUS][acvp_retrieve_vector_set:782]--> GET https://demo.acvts.nist.gov:443/acvp//acvp/v1/testSessions/1571/vectorSets/8230
***ACVP [STATUS][acvp_retrieve_vector_set:796]--> KAT vector set response received
***ACVP [STATUS][acvp_process_vsid:1820]--> 200 OK [ {
  "acvVersion" : "0.5"
}, {
  "vsId" : 8230,
  "retry" : 30

I see this about 7 times now, Have you seen any issues like this or should I assume it's my work network blocking it?

**Comment by elliemdaw** [comment]
The logs are telling you that the server is working on generating tests and the client needs to wait ("200 OK KAT values not ready...") :) from my experience, the server responsiveness is different depending on what you are running. If you are running a lot of algorithms and modes, that takes longer. Same with slower algorithms like ECDSA, etc.

**Comment by iabent** [comment]
Oh, well don't mind me then! Thank you.

**Comment by elliemdaw** [comment]
Good luck! 👍

**Comment by iabent** [comment]
Final (hopefully) curiosity: I received 2 versions the end results. The first is {"passed" : false} (8388 through 8405 passed, 8406 is incomplete) and the second is { "passed" : true,} (where all the tests, 8388 through 8406, passed). Both lists look identical save that 8406 is incomplete in the first and passed in the second.

The last entry to the list is VectorSets/8406. But when I look through all the tests ran I see it ran all the way until VsID 8416, is there a reason the last 10 get "cut off" from the results? The results start at 8388 as well as the tests, so it just looks like the end is cut. Does this have anything to do with the "incomplete" I got in the first set of results? (The incomplete was 8406)

I can add any more information needed. Sorry to bother you!

**Comment by elliemdaw** [comment]
Right, so if you look at the log, you recieved the first version of the answers, then the client waited for the 30 second retry period and asked again (because it saw an incomplete disposition), asked again and saw that all the dispositions are complete and have passed. It will continue to ask for dispositions until all the "incomplete"s have been resolved, so only the final one matters.

**Comment by iabent** [comment]
Makes sense, what about the results of 8407 to 8416? I know 8416 ran:
***ACVP [STATUS][acvp_dispatch_vector_set:1888]--> ACV Operation: HMAC-SHA2-512
***ACVP [STATUS][acvp_process_vector_set:1931]--> Successfully processed KAT vector set
***ACVP [STATUS][acvp_process_vsid:1861]--> POST vector set response vsId: 8416
***ACVP [STATUS][acvp_submit_vector_responses:827]--> Submitting vector responses to https://demo.acvts.nist.gov:443/acvp//acvp/v1/testSessions/1586/vectorSets/8416/results
***ACVP [STATUS][acvp_submit_vector_responses:837]--> Finished POSTing KAT vector responses

But the end of my results summary looks like this:

{
    "vectorSetUrl" : "/acvp/v1/testSessions/1586/vectorSets/8405",
    "status" : "passed"
  }, {
    "vectorSetUrl" : "/acvp/v1/testSessions/1586/vectorSets/8406",
    "status" : "passed"
  }, {
***ACVP [STATUS][acvp_get_result_test_session:1974]--> Passed all vectors in test session

Thanks again for all the replies! Very appreciated :)

**Comment by iabent** [comment]
Hopefully you guys see this message but I was wondering if the American Government shutdown means that the demo server is also shut down? Ever since my return from the holidays I have not been able to connect (I get couldn't resolve Hostname) I tried using the setup that ran fine before 2019 as well as updating my libacvp-master with the newest build.

Thanks!

**Comment by bfussell** [comment]
Yes, the demo server is offline due to the government shutdown.

**Comment by iabent** [comment]
Thanks for the swift reply! That explains it

**Comment by iabent** [comment]
Good morning, sadly still waiting on the government to reopen but alas. 

I had a quick question: Is there somewhere where I can get my hands on a sample JSON vector set? One that I would be receiving from the demo server if it was up? It would be useful to have as a reference with my work going forward.

Thanks!

**Comment by bfussell** [comment]
The ACVP document github has many example JSON vector sets. 
https://github.com/usnistgov/ACVP

Our internal testing includes some, but they are divided up based on algorithm. Is there a specific algorithm you are looking for ?

Someone else on our team may have a full vector set, but I don't.

**Comment by iabent** [comment]
Nothing specific, was currently thinking of looking at AES for now because that is the most familiar to me. I had a look through some of the ACVP github code but didn't see any vector sets, but I guess I didn't look hard enough! Where would they be located? If you don't know off the top of your head I can get to digging.

As always, thank you for the quick response!

**Comment by iabent** [comment]
Hello! It's me again, randomly popping in with inquiries :)

I had a simple question: Is it planned to keep this libacvp tool up to date with the latest updates from ACVP indefinitely? Or is is more a "early demo to show how it works, after ACVP goes live we will leave it as is" type tool? I ask as one of our engineers is playing around with libacvp and found that "RSA Decryption Operation Primitive (RSADP)" is missing entirely from the tool, yet ACVP itself has it being supported. Is libacvp something he can rely on to come back to see how algorithms are implemented?

Just wanted to get your take on it :) Thanks so much, as always!

**Comment by bfussell** [comment]
We will continue to enhance it.  There are a few items that the server supports that we do not today.  SHA-3 and SHAKE are being developed now.  KAS non-comp mode is future as is RSADP.  We do not have timelines for those two, but SHA-3/SHAKE should be done within the next 30 days.

As always, since this is an open source project all contributors are welcome to develop features that are not yet coded and submit a PR so they can be included for all.

**Comment by iabent** [comment]
Thank you, as always, for the response :)

Another quick question, if you will. We're having some difficulty accessing the demo server as of yesterday (getting a 404 error when we try to run the client, which was working fine otherwise) Did something change recently? We'll be updating the libacvp code to see if that helps, but does this ring any bells? 

Thank you so much, as always!

**Comment by bfussell** [comment]
It was down between 5:00ET and 5:30 yesterday for maintenance.  There was also some significant changes to registration at the server which we are working to implement on the client, so the most recent code will still not work until we complete the changes and push it out.

**Comment by iabent** [comment]
Thank you so much for the quick reply :) Much appreciated!
