### ISSUE TITLE
Get demo certificate number

### ISSUE THREAD

**Issue by bserma** [cisco/libacvp#328]
Hello, 
I have some troubles with the libacvp.
I succeeded to generate a testSession.json thanks to the command ./app/acvp --sample
but i can not generate or find the certificate number. 
Can you help me please ? What is the command please ? 

Thanks for advance

**Comment by bfussell** [comment]
In general the steps are:

1. Get credentials from NIST for the demo server
2. Modify the app code as needed to match your crypto module.
3. Modify the metadata as needed to match your crypto module.
4. Test your crypto module using the demo server. Need to specify your algorithms using either command line options or via app code modification.  Need to include command line option --fips_validation metadata/<your metadata>.
5. Once that test passes request production credentials from NIST and run the same test using the production server.
6. You can check results and certificate information using the --get command line option.

The process is discussed in the acvp-spec in the ACVP github, https://github.com/usnistgov/ACVP

**Comment by bserma** [comment]
Thank you for this response.

Nevertheless, I do not understand one thing.
I follow the ReadMe:

> 
> Download vectors on network accessible device: ./app/acvp_app --<algs of choice or all_algs> --vector_req <filename1>
> 
> Copy vectors and acvp_app to target: ./app/acvp_app --all_algs --vector_req <filename1> --vector_rsp <filename2>
> 
> Copy respones(filename2) to network accessible device: ./app/acvp_app --all_algs --vector_upload <filename2>
It worked ofr an offline test but What are the command to perfom a certification ?

I think the scenario is:
- Create a vendor
- Create a person
- Create a module
- Perform the tests
- Send the command with the fips_validation

About my scenario, is it correct ?

**Comment by bfussell** [comment]
That is correct, except you also need to create your OE. The --fips_validation option needs a file, an example is metadata/validation.json.  You must modify metadata/validation.json to match your information and when you perform the upload it will assign the metadata information to your test results and return the validation request number.  You can monitor the request number until the request is complete and it will return your cert information.  Here are the steps:

app/.libs/acvp_app --cmac --vector_req cmac_req.json
app/.libs/acvp_app --cmac --vector_req cmac_req.json --vector_rsp cmac_rsp.json
app/.libs/acvp_app --cmac --vector_upload cmac_rsp.json --fips_validation metadata/validation.json
response is:
}, {
  "url" : "/acvp/v1/requests/1252",
  "status" : "initial"
} ]
app/.libs/acvp_app --get "/acvp/v1/requests/1252"
response is:
}, {
  "url" : "/acvp/v1/requests/1252",
  "status" : "approved",
  "approvedUrl" : "/acvp/v1/validations/31182"
} ]
app/.libs/acvp_app --get "/acvp/v1/validations/31182" --verbose
response will show your metadata and the algorithm(s) that were tested.

**Comment by bserma** [comment]
Thank you, the commands work now, but...
When I edit my metadata file, there is the field "id".
I replace the "id":1 by the my vendor id (this vendor id was created when i created a vendor : it is /acvp/v1/vendors/id). 
But when I type the last command to validate : app/.libs/acvp_app --cmac --vector_upload cmac_rsp.json --fips_validation metadata/validation.json

I have an error : 
> ***ACVP [ERR][find_vendor:378]--> Invalid 'id' (1)
> ***ACVP [ERR][acvp_oe_ingest_metadata:3275]--> Failed to parse 'modules' from metadata JSON
> Failed to read validation_metadata_file

So I don't understand the signification of this id.
Can you help me please ?

Thanks for advance.

**Comment by bfussell** [comment]
It's been deprecated in the protocol definition, but it's still in the client library code.  It's simply a non-zero index. If you should set it to 1 for vendors modules and oe just like the example json and make sure
the validaion.json maintains the same format as he example.

**Comment by bserma** [comment]
Ok, but I don't understand one thing.
I performed this command to create vendors, person, modules, oe, etc... with my vendors.json, ...
I can see it by the command:
./app/acvp_app --get /acvp/v1/modules/11496

And when I see the validation with this command ./app/acvp_app --get /acvp/v1/validations/31182. It does not correspond with my files in metadata.

Have you any idea about the origin of the problem ?

Thanks

**Comment by bfussell** [comment]
Did you copy your vendor, module and oe information into the validation.json file ?

**Comment by bserma** [comment]
Yes, I edited the file with the information of my vendor, module and oe information (the same information which I put in vendor.json, module.json and oe.json.

**Comment by bfussell** [comment]
Enable --verbose when performing the --fips_validation and you should see what vendor, contact and oe that is matching the search.  

Looks like your these are correct it is matching the default information that was in the metadata/ directory.

**Comment by bserma** [comment]
I used the verbose with the --fips_validation and the response contains /acvp/v1/modules/11498.
And when I "GET request" /acvp/v1/modules/11498, I found my module. Yes it works. Thank you @bfussell !!!

I think that I made a mistake the first time.
I will recreate a new module to test. If it succeeds, I will close the issues.

Again Thank you @bfussell

**Comment by bserma** [comment]
I follow these instructions:

`./app/acvp_app --post ./metadata_serma/vendor.json  /acvp/v1/vendors`
Response --> ./app/acvp_app --get /acvp/v1/vendors/11267

`./app/acvp_app --post ./metadata_serma/person.json /acvp/v1/person`
Response --> ./app/acvp_app --get /acvp/v1/persons/15028

`./app/acvp_app --post ./metadata_serma/module.json /acvp/v1/modules --verbose`
Response --> ./app/acvp_app --get /acvp/v1/modules/11504

`./app/acvp_app --post ./metadata_serma/oe.json /acvp/v1/oes --verbose`
Response --> ./app/acvp_app --get /acvp/v1/oes/21335

`./app/acvp_app --all_algs --vector_req ./serma_test_req.json --verbose`

`./app/acvp_app --all_algs --vector_req ./serma_test_req.json --vector_rsp ./serma_test_rsp.json --verbose`
Response  --> vsId: 80106

`./app/acvp_app --all_algs --vector_upload ./serma_test_rsp.json --fips_validation ./metadata_serma/validation.json --verbose`
Response --> /acvp/v1/requests/1314

`./app/acvp_app --get /acvp/v1/requests/1314 --verbose`
Response --> /acvp/v1/validations/41246

`./app/acvp_app --get /acvp/v1/validations/41246`
Response --> "validationId" : "A10069"

But to my mind, my testSession is not certified, is it correct ?
If Yes how to certificied my testSession and get a certificate number please ?

Thanks for advance

**Comment by bfussell** [comment]
That was run on the demo server, correct ?
Looks like everything was successful and your validation number is A10069.
So you have proven that you can perform the test and now you need to work with NIST to
get production server credentials and re-run the exact same steps using the production server.

However on the production server you don't automatically get a certificate number,  they manually approve it.
