### ISSUE TITLE
Scripts nist_setup is outdated

### ISSUE THREAD

**Issue by celic** [cisco/libacvp#330]
The url should be updated to `demo.acvts.nist.gov`.

As well the key file is not produced by NIST. The user should already possess that file.

**Comment by bfussell** [comment]
export ACV_SERVER=demo.acvts.nist.gov
set ACV_SERVER=demo.acvts.nist.gov

These seem to be correct.

I'll update the key information to say user generated

**Comment by celic** [comment]
My mistake the workspace is indeed out of date. I'll close the other issue as well.
