### ISSUE TITLE
Failed to login with ACVP server

### ISSUE THREAD

**Issue by hexiangqwqwqw** [cisco/libacvp#335]
Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [ERR][acvp_curl_http_post:687]--> Curl failed with code 77 (Problem with the SSL CA cert (path? access rights?))

***ACVP [STATUS][log_network_status:1397]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
(null)

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP server

**Comment by bfussell** [comment]
That generally means there is a problem with your CA cert file. Are you certain it is at certs/acvp.nist.gov.crt ? Does it have reasonable access rights ?

You may want to use a fully explicit path.

**Comment by hexiangqwqwqw** [comment]
I use a fully explicit path
hexiang@hexiang-VirtualBox:~/work/ACVT/libacvp-master/app$ ./acvp_app  --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/hexiang/work/ACVT/libacvp-master/certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  kevin.micciche_hpe_server.cer
    ACV_KEY_FILE:   myserver.key

***ACVP [ERR][acvp_curl_http_post:687]--> Curl failed with code 35 (SSL connect error)

***ACVP [STATUS][log_network_status:1397]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp:
(null)

***ACVP [STATUS][acvp_login:2067]--> Login Send Failed
***ACVP [ERR][acvp_run:2585]--> Failed to login with ACVP server

**Comment by bfussell** [comment]
That's a  pretty generic TLS connection failure, I'd check with the NIST server folks.
You can open an issue here:   https://github.com/usnistgov/ACVP

**Comment by hexiangqwqwqw** [comment]
How to overcome that

**Comment by bfussell** [comment]
Check with the NIST server folks.
You can open an issue here: 
https://github.com/usnistgov/ACVP
