### ISSUE TITLE
invalid chunk

### ISSUE THREAD

**Issue by bserma** [cisco/libacvp#373]
Hello

I want to validate my test vectors for an aes on dev server thanks to this command:
`./app/acvp_app --aes --vector_upload ./test_rsp.json --fips_validation ./metadata/validation.json --verbose`
and I have this error message
`***ACVP [STATUS][acvp_upload_vectors_from_file:1016]--> Uploading vectors from response file...
***ACVP [INFO][acvp_upload_vectors_from_file:1087]--> Received vsid_url=/acvp/v1/testSessions/76834/vectorSets/169553
malloc_consolidate(): invalid chunk size
`
I don't understand my error because I use the default validation.json 

Can you help me please ?

Best regards

**Comment by abkarcher** [comment]
Hello,
Is this with the latest version of the code, or an older version? If older, could you try with latest? 

Thanks,
Andrew

**Comment by bserma** [comment]
I update my depot but the problem still there.

**Comment by abkarcher** [comment]
Hello,

I was able to reproduce and am working on it. Thank you for bringing this to our attention, and apologies for the inconvenience.

Andrew

**Comment by abkarcher** [comment]
Hello,

Can you pull the latest and try again? That issue should be resolved. 
Please let us know if you experience any other errors around that functionality as well.

Thanks,
Andrew

**Comment by bserma** [comment]
Hello,
I test the newest version and it works. There is no invalid chunk.
But when I want to validate my test vectors
`The Vendor(1) does not exist in server DB. Must create first!`

So the problem is now functional.
But my vendor is created so I don't understand.

**Comment by bserma** [comment]
Ok I found my problems.
I confirm that the problem about invalid chunk is closed.
Thanks @abkarcher .

**Note** 
I don't know if it is a bug or not but I found this: 
When I create a vendor thanks this command:
`./app/acvp_app --post ./metadata/vendor.json  /acvp/v1/vendors`

The result automaticaly add http in website attributes:
see  `./app/acvp_app --get /acvp/v1/vendors/11446` --> webmail = http:toto.com

And when I validate my module with this command:
`./app/acvp_app --all_algs --vector_upload ./serma_test_rsp.json --fips_validation ./metadata_serma/validation.json --verbose`
I must add "http" manually to validate my module.

If 'http' is not present I have this error:
```
ACVP [INFO][log_network_status:1422]--> GET...
        Status: 200
        Url: https://demo.acvts.nist.gov:443/acvp/v1/vendors?name[0]=eq:Toto&website[0]=eq:toto.com
        Resp:
[ {
  "acvVersion" : "1.0"
}, {
  "totalCount" : 0,
  "incomplete" : false,
  "links" : {
    "first" : "/acvp/v1/vendors?offset=0&limit=20&website[0]=eq:toto.com&name[0]=eq:Toto",
    "next" : null,
    "prev" : null,
    "last" : "/acvp/v1/vendors?offset=0&limit=20&website[0]=eq:toto.com&name[0]=eq:Toto"
  },
  "data" : [ ]
} ]

ACVP [ERR][verify_fips_module:2419]--> The Vendor(1) does not exist in server DB. Must create first!
```
Is it a normal ?

Best regards.

**Comment by abkarcher** [comment]
Hello,
I'm glad you were able to get it working! We have run into this with the NIST server as well - It is normal for the server to append the http: it seems, though I have posted an issue with them in the last few weeks just to find out the reasoning.

Because of things like this, it's a good practice to check the URL they provide when you submit a vendor (using --get) and ensure the validation you are submitting matches the exact version of the vendor that the server has listed as "approved".
