### ISSUE TITLE
Questions about performing fips validation for specific modes

### ISSUE THREAD

**Issue by jonahmvp** [cisco/libacvp#383]
Hello,

I have some questions about performing a fips validation for a specific algorithm using libacvp:

Say I wanted to perform a fips validation for only AES CBC and ECB modes. Currently when I download aes vectors using the command:

> ./app/acvp_app --aes --vector_req ./vectors

I receive vector sets for all AES algorithms. 
After processing only AES and CBC vector sets and performing a fips validation using commands:

> 	./app/acvp_app --post ./metadata/person.json
	./app/acvp_app --aes --vector_upload JSONresponses --fips_validation ./metadata/validation.json --verbose

I get the following error:

> ***ACVP [ERR][acvp_get_result_test_session:2618]--> Missing submissions for one or more vector sets. Please submit responses for all vector sets.
***ACVP [ERR][acvp_validate_test_session:2801]--> This testSession cannot be certified. Required disposition == 'pass'.

1. How can I use libacvp to download only the vectorsets that correspond to specific modes such as ECB and CBC? If this is possible, where in the app source code would I make this modification?

**Comment by bfussell** [comment]
You just need to go into app_main.c and comment out the flavors of AES you do not want to register for in enable_aes() and re-compile.

**Comment by bserma** [comment]
I have a question about that : 
for example in aes cbc mode , the parameter plaintext is set thanks to this command.
`rv = acvp_cap_sym_cipher_set_parm(ctx, ACVP_AES_CBC, ACVP_SYM_CIPH_PTLEN, 1536);`

The value 1536 is just an example or it is based on ACVP protocol.
Can we have a bigger value than 1536 or not ?

Best regards,

**Comment by bfussell** [comment]
That value is dependent upon your crypto module. All of the values used in the registration in app_main.c are examples only, mostly based on openssl FOM.

**Comment by bserma** [comment]
ok thanks
