### ISSUE TITLE
Unable to login to demo.acvts.nist.gov; 401 error received

### ISSUE THREAD

**Issue by sandeepumeshbe** [cisco/libacvp#386]
Hello

We are facing a issue which states : 401 error received from server and the message is "The supplied one time password could not be verified". Can you please help us on how we can proceed further ?

Additional details:

Steps:
git pull
configure, make

Script file details:
$cat scripts/nist_setup.sh
export ACV_URI_PREFIX=/acvp/v1/
export ACV_API_CONTEXT=acvp/
export ACV_CA_FILE=certs/acvp.nist.gov.crt
export ACV_KEY_FILE=<path_of_key_file/key_file>
export ACV_CERT_FILE=<path_of_certs_file/certificate_file>
export ACV_TOTP_SEED="A30YEfyjqh/QWvaFltvujukj5ujNQxhUzXd7xF5I7Oc=" <Note: this is not actual seed obtained>
export ACV_PORT=443
export ACV_SERVER=demo.acvts.nist.gov

command executed:
./app/acvp_app --sample --aes

output:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  <path_of_certs_file/certificate_file>
    ACV_KEY_FILE:  <path_of_key_file/key_file>

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSNAME (32 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSVERSION (64 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_ARCHITECTURE (16 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_PROCESSOR (64 char max.)
***ACVP [ERR][log_network_status:1466]--> 401 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> {
  "acvVersion" : "1.0",
  "error" : "The supplied one time password could not be verified"
}
***ACVP [STATUS][acvp_login:2332]--> Login Send Failed
***ACVP [ERR][acvp_run:2964]--> Failed to login with ACVP server

Time sync'd with time-b-b.nist.gov using NTP and current time in system is:

Mon Apr 13 14:08:56 CDT 2020

Other system Environment:
AIX 7.2 on Power 7
gcc (GCC) 8.3.0
openssl 1.0.2t version

We further checked with Jason Arnold regarding the cert and TOTP seed, he collected the relevant files from us and confirmed that it is working in his environment. So, clearly we are missing something in our client environment which does not satisfy demo server. Can you please provide your inputs ?
Thanks

**Comment by bfussell** [comment]
We just went through refreshing our credentials on March 25 and during that process Jason had issues properly generating the TOTP. I'm not saying that is what you are encountering, but was curious when you got these credentials, was it recently ?

One of the issues with ours was the TOTP seed had a '\' in the string which is invalid.

**Comment by sandeepumeshbe** [comment]
Hello Barry

We got the certificate on the same day - 25th March. 
Please let us know if you want us to try with any other branch ?

Thanks

**Comment by bfussell** [comment]
Have you checked your seed for illegal characters ? Such as ) or \ ?
Here is a description that defines valid characters.  

https://base64.guru/learn/base64-characters

If you have illegal characters you'll need to ask Jason for a new seed.

We've had no changes in that area of the code for quite some time, when did you download the source code from the libacvp github ?  There is no other branch.

Regards,

Barry

**Comment by sandeepumeshbe** [comment]
Hello

There are only two other characters apart from alpha-numeric chars in seed: 
/(somewhere in middle of the seed) and 
=(as the last seed character)

Can you please let us know if it valid to provide like this:
export ACV_TOTP_SEED="A30YEfyjqh/QWvaFltvujukj5ujNQxhUzXd7xF5I7Oc="
We have provided seed within quotes, and = character is also provided. 

Thanks

**Comment by bfussell** [comment]
Yes, that is a valid way to set your environment variable.

**Comment by jarnold01** [comment]
Hi @sandeepumeshbe , just wanted to add that when I successfully tested your credentials from my libacvp client installation, I did NOT include the double-quotes (") when setting the ACV_TOTP_SEED environment variable.

Here is how I set it:

export ACV_TOTP_SEED=A30[removed]Oc=

Hope this helps.
