### ISSUE TITLE
Request for expected result after requesting sample test vector

### ISSUE THREAD

**Issue by luckywqe** [cisco/libacvp#387]
Hi,

I built a non-runtime libacvp application and tried to request a sample test vector and its expected answer. It looks good to have the downloaded hash test vector where the tag "isSample" is marked as true, but later I got a failed response from server while trying to get the expected answer.

Here is my testing steps.
1../acvp_app --hash --vector_req ./testvector/hash_req.json --sample --verbose

Vector sets are successfully downloaded 
"vectorSetUrls": [
        "\/acvp\/v1\/testSessions\/81129\/vectorSets\/188932",
        "\/acvp\/v1\/testSessions\/81129\/vectorSets\/188933",
        "\/acvp\/v1\/testSessions\/81129\/vectorSets\/188934",
        "\/acvp\/v1\/testSessions\/81129\/vectorSets\/188935",
        "\/acvp\/v1\/testSessions\/81129\/vectorSets\/188936"

Tag "isSample" are also marked as true
"vsId": 188932,
    "algorithm": "SHA-1",
    "revision": "1.0",
    "isSample": true,

2../acvp_app --get /acvp/v1/testSessions/81129/vectorSets/188932/expected --verbose

Get the error message "error" : "tsId was not found in the JWT"
***ACVP [INFO][log_network_status:1445]--> POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [STATUS][acvp_login:2109]--> Login successful
***ACVP [ERR][log_network_status:1418]--> 401 error recieved from server. Message:
***ACVP [ERR][log_network_status:1419]--> {
  "acvVersion" : "1.0",
  "error" : "tsId was not found in the JWT"
}
***ACVP [INFO][log_network_status:1425]--> GET...
	Status: 401
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/81129/vectorSets/188932/expected
	Resp:
{
  "acvVersion" : "1.0",
  "error" : "tsId was not found in the JWT"
}

GET Response: {
  "acvVersion" : "1.0",
  "error" : "tsId was not found in the JWT"
}

Not quite sure if I misuse the command, does anyone have idea?

Thanks,
Sean

**Comment by bfussell** [comment]
The client will automatically print out the sample output when you include --sample on the command line AND there was a failure in your responses.  It does not request the sample data unless you have a failure. You don't have to request it using --get.  However, having just tested the --sample operation it appears that sample output is truncated. I just created a PR to fix that issue so it will be available as soon as it is approved.

**Comment by luckywqe** [comment]
Hi @bfussell 

Thanks for your clarification. I will try it again when the output-truncated issue is fixed.

**Comment by luckywqe** [comment]
Hi @bfussell,

I see your modification work on acvp.c to dump all sample code. Just check out the latest code and have a test, it seems the  output-truncated issue is still there.  
Do you have any suggestion ? 

***ACVP [INFO][log_network_status:1423]--> GET Vector Set...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/81326/vectorSets/189585
	Resp:
[ {

  "acvVersion" : "1.0"

}, {

  "vsId" : 189585,

  "algorithm" : "HMAC-SHA-1",

  "revision" : "1.0",

  "isSample" : true,

  "testGroups" : [ {

    "tgId" : 1,

    "testType" : "AFT",

    "keyLen" : 264,

    "msgLen" : 128,

    "macLen" : 32,

    "tests" : [ {

      "tcId" : 1,

      "key" : "C772583B5B9BCA8D22A008EEA565125AFA076A848D2CC64C7CA9EA434F681DB4DC",

      "msg" : "8CCC0D3F24DFE38E2B5CB9BE6E238E3B"

    }, {

      "tcId" : 2,

      "key" : "8F5BFAE3EA70DF221C0A59515B7B44F8D7F7D8FA9E64B026EFC872098AE7C5DA53",

      "msg" : "C2C18B47A01F892AF5551F22E68F0898"

    }, {

      "tcId" : 3,

      "key" : "08268BD86A54AAA55F2439921B298E8B344DDE7AB262219342EFE2D76CABA0E37D",

      "msg" : "18E33307E8DEF7509B6BEA2B5F3815A0"

    }, {

      "tcId" : 4,

      "key" : "AB44471D8BCFC4B2D74DDA8C68C3F1EF222A4FC2448EF6D1C608C7A950119DB011",

      "msg" : "BEBBCAE6397975EB6947FBFA69CC7DAC"

    }, {

      "tcId" : 5,

      "key" : "576ED445F19E063DDB91634F9C57F2C0735EFFC2A96AFC6CFD6C894DA2A5592011",

      "msg" : "7A0F51603ED783DDDAA99F4EF20E4162"

    }, {

      "tcId" : 6,

      "key" : "0B285CD88E958167AB07FC14DA215F116E7280E8DFD145AE898A7F888F1346DC79",

      "msg" : "6DAE51A1F208F39EAB3A88C9854E3F16"

    }, {

      "tcId" : 7,

      "key" : "D9306A1D54A3E8EDC1C22AC4E04634C6999A09B8DC9CDA0ACF971CBC12FD59E7B6",

      "msg" : "468278B0BD0F3D841B034E60BF33FA0F"

    }, {

      "tcId" : 8,

      "key" : "4E3274BCCC496A2B390D97A87C624117106626EA311611198E56E9B1EB7F913226",

      "msg" : "5764F77A42A491949E1718044FCCBD8C"

    }, {

      "tcId" : 9,

      "key" : "6D59FA0209BF2A8CBF0499DA8A808E17B513150FD6A375D2424DD1CE99C2B5EDA2",

      "msg" : "CC85EC4A05EDF60ED98E8C0FADE465FA"

    }, {

      "tcId" : 10,

      "key" : "4B0B077D8E688E1F441D76DD42C14B7E26C95CF4E23B2E31CD50AC1C1616E37FA5",

      "msg" : "BBE2DAFDF***ACVP [STATUS][acvp_process_vsid:2417]--> Saving vector set /acvp/v1/testSessions/81326/vectorSets/189585 to file...
***ACVP [STATUS][acvp_run:3024]--> Successfully downloaded vector sets and saved to specified file.

**Comment by bfussell** [comment]
As I noted above the samples are only generated when the server has detected a failure in your response and told the client. Your command line is only downloading the request vectors. 

Here's an example of the proper steps.


app/acvp_app --kas_ffc --vector_req kas_ffc_req.json --sample
app/acvp_app --kas_ffc --vector_req kas_ffc_req.json --vector_rsp kas_ffc_rsp.json  <--- offline run on target device
app/acvp_app --kas_ffc --vector_upload kas_ffc_rsp.json --sample

**Comment by luckywqe** [comment]
Hi @bfussell ,

Great notification, following your procedure the sample can be correctly retrieved from server. 
Thank you very much.

Sean
