### ISSUE TITLE
Unable to login -- 403 "Forbidden" Error

### ISSUE THREAD

**Issue by yeongk** [cisco/libacvp#392]
Hi,

While connecting to the NIST demo server using libacvp acvp_app, I get the 403 error. The session log is listed below. 

$ ./app/acvp_app --aes --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /Users/yeongk/imprivata/stash/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /Users/yeongk/imprivata/dev/nist/demo.cer
    ACV_KEY_FILE:   /Users/yeongk/imprivata/dev/nist/private_key.pem

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:477]--> HTTP User-Agent: libacvp/1.0;Darwin;18.7.0;x86_64;Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz;GCC/4.2.1

***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 403
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1466]--> 403 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> <html><head><title>Error</title></head><body>Forbidden</body></html>
***ACVP [STATUS][acvp_login:2332]--> Login Send Failed
***ACVP [ERR][acvp_run:2969]--> Failed to login with ACVP server

My env setting is as follows:
$ set | grep ACV
ACV_API_CONTEXT=acvp/
ACV_CA_FILE=/Users/yeongk/imprivata/stash/libacvp/certs/mozzila_trust_anchors.pem
ACV_CERT_FILE=/Users/yeongk/imprivata/dev/nist/demo.cer
ACV_KEY_FILE=/Users/yeongk/imprivata/dev/nist/private_key.pem
ACV_SERVER=demo.acvts.nist.gov
ACV_TOTP_SEED=YyWJflb70CJ7l135LM/4Jog0visDgmkEqWFFeEmQfeG6KzWt0Nyl3XmN2okwnOVc8/9xLM12 <== obfuscated

Any help would be greatly appreciated.

Thanks

**Comment by abkarcher** [comment]
Hello,
In my experience 403 is only returned by server when the cert or key are invalid or expired. Are you able to re-verify that those files are in the right place and have not expired?

The server responds with a different more specific error message for TOTP issues, just for the record.

It also seems that the NIST server has had some connectivity issues for certain folks using other clients in the last day or two. This has not been an issue that we or our users have experienced with libacvp, but it is possible there is some work happening on their end preventing access.

Thanks,
Andrew

**Comment by yeongk** [comment]
If I purposely modify the cert to make it an invalid cert, it gives me a SSL certificate-specific error. 

$ ./app/acvp_app --verbose --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /Users/yeongk/imprivata/stash/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /Users/yeongk/imprivata/dev/nist/demo_bad.cer
    ACV_KEY_FILE:   /Users/yeongk/imprivata/dev/nist/private_key.pem

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:477]--> HTTP User-Agent: libacvp/1.0;Darwin;18.7.0;x86_64;Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz;GCC/4.2.1

***ACVP [ERR][acvp_curl_http_post:720]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1464]--> Received no response from server.
***ACVP [STATUS][acvp_login:2332]--> Login Send Failed
***ACVP [ERR][acvp_run:2969]--> Failed to login with ACVP server

**Comment by bfussell** [comment]
You may want to follow this issue on the ACVP github. Most connection type issues tend to be associated with the server.

https://github.com/usnistgov/ACVP/issues/850#issuecomment-621607237

Regards,

Barry

**Comment by yeongk** [comment]
Turned out this was due to an issue on the server side. Now it is working fine. 

Thanks,
Yeong
