### ISSUE TITLE
(ACVP_AES_XTS, tweak) typo on line 558 in acvp_build_register.c

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#397]
Current line ---> switch (sym_cap->tweak->length) { ...
Should be   ---> switch (sl_list->length) { ...

    if (cap_entry->cipher == ACVP_AES_XTS) {
        json_object_set_value(cap_obj, "tweakMode", json_value_init_array());
        opts_arr = json_object_get_array(cap_obj, "tweakMode");
        sl_list = sym_cap->tweak;
        while (sl_list) {
            switch (sym_cap->tweak->length) {
            case ACVP_SYM_CIPH_TWEAK_HEX:
                json_array_append_string(opts_arr, "hex");
                break;
            case ACVP_SYM_CIPH_TWEAK_NUM:
                json_array_append_string(opts_arr, "number");
                break;
            default:
                break;
            }
            sl_list = sl_list->next;
        }
    }

Since the switch keeps switching on the first link list nodes length/value then it builds the json with either ["hex","hex"] or ["number","number"] when two tweakModes are present in cap.

**Comment by bfussell** [comment]
Thanks for pointing this out. Should be resolved by #398.
Note that since our crypto module does not support number tweak mode it is not supported in the client application code. If you need that mode you will need to provide the app code to access your crypto module that supports it.
