### ISSUE TITLE
KAT dispatch error: crypto module failed the operation

### ISSUE THREAD

**Issue by yeongk** [cisco/libacvp#401]
After obtaining rsa_keygen_req.json via ./app/acvp_app --rsa --vector_req, rsa_keygen_req.json was processed locally against a target crypto module to produce rsa_keygen_rsp.json.
When the following command was issued, however, an error shows up, "KAT dispatch error -- crypto module failed the operation" as follows:

$ ./app/acvp_app --rsa --vector_req rsa_keygen_req.json --vector_rsp rsa_keygen_rsp.json --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /Users/yeongk/imprivata/stash/libacvp/certs/mozzila_trust_anchors.pem        
    ACV_CERT_FILE:  /Users/yeongk/imprivata/dev/nist/Imprivata_Yeong_Kim_Demo.pem
    ACV_KEY_FILE:   /Users/yeongk/imprivata/dev/nist/onesign_private_key.pem

***ACVP [STATUS][acvp_run_vectors_from_file:864]--> Beginning offline processing of vector sets...
***ACVP [INFO][acvp_run_vectors_from_file:923]--> Received vsid_url=/acvp/v1/testSessions/83110/vectorSets/198701
***ACVP [STATUS][acvp_dispatch_vector_set:2501]--> Processing vector set: 198701
***ACVP [STATUS][acvp_dispatch_vector_set:2502]--> Algorithm: RSA
***ACVP [INFO][acvp_rsa_keygen_kat_handler:496]-->     Test group: 0
***ACVP [INFO][acvp_rsa_keygen_kat_handler:497]-->   infoGenByServer: true
***ACVP [INFO][acvp_rsa_keygen_kat_handler:498]-->        pubExpMode: fixed
***ACVP [INFO][acvp_rsa_keygen_kat_handler:499]-->         keyFormat: standard
***ACVP [INFO][acvp_rsa_keygen_kat_handler:500]-->            modulo: 2048
***ACVP [INFO][acvp_rsa_keygen_kat_handler:506]--> Found new RSA test vector...
***ACVP [INFO][acvp_rsa_keygen_kat_handler:511]-->         Test case: 0
***ACVP [INFO][acvp_rsa_keygen_kat_handler:512]-->              tcId: 1
***ACVP [ERR][acvp_rsa_keygen_kat_handler:585]--> ERROR: crypto module failed the operation
***ACVP [ERR][acvp_run_vectors_from_file:945]--> KAT dispatch error

Tracing the libacvp code, looks like the error was triggered by (cap->crypto_handler)(&tc) returning a value of 1. At that time, I see cap->crypto_handler shows the following value:
0x0000000100009760 (acvp_app`app_rsa_keygen_handler at app_rsa.c:303)

Any insight on why this crypto module failure error shows up?

Thanks

**Comment by bfussell** [comment]
Yes, openssl FOM 2.X does not have support for 186-4 RSA key gen. See the note in app/app_rsa.c:

    /*
     * IMPORTANT: Placeholder! The RSA keygen vector
     * sets will fail if this handler is left as is.
     *
     * Below, insert your own key generation API that
     * supports specification of all of the params...
     */
If your crypto module supports RSA key generation that meets FIPS 186-4 then you must add code to invoke it.

**Comment by yeongk** [comment]
Thanks for the info.
