### ISSUE TITLE
Invalid vendorId error

### ISSUE THREAD

**Issue by yeongk** [cisco/libacvp#402]
Invalid vendor id error is returned, when the following command was issued,
 ./app/acvp_app --verbose --rsa --vector_upload rsa_keygen_rsp.json --fips_validation metadata/validation.json

***ACVP [ERR][find_vendor:328]--> Invalid 'id' (11532)
***ACVP [ERR][acvp_oe_ingest_metadata:3356]--> Failed to parse 'modules' from metadata JSON
Failed to read validation_metadata_file

But, when we check the following (demo env):
./app/acvp_app --get /acvp/v1/vendors/11532,
vendor information is returned properly.

In addition to the vendor Id, so far we have also posted address, person, oe, and module, and gotten approved Ids for them from the NIST demo environment. 
What could be causing the invalid vendor Id? vendorId is defined as an attribute in the 'modules' block in validation.json. 'id' field in the 'modules' block is left as 1.

**Comment by bfussell** [comment]
I would need to see the validation.json file you are using.

**Comment by yeongk** [comment]
[validation.json.zip](https://github.com/cisco/libacvp/files/4613061/validation.json.zip)

**Comment by bfussell** [comment]
There are a few issues.  

First the demo environment has a bug in that it adds http: to your website information, the production server does not. So make this change in validation.json:

      "website": "http:imprivata.com",

Second, the validation.json does not match the contact information. The contacts registered for your vendor has:
    "phoneNumbers" : [ {
      "type" : "fax",
      "number" : "555-555-0001"
    } ]
and you validation.json has:
                    "phoneNumbers": [
                        { "number": "555-555-0001", "type": "fax" },
                        { "number": "555-555-0002", "type": "voice" }
                    ]
Either update your phone numbers in your vendor information or remove the voice number in validation.json.

Finally, our code is not using the vendor_id/id information consistently so there is a bug there.  The current workaround is to suimply use this in your modules information in validation.json:

            "vendorId": 1,

We'll open an internal bug to address the inconsistencies with vendor_id and id.

Regards,

Barry

**Comment by yeongk** [comment]
Thanks Barry. Greatly appreciated your help. I made mods per your suggestions, and now I can make further progress in the upload.

But, at the end of the upload, I get the following:
***ACVP [STATUS][acvp_get_result_test_session:2722]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2723]--> Note: Use verbose-level logging to see results of each test case
***ACVP [ERR][acvp_validate_test_session:2827]--> This testSession cannot be certified. Required disposition == 'pass'.

So, I checked the test session:
$ ./app/acvp_app --get /acvp/v1/testSessions/84257

***ACVP [STATUS][acvp_login:2341]--> Logging in...
***ACVP [STATUS][acvp_login:2361]--> Login successful
***ACVP [ERR][log_network_status:1466]--> 401 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> {
  "acvVersion" : "1.0",
  "error" : "tsId was not found in the JWT"
}
***ACVP [STATUS][acvp_run:3000]--> GET Response:

{
  "acvVersion" : "1.0",
  "error" : "tsId was not found in the JWT"
}

NOTE: I was initially using the json structure provided in Appendix C.1 of https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_rsa.html. One thing I noticed, however, was that without the jwt/url/vectorSetUrls block, it errored out. So, I replaced the first block ("{ "acvVersion": <acvp-version> }") with the first block from the request json I got from the --vector_req session. So, my response json structure looks like the following:
{{"jwt":"...", "url": "...", "vectorSetUrls":[.....]},
{"vsId: xxx, "algorithm":.....}}

So, I decomposed the jwt to see if tsId is really missing there:
{7 items
"jti":"14a076ef-9198-4765-a3be-5ccad5fe238e"
"iat":1589309130
"sub":"1.2.840.113549.1.9.1=#1612796b696d40696d707269766174612e636f6d,CN=acvp.imprivata.com,OU=NIAP,O=Imprivata Inc,L=Lexington,ST=Massachusetts,C=US"
"iss":"NIST ACVTS"
"exp":1589310930
"vsId":"[205344]"
"tsId":"84257"
}

As you can see, tsId 84257 is included in jwt. Any insight on this error? Could be related to the response json structure issue?

By the way, I noticed that in Appendix B.1 of https://github.com/usnistgov/ACVP/blob/master/artifacts/acvp_sub_rsa.html, vsId is defined as a number, but libacvp --rsa --vector_req returns vsId as a string. Looks like this needs to be corrected in libacvp.

**Comment by bfussell** [comment]
Your test responses failed. Use --get_results to obtain specifics about the failure

**Comment by yeongk** [comment]
--get_results with --verbose flag doesn't seem to provide any more specifics about the failure. Is there other way to get more info on the failure?

$ ./app/acvp_app --get_results rsa_keygen_rsp.json --verbose

***ACVP [INFO][log_network_status:1427]--> GET Vector Set Result...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/84257/results
	Resp:
[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/84257/vectorSets/205344",
    "status" : "error"
  } ]
} ]

***ACVP [STATUS][acvp_get_result_test_session:2722]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2723]--> Note: Use verbose-level logging to see results of each test case

**Comment by bfussell** [comment]
acvp_app --get_results testSession84257.json --verbose

Don't pass the response file pass the testSession file that was generated with your original test session request.

**Comment by yeongk** [comment]
Hmmm..  Still not providing more specifics.
$ ./app/acvp_app --verbose --get_results testSession_84257.json

***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [STATUS][acvp_login:2361]--> Login successful
***ACVP [INFO][log_network_status:1427]--> GET Vector Set Result...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/84257/results
	Resp:
[ {
  "acvVersion" : "1.0"
}, {
  "passed" : null,
  "results" : [ {
    "vectorSetUrl" : "/acvp/v1/testSessions/84257/vectorSets/205344",
    "status" : "error"
  } ]
} ]

***ACVP [STATUS][acvp_get_result_test_session:2722]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2723]--> Note: Use verbose-level logging to see results of each test case

**Comment by bfussell** [comment]
The get_results operation seems to be working fine.  I think you're hitting a server state issue, or maybe not an issue, but a state where get_results cannot obtain the specifics you need. See https://github.com/usnistgov/ACVP/issues/618

I recommend you open a case with NIST on their github.

**Comment by yeongk** [comment]
Thanks Barry. Will open a case with NIST.

btw, I attached the upload json used. Is the json structure correct? Just want to make sure the failure is not due to an incorrect json structure.
[upload_validation.json.zip](https://github.com/cisco/libacvp/files/4618338/upload_validation.json.zip)

**Comment by bfussell** [comment]
Yes, that json format looks fine to me.

**Comment by yeongk** [comment]
Great! Thanks Barry. Opened a case with NIST.
