### ISSUE TITLE
how to build libacvp.so only?

### ISSUE THREAD

**Issue by joymcg** [cisco/libacvp#403]
Hi,
  I want to build libacvp.so only. How could I do that?
  I think libacvp.so is only depended on libcurl, so maybe we can just build this dynamic library with libcurl header files.  And when  build app or write my own app, I will link them all togther.

**Comment by abkarcher** [comment]
Hello,

We currently unfortunately do not have a configure/make target for just the library, though we hope to in the future. For now, you would just have to build the app and library together to get the library or modify the build process/app as needed. I will make a note of this!

Thanks,
Andrew

**Comment by joymcg** [comment]
Hello,
  Thanks for the apply.  Looking forward to the library configurable version.

**Comment by bfussell** [comment]
Addressed with PR #439
