### ISSUE TITLE
Support for KDF108 - requiresEmptyIv?

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#416]
I noticed "typedef enum acvp_kdf108_param"  doesn't currently have a param of: 

ACVP_KDF108_REQUIRES_EMPTY_IV 

in support of the below JSON value:

https://usnistgov.github.io/ACVP/artifacts/acvp_sub_kdf108.html#rfc.section.2.4
"requiresEmptyIv | Whether the IUT requires an empty IV for Feedback KDF. | boolean | true/false"

Feature was mentioned from the below github post:
https://github.com/usnistgov/ACVP/issues/729

Was this going to be added eventually, or should I not look to support it on my ACVP client?

**Comment by bfussell** [comment]
For the most part we only implemented things we could test. We, or you, could add that option and the library processing portion of the the option, but we have no way to test it. You'd have to also implement the app code to interface to your crypto module.

**Comment by zacwdev** [comment]
Are you alright with code being provided as a solution to just allow the requesting of the Vectorsets even though we have no way to test it - as I'm assuming from your comments above that openssl doesn't' support it? Or is interface code also required for it to be approved for merge?

**Comment by bfussell** [comment]
library code to request the vectorSets would be fine, however receiving, parsing and processing the vectorSets and providing them to the app side would be even better :) The code that interfaces with the crypto module is not necessary, we understand that may contain intellectual property.

**Comment by abkarcher** [comment]
Hello,

Support for this was added in PR #471. Please let us know if you experience any issues.

Thanks,
Andrew
