### ISSUE TITLE
Validation error on JSON payload when requesting Vectors for KDF108 DPI

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#417]
I'm having trouble requesting vectors for KDF108 Mode DPI with any arrangement of parameters. This isn't through the libacvp sample app, but through my own application which uses the libacvp library.

Counter and Feedback modes work fine. Below is the output of two different attempts.
I've viewed the ACVP_CTX *ctx structure in memory after calling acvp_cap_kdf108_set_parm() and it loads the DPI variables correctly. I've reviewed the acvp_build_kdf108_register_cap() definition code, and couldn't find anything odd on how the json object is getting built for DPI. I have not tried this request with the sample app.

***ACVP [STATUS][acvp_login:2340]--> Login successful

***ACVP [STATUS][acvp_register:1854]--> Building registration of capabilities...

***ACVP [STATUS][acvp_register:1860]--> Sending registration of capabilities...

***ACVP [INFO][acvp_register:1861]--> [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"KDF","revision":"1.0","prereqVals":[{"algorithm":"CMAC","valValue":"same"},{"algorithm":"HMAC","valValue":"same"},{"algorithm":"KAS","valValue":"same"},{"algorithm":"DRBG","valValue":"same"}],"capabilities":[{"kdfMode":"dpi","macMode":["CMAC-AES128","CMAC-AES192","CMAC-AES256","HMAC-SHA-1","HMAC-SHA2-224","HMAC-SHA2-256","HMAC-SHA2-384","HMAC-SHA2-512","CMAC-TDES"],"supportedLengths":[{"min":1,"max":4096,"increment":1}],"fixedDataOrder":["after fixed data","before fixed data","before iterator","none"],"counterLength":[0,8,16,24,32],"supportsEmptyIv":false}]}]}]

***ACVP [INFO][log_network_status:1442]--> POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:

***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KDF-1.0: Error converting value \u0022dpi\u0022 to type \u0027NIST.CVP.Crypto.Common.KDF.Enums.KdfModes\u0027. Path \u0027capabilities[0].kdfMode\u0027, line 1, position 280."
    ]
  }
]

***ACVP [ERR][acvp_register:1872]--> Failed to send registration

***ACVP [ERR][acvp_run:3007]--> Failed to register with ACVP server

------------------------Another Attempt below -----------------------------

***ACVP [STATUS][acvp_login:2340]--> Login successful

***ACVP [STATUS][acvp_register:1854]--> Building registration of capabilities...

***ACVP [STATUS][acvp_register:1860]--> Sending registration of capabilities...

***ACVP [INFO][acvp_register:1861]--> [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"KDF","revision":"1.0","prereqVals":[{"algorithm":"CMAC","valValue":"same"}],"capabilities":[{"kdfMode":"dpi","macMode":["CMAC-AES128"],"supportedLengths":[{"min":1,"max":4096,"increment":1}],"fixedDataOrder":["before fixed data"],"counterLength":[0],"supportsEmptyIv":true}]}]}]

***ACVP [INFO][log_network_status:1442]--> POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:

***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KDF-1.0: Error converting value \u0022dpi\u0022 to type \u0027NIST.CVP.Crypto.Common.KDF.Enums.KdfModes\u0027. Path \u0027capabilities[0].kdfMode\u0027, line 1, position 164."
    ]
  }
]

***ACVP [ERR][acvp_register:1872]--> Failed to send registration

***ACVP [ERR][acvp_run:3007]--> Failed to register with ACVP server

**Comment by bfussell** [comment]
This is much like issue #416 except that it appears we had begun the DPI mode implementation in the library, but found our test module did not support it so it was not completed. It's open source and we welcome enhancements and bug fixes via PR so everyone can benefit if you are so inclined.

Regards,

Barry

**Comment by zacwdev** [comment]
Thanks Barry,

If its not addressed in the future I'll try to circle back to this when time is available, and when my more pressing code is complete.
