### ISSUE TITLE
Division by 0 allowed in acvp_cap_hash_set_domain()

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#421]
In function acvp_cap_hash_set_domain() in file acvp_capabilities.c at line 2250 there is not a pre-check to make sure variable 'increment' which is the divisor in a modulo operation is not zero before attempting the operation resulting in a possible crash (signal SIGFRE - Arithmetic exception) or some other undefined behavior if/when 'increment' is ever the value 0.        

-------------------------------------------------------
    if (min % increment != 0) {
        ACVP_LOG_ERR("min(%d) MODULO increment(%d) must equal 0", min, increment);
        return ACVP_INVALID_ARG;
    }
    if (max % increment != 0) {
        ACVP_LOG_ERR("max(%d) MODULO increment(%d) must equal 0", max, increment);
        return ACVP_INVALID_ARG;
    }
-------------------------------------------------------

I believe the ACVP server requires this value to be >= 1, so maybe something right above line 2250 like this would help:

        if (increment < 1) {
            ACVP_LOG_ERR("increment must be 1 or greater");
            return ACVP_INVALID_ARG;
        }

Or:

        if (increment == 0) {
            ACVP_LOG_ERR("increment must not equal 0");
            return ACVP_INVALID_ARG;
        }

**Comment by abkarcher** [comment]
Hello,

Just addressed this in a PR. Thanks a ton for the find(s)!

Andrew

**Comment by zacwdev** [comment]
No problem. Thanks Andrew!
