### ISSUE TITLE
TOTP Windows has already been used 

### ISSUE THREAD

**Issue by luckywqe** [cisco/libacvp#427]
Hi, 

Just want to try posting vendor registration on demo server, but get a strange error "TOTP Windows has already been used" with error code 403 from server. The same situation is also happening on the response from the production server. 

The registration testing of my client app works fine before last week, but gets error code this week. I am wondering if the ACVP server hot-fix last week results in this error. 

Could anyone help on this issue? Thanks so much.

seanhuang@ubuntu:~/Downloads/acvp_demo$ ./acvp_app --post ./metadata/TUVAP/vendor.json /acvp/v1/vendors --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/nistca.cert
    ACV_CERT_FILE:  certs/TUVAP_Teddy_Tsui_Demo.pem
    ACV_KEY_FILE:   certs/private.key

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:477]--> HTTP User-Agent: libacvp/1.0;Linux;5.3.0-59-generic;x86_64;Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz;GCC/7.5.0

***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [STATUS][acvp_login:2340]--> Login successful
***ACVP [INFO][acvp_post_data:2892]--> 
POST Data: [
...ignore...
]

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [INFO][log_network_status:1439]--> POST Login...
	Status: 403
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1466]--> 403 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Access denied! Reason: TOTP Window has already been used"
  }
]
***ACVP [STATUS][acvp_login:2332]--> Login Send Failed
***ACVP [ERR][acvp_post_data:2897]--> Failed to login with ACVP server

Sean

**Comment by bfussell** [comment]
This is working as intended. NIST added a limitation to how often you can request a JWT using a TOTP. You can only use a TOTP once and since a TOTP lasts 30 seconds there is a 30 second minimum before you can issue a new command/request a new session. If you try again after 30 seconds it should work fine.

**Comment by luckywqe** [comment]
Hi Barry,
I can feel the 30s limitation while querying request id since the --get process is done in one session. But it seems the post process will be divided into 2 continuous session requests by client app. From the log I can observe the first login is successful, and the second login failed. 

Do you have any suggestion on avoiding this situation while operating client app.
Sean

**Comment by abkarcher** [comment]
Hello,

Was this particular issue only with --post? I found we had been logging in twice accidentally when using --post and fixed it with a PR earlier (The fix is now in master). Thanks for the find.

Andrew

**Comment by luckywqe** [comment]
Hi Andrew,

The issue only happens with --post from my testing.
And great thanks for the fix, it works well now.

Sean
