### ISSUE TITLE
Question about JWT refresh

### ISSUE THREAD

**Issue by NorthHill-16** [cisco/libacvp#430]
Hi, I can successfully login to the ACVP server, however, when I try to upload my vector set, I get the error, 

***ACVP [ERR][log_network_status:1467]--> [{"acvVersion":"1.0"},{"error":"The provided JWT expired at 2020-06-18 05:04:15Z and is no longer valid. The JWT claims may be refreshed through the renewal process described in the specification."}]

I don't find there are any specification about it. May I know how to solve this problem?

**Comment by abkarcher** [comment]
Hello,

This is a result of a recent change with how the NIST server communicates errors to the client, and I am working on fixing it right now. A temporary fix is to use --resume_session testSession_XXXXX.json where XXXXX is the test session ID number printed at the beginning of the original session. 

Thanks,
Andrew

**Comment by NorthHill-16** [comment]
Thank you for your quick reply, the temporary solution works, hope the problem could be fixed soon, thanks.

**Comment by NorthHill-16** [comment]
Hi, @abkarcher 
I have no problem at download vector set by your temporary solution, but when I upload, I get a new error.

$: ./app/acvp_app --hash --vector_upload answer.json --resume_session testSession_XXXXX.json

***ACVP [STATUS][acvp_upload_vectors_from_file:1017]--> Uploading vectors from response file...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 239804
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027failed\u0027 status."
    ]
  }
]
***ACVP [ERR][acvp_upload_vectors_from_file:1145]--> Failed to submit test results for vector set - skipping...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 239806
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027failed\u0027 status."
    ]
  }
]
***ACVP [ERR][acvp_upload_vectors_from_file:1145]--> Failed to submit test results for vector set - skipping...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 239807
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027failed\u0027 status."
    ]
  }
]
***ACVP [ERR][acvp_upload_vectors_from_file:1145]--> Failed to submit test results for vector set - skipping...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 239808
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027processed\u0027 status.",
      "Unable to submit results when vector set in \u0027failed\u0027 status."
    ]
  }
]
***ACVP [ERR][acvp_upload_vectors_from_file:1145]--> Failed to submit test results for vector set - skipping...
***ACVP [STATUS][acvp_upload_vectors_from_file:1142]--> Sending responses for vector set 0
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Invalid JSON provided.",
    "context": [
      "Unable to deserialize body into two objects"
    ]
  }
]
***ACVP [ERR][acvp_upload_vectors_from_file:1145]--> Failed to submit test results for vector set - skipping...
***ACVP [STATUS][acvp_upload_vectors_from_file:1158]--> Tests complete, checking results...
***ACVP [STATUS][acvp_get_result_test_session:2701]--> Test session complete: some vectors failed, reporting results...
***ACVP [STATUS][acvp_get_result_test_session:2702]--> Note: Use verbose-level logging to see results of each test case
***ACVP [STATUS][acvp_list_failing_algorithms:796]--> Failing algorithms:
***ACVP [STATUS][acvp_list_failing_algorithms:798]-->     SHA-1
***ACVP [STATUS][acvp_list_failing_algorithms:798]-->     SHA2-224
***ACVP [STATUS][acvp_list_failing_algorithms:798]-->     SHA2-256
***ACVP [STATUS][acvp_list_failing_algorithms:798]-->     SHA2-384
***ACVP [STATUS][acvp_list_failing_algorithms:798]-->     SHA2-512

Is this error also relates to this issue?  Ps. The uploaded response vectors are all valid and correct.

**Comment by abkarcher** [comment]
Hello,
I haven't seen this before, but that seems like NIST is not happy with the responses somehow - you might be best off making an issue here to see if they can provide more information for what went wrong:

https://github.com/usnistgov/ACVP

I can't think of an immediate situation in which the client would cause issues here - though note that using --resume_session with --vector_upload is unnecessary (and doesn't do anything).

**Comment by abkarcher** [comment]
Actually, looking more closely, there seems to be a "vector set 0" in your responses file - this indicates that there is some sanity issues with either the original test cases or the response. Are you able to create a new test session and see if it has the same issues?

**Comment by NorthHill-16** [comment]
Hi, @abkarcher 

Thanks for all your replies. It is so interesting that all the issues are disappeared now. I can request a new testSession, download, and upload with no problem at this time. But today morning and afternoon, it happens to be the error above.

**Comment by NorthHill-16** [comment]
Hi, @abkarcher 
Should I close this issue? It seems not a client issue. I have not pull any code from libacvp, but the problems are all disappered.

**Comment by abkarcher** [comment]
Hello,

I'll go ahead and close it, but will poke around in the code a bit more to make sure there's nothing that may have caused this during --vector_req.

I will be making a PR soon to fix the refresh issue as well.

Thanks,
Andrew

**Comment by NorthHill-16** [comment]
Okay, thanks.
