### ISSUE TITLE
KDF135 TLS potential bug depending on order of parameter assignment.

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#436]
File: /src/acvp_capabilities.c
Line: 4934

Issue: If ACVP_KDF135_TLS10_TLS11 method is set (which has no hash_alg parameters) after  ACVP_KDF135_TLS12 is set then it will wipe the SHA hash algorithms previously set by TLS12 as they both share the same context capabilities variable (kdf135_tls_cap->sha).

Below code would fail to properly build the registration json object because ACVP_KDF135_TLS10_TLS11 is assigned after ACVP_KDF135_TLS12 in turn setting the shared sha parameter from ACVP_SHA256 | ACVP_SHA384 | ACVP_SHA512 to 0:
```
rv = acvp_cap_kdf135_tls_set_parm(ctx, ACVP_KDF135_TLS, ACVP_KDF135_TLS12,
                                      ACVP_SHA256 | ACVP_SHA384 | ACVP_SHA512);

rv = acvp_cap_kdf135_tls_set_parm(ctx, ACVP_KDF135_TLS, ACVP_KDF135_TLS10_TLS11,0);
```
Issue code:
```
kdf135_tls_cap->sha = param;
```
Solution code:
```
    if (method == ACVP_KDF135_TLS12) {
      kdf135_tls_cap->sha = param;
    }
```
Since method ACVP_KDF135_TLS10_TLS11 has no parameters there is no need to assign it to kdf135_tls_cap->sha

Or another code solution which might scale better if we eventually get parameter support for TLS10_TLS11 or if there's multiple parameter assignment calls:
```
kdf135_tls_cap->sha |= param;
```

**Comment by zacwdev** [comment]
After further review, I think its best to replace
This code from acvp_capabilities.c line 4927 (a tad above the code report above)
```    /* only support two method types so just use whichever is available */
    if (!kdf135_tls_cap->method[0]) {
        kdf135_tls_cap->method[0] = method;
    } else {
        kdf135_tls_cap->method[1] = method;
    }

    kdf135_tls_cap->sha = param;
```
With
```
    switch (method) {
    case ACVP_KDF135_TLS10_TLS11:
        kdf135_tls_cap->method[0] = ACVP_KDF135_TLS10_TLS11;
        break;
    case ACVP_KDF135_TLS12:
        kdf135_tls_cap->method[1] = ACVP_KDF135_TLS12;
        break;
    default:
        return ACVP_INVALID_ARG;
    }

    kdf135_tls_cap->sha |= param;
```
Which will support multiple assignment calls and not run the issue that if you call the same method assignment twice having it build the JSON code with the same method in both method[0] and method[1] which would fail. This aligns with how KDF135_SSH is constructed in the  acvp_capabilities.c. On top of those changes, updating acvp_build_register.c by replacing the below code:

```
    if (cap_entry->cap.kdf135_tls_cap->method[0] == ACVP_KDF135_TLS10_TLS11) {
        json_array_append_string(temp_arr, "v1.0/1.1");
    } else if (cap_entry->cap.kdf135_tls_cap->method[0] == ACVP_KDF135_TLS12) {
        json_array_append_string(temp_arr, "v1.2");
    }

    if (cap_entry->cap.kdf135_tls_cap->method[1] == ACVP_KDF135_TLS10_TLS11) {
        json_array_append_string(temp_arr, "v1.0/1.1");
    } else if (cap_entry->cap.kdf135_tls_cap->method[1] == ACVP_KDF135_TLS12) {
        json_array_append_string(temp_arr, "v1.2");
    }
```
With:
```
    if (cap_entry->cap.kdf135_tls_cap->method[0] == ACVP_KDF135_TLS10_TLS11) {
        json_array_append_string(temp_arr, "v1.0/1.1");
    }
    if (cap_entry->cap.kdf135_tls_cap->method[1] == ACVP_KDF135_TLS12) {
        json_array_append_string(temp_arr, "v1.2");
    }
```

**Comment by abkarcher** [comment]
Thanks for the find! I was looking at that original bit of code and trying to think if there was a better way to organize it for the time being, and your fix seems to fit the bill the bill.  I'll try and get this in tomorrow.

Thanks,
Andrew
