### ISSUE TITLE
Improper E value provided

### ISSUE THREAD

**Issue by NorthHill-16** [cisco/libacvp#438]
Hi, when I want to request for a RSA test vector, I get the following,

***ACVP [STATUS][acvp_login:2320]--> Logging in...
***ACVP [STATUS][acvp_login:2340]--> Login successful
***ACVP [STATUS][acvp_register:1854]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1860]--> Sending registration of capabilities...
***ACVP [ERR][log_network_status:1466]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1467]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "RSA-sigVer-1.0: Improper E value provided"
    ]
  }
]
***ACVP [ERR][acvp_register:1872]--> Failed to send registration
***ACVP [ERR][acvp_run:3007]--> Failed to register with ACVP server

Is libacvp not support RSA yet?

**Comment by abkarcher** [comment]
Hello,

I am unable to reproduce this issue. Have you made any code changes?
Can you provide your ./configure and ./acvp_app arguments?
RSA is supported provided you are using a supporting crypto module, but should still register properly regardless.

Thanks,
Andrew

**Comment by bfussell** [comment]
I'm able to reproduce by putting random strings in the SigVer fixedPubExp registration field. Whatever was changed from our based code is triggering this issue. It is likely a parameter limitation enforced by the NIST server, however I see no definition of that limitation in their specifications for expPubFixed. Maybe it is defined in the old RSAVS CAVS specs.  Regardless, this is something you should take up with NIST via an issue at their github, https://github.com/usnistgov/ACVP

Regards,

Barry

**Comment by NorthHill-16** [comment]
Hi, sorry for late reply since I am not work on the libacvp side recently. Yes, I figure out that it is my configuration error, there is no problem when I use the default configuration. But never mind, I see you guys add a --manual-registration feature recently, which is very helpful.
