### ISSUE TITLE
How to download answer from server when specify as sample request

### ISSUE THREAD

**Issue by NorthHill-16** [cisco/libacvp#442]
Hi, if I request a test vector as sample, I think it shall be available for me to download the correct answer from server. May I know how to do it in libacvp?

**Comment by abkarcher** [comment]
Hello,

As far as I can tell, we currently do not have a way of simply of downloading the expected results for vector sets in samples using the app or library. I will make note of this. 

However, libacvp does automatically get the expected sample results for failed vector sets. So, you could do offline vector set processing using --vector_req and --vector_rsp, and perform the testing. For any failed vector sets, you can get the correct answers from libacvp output. For any successful ones, you can get the output from the file you specified using --vector_rsp.
The flow would be similar to:

./acvp_app --all_algs --sample --vector_req filename1.json
./acvp_app --all_algs --vector_req filename1.json --vector_rsp filename2.json
./acvp_app --sample --vector_upload filename2.json

With filename2 containing the right results for passing vector sets, and libacvp output from --vector_upload containing the right answers for failing ones.

I hope this makes sense. I will make note that we likely want an easier way of just getting a file/output containing all of the expected results.

Thanks,
Andrew

**Comment by NorthHill-16** [comment]
Hi, @abkarcher 

  Some modules like RSA, ECDSA, currently not support to --vector_rsp yet. However, I find out a way to get the expected results for these modules from server.

  ./acvp_app --rsa --vector_req xxx --sample
  ./acvp_app --rsa --vector_upload xxx --sample

  If both request and upload contain --sample, I see the result will print out by server.
