### ISSUE TITLE
ACVP_CURL_BUF_MAX too small for HMAC/SHA testSession/VS request with max keylen (524288)

### ISSUE THREAD

**Issue by zacwdev** [cisco/libacvp#443]
File: include/acvp/acvp_lcl.h
Line: 692
Content: #define ACVP_CURL_BUF_MAX       (1024 * 1024 * 16) /**< 16 MB */
Issue: Below condition at (src/acvp_transport.c:155) becomes true when requesting a testSession with max parameters.
```    
if ((ctx->curl_read_ctr + nmemb) > ACVP_CURL_BUF_MAX) {
        fprintf(stderr, "\nServer response is too large\n");
        return 0;
}
```

Solution:  #define ACVP_CURL_BUF_MAX       (1024 * 1024 * 32) /**< 32 MB */

Doubling it from 16M to 32M allowed the request to work and the vectorsets file that was saved to disk was 30M in size, so 32 seems appropriate. 32M isn't enough to request more than one SHA using max key length, but at least it can handle one. Would increasing this number even higher have any adverse effects? Maybe 64 or 128?

Below is the failed request:

```
***ACVP [STATUS][acvp_login:2340]--> Login successful

***ACVP [STATUS][acvp_register:1854]--> Building registration of capabilities...

***ACVP [STATUS][acvp_register:1860]--> Sending registration of capabilities...

***ACVP [INFO][acvp_register:1861]--> [{"acvVersion":"1.0"},{"algorithms":[{"algorithm":"HMAC-SHA2-256","revision":"1.0","keyLen":[{"min":8,"max":524288,"increment":8}],"macLen":[{"min":32,"max":256,"increment":8}]}]}]

***ACVP [INFO][log_network_status:1442]--> POST Registration...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved


***ACVP [INFO][acvp_parse_test_session_register:2196]--> Received vsid_url=/acvp/v1/testSessions/93524/vectorSets/248823

***ACVP [STATUS][acvp_register:1869]--> Successfully sent registration and received list of vector set URLs

***ACVP [STATUS][acvp_register:1870]--> Test session URL: /acvp/v1/testSessions/93524

***ACVP [STATUS][acvp_run:3016]--> Beginning to download and process vector sets...

***ACVP [INFO][log_network_status:1422]--> GET Vector Set...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/93524/vectorSets/248823
	Resp:
....
      {
            "tcId": 11,
            "key": "93C58AA48A52C3A0",
            "msg": "06F62B
***ACVP [ERR][acvp_process_vsid:2391]--> JSON parse error

***ACVP [ERR][acvp_process_tests:2231]--> Unable to process vector set! Error: 4

***ACVP [ERR][acvp_run:3024]--> Failed to process vectors
```

**Comment by bfussell** [comment]
If you change the registration then buffer size boundaries such as this may also need to be changed.
Our buffer size boundaries are based on the capabilities we tested.
I doubt this would be the last instance of this, particularly since SHA-3 and SHAKE tend to require tons of buffer.

**Comment by zacwdev** [comment]
Thanks for the explanation. I thought the libacvp library was being geared as a general purpose ACVP library for other applications that need to communicate with the NIST ACVP server, and the sample app (openssl module) was just there as an example, and figured you guys were trying to keep it compatible with other scenarios that might arise when being used with other modules, more than just its compatibility with the sample app, but maybe there are too many possibilities to support with this assumption.

**Comment by bfussell** [comment]
Yes, we are happy to keep it compatible with other scenarios that might arise. Feel free to submit a PR with your desired changes.

**Comment by abkarcher** [comment]
Hello,
We have increased the Curl buffer size to 32MB in PR #469. We also added comments to enable_cmac and enable_hmac in acvp_app indicating that the buffer size in the library may need to be increased for large domains. If this becomes a problem down the road we will reevaluate. Please let us know if any more issues around this are experienced.

Thanks,
Andrew
