### ISSUE TITLE
outLen should be read into testcase for HASH SHAKE AFT test vectors

### ISSUE THREAD

**Issue by harrywangca** [cisco/libacvp#449]
test vectors for HASH SHAKE-128 and SHAKE-256 with test type 'AFT' contain "outLen" value for each test case. Though currently outLen are always 128 or 256 respectively for SHAKE-128 and SHAKE-256,  theoretically they can be any length. I guess that's the reason of having outLen for each test case.  So for 'AFT', outLen should be read-in and stored in test case.

**Comment by bfussell** [comment]
I would say that is potentially a bug in the NIST server, it shouldn't send outLen for AFT.   Unfortunately there is no SHAKE example for AFT in the spec. However, there is an example of SHAKE VOT(Variable Output Test) testType and our library properly reads outLen and returns the proper result based on that length.

In addition I think there is a bug in the spec regarding sending outLen with the SHAKE response data, it should not be sent. As part of our design it was intended to minimize the return information for secrecy purposes. Our client does not return that value and the server accepts it and passes the test without it.

Let me know if you have additional questions.

Regards,

Barry

**Comment by bfussell** [comment]
Any further questions ? If not, I'll close the case.

**Comment by harrywangca** [comment]
My point is that SHAKE theoretically can have any outLen, that's why it has VOT tests. outLen item in AFT vectors may serve for this purpose in the future. If you think it's impossible for NIST to give different outLen, this can be closed.

Regards,
Harry
