### ISSUE TITLE
HMAC Key Lengths

### ISSUE THREAD

**Issue by mtdownz** [cisco/libacvp#450]
It seems that ACVP limit the key lengths of the vectors to a maximum of 5. This would be typically broken up into 2 keys for KS < BS, 1 key for KS = BS, and 2 keys for KS > BS.
I have a vendor that uses a wide range of key sizes:
512 and 640 (KS < BS)
1024 (KS = BS)
1152 and 1280 (KS > BS)

Modifying the app_main.c with the following:
rv = acvp_cap_hmac_set_domain(ctx, ACVP_HMAC_SHA2_512, ACVP_HMAC_KEYLEN, 512, 1280, 128);

I receive vectors with 5 key lengths that omit KS = 640 and include KS = 896. Can you advise how I should request vectors in order to get specific values rather than random values in the range i.e. avoiding KS 768 and 896?

Thank you in advance,
Martin

**Comment by bfussell** [comment]
Please review the ACVP spec https://github.com/usnistgov/ACVP
particularly acvp_sub_mac, section 7.1. HMAC Algorithm Capabilities Registration.



keyLen for HMAC contains a Domain of values, the server may choose values defined by these rules:

    2 values below the Hash's block length. See Section 7.2
    The Hash's block length.
    2 values above the Hash's block length.

macLen for HMAC contains a Domain of values, the server may choose values defined by these rules:

    The smallest HMAC length supported
    A second HMAC length supported
    The largest HMAC length supported


I think the server is working as expected.

Regards,

Barry Fussell

**Comment by mtdownz** [comment]
Hello Barry,
Thank you for the clarification. Slightly different behavior to CAVS. So I thought I would double check.
Regards,
Martin

**Comment by bfussell** [comment]
Happy to help !
