### ISSUE TITLE
drbg sample fails on revision 1728

### ISSUE THREAD

**Issue by harrywangca** [cisco/libacvp#453]
In both trunk and tag/v1.0.4,
$ app/acvp_app --verbose --drbg --sample

...

***ACVP [STATUS][acvp_dispatch_vector_set:2511]--> Algorithm: hashDRBG
***ACVP [INFO][acvp_drbg_kat_handler:87]-->     DRBG alg: hashDRBG
***ACVP [INFO][acvp_drbg_kat_handler:129]--> Number of TestGroups: 198
***ACVP [INFO][acvp_drbg_kat_handler:237]-->     Test group:
***ACVP [INFO][acvp_drbg_kat_handler:238]-->     DRBG mode: SHA-1
***ACVP [INFO][acvp_drbg_kat_handler:239]-->     derFunc: false
***ACVP [INFO][acvp_drbg_kat_handler:240]-->     predResistance: true
***ACVP [INFO][acvp_drbg_kat_handler:241]-->     entropyInputLen: 128
***ACVP [INFO][acvp_drbg_kat_handler:243]-->     additionalInputLen: 0
***ACVP [INFO][acvp_drbg_kat_handler:245]-->     persoStringLen: 0
***ACVP [INFO][acvp_drbg_kat_handler:246]-->     nonceLen: 96
***ACVP [INFO][acvp_drbg_kat_handler:247]-->     returnedBitsLen: 160
***ACVP [INFO][acvp_drbg_kat_handler:254]--> Number of Tests: 15
***ACVP [INFO][acvp_drbg_kat_handler:263]--> Found new DRBG test vector...
***ACVP [INFO][acvp_drbg_kat_handler:268]--> json testval count: 0
 {
    "tcId": 1,
    "entropyInput": "202A07C33F10531B16F51599FC0E5922",
    "nonce": "04A73E59815520CE4C7D3324",
    "persoString": "",
    "otherInput": [
        {
            "intendedUse": "generate",
            "additionalInput": "",
            "entropyInput": "4255BFDC893EB59E320503FAC17D392B"
        },
        {
            "intendedUse": "generate",
            "additionalInput": "",
            "entropyInput": "12C535BB84C7F61A3EDFAA6949023D39"
        }
    ]
}

***ACVP [INFO][acvp_drbg_kat_handler:315]-->         Test case: 0
***ACVP [INFO][acvp_drbg_kat_handler:316]-->              tcId: 1
***ACVP [INFO][acvp_drbg_kat_handler:317]-->              entropyInput: 202A07C33F10531B16F51599FC0E5922
***ACVP [INFO][acvp_drbg_kat_handler:318]-->              perso_string:
***ACVP [INFO][acvp_drbg_kat_handler:319]-->              nonce: 04A73E59815520CE4C7D3324
***ACVP [INFO][acvp_drbg_kat_handler:338]--> Found new DRBG Prediction Input...
***ACVP [ERR][acvp_drbg_kat_handler:437]--> crypto module failed the operation
***ACVP [ERR][acvp_process_tests:2246]--> Unable to process vector set! Error: 12
***ACVP [ERR][acvp_run:3032]--> Failed to process vectors

In another test with my own FIPS module (not OPENSSL), I set predResistance to false in ebable_drbg() function, I got a similar failure:

***ACVP [STATUS][acvp_dispatch_vector_set:2510]--> Processing vector set: 274021
***ACVP [STATUS][acvp_dispatch_vector_set:2511]--> Algorithm: hashDRBG
***ACVP [INFO][acvp_drbg_kat_handler:87]-->     DRBG alg: hashDRBG
***ACVP [INFO][acvp_drbg_kat_handler:129]--> Number of TestGroups: 20
***ACVP [INFO][acvp_drbg_kat_handler:237]-->     Test group:
***ACVP [INFO][acvp_drbg_kat_handler:238]-->     DRBG mode: SHA-1
***ACVP [INFO][acvp_drbg_kat_handler:239]-->     derFunc: false
***ACVP [INFO][acvp_drbg_kat_handler:240]-->     predResistance: false
***ACVP [INFO][acvp_drbg_kat_handler:241]-->     entropyInputLen: 128
***ACVP [INFO][acvp_drbg_kat_handler:245]-->     persoStringLen: 0
***ACVP [INFO][acvp_drbg_kat_handler:246]-->     nonceLen: 64
***ACVP [INFO][acvp_drbg_kat_handler:247]-->     returnedBitsLen: 640
***ACVP [INFO][acvp_drbg_kat_handler:254]--> Number of Tests: 15
***ACVP [INFO][acvp_drbg_kat_handler:263]--> Found new DRBG test vector...
***ACVP [INFO][acvp_drbg_kat_handler:268]--> json testval count: 0
 {
    "tcId": 1,
    "entropyInput": "DBC62FA0F988F91FC2D1F0435D54756B",
    "nonce": "468BB5181FC7B195",
    "persoString": "",
    "otherInput": [
        {
            "intendedUse": "reSeed",
            "additionalInput": "",
            "entropyInput": "99689DB522ED4665B58E903F6844D909"
        },
        {
            "intendedUse": "generate",
            "additionalInput": "",
            "entropyInput": ""
        },
        {
            "intendedUse": "generate",
            "additionalInput": "",
            "entropyInput": ""
        }
    ]
}

***ACVP [INFO][acvp_drbg_kat_handler:315]-->         Test case: 0
***ACVP [INFO][acvp_drbg_kat_handler:316]-->              tcId: 1
***ACVP [INFO][acvp_drbg_kat_handler:317]-->              entropyInput: DBC62FA0F988F91FC2D1F0435D54756B
***ACVP [INFO][acvp_drbg_kat_handler:318]-->              perso_string:
***ACVP [INFO][acvp_drbg_kat_handler:319]-->              nonce: 468BB5181FC7B195
***ACVP [INFO][acvp_drbg_kat_handler:338]--> Found new DRBG Prediction Input...
***ACVP [ERR][acvp_drbg_kat_handler:437]--> crypto module failed the operation
***ACVP [ERR][acvp_process_tests:2246]--> Unable to process vector set! Error: 12
***ACVP [ERR][acvp_run:3080]--> Failed to process vectors

**Comment by harrywangca** [comment]
When I look at acvp_drbg_kat_handler() in acvp_drbg.c, it says:

            /*
             * Handle pred_resist_input array. Has at most 2 elements
             */

But for my test case,  which set predResistance to false, pred_resist_input array always have 3 elements:

    "testGroups": [
        {
            "tgId": 1,
            "testType": "AFT",
            "derFunc": false,
            "reSeed": true,
            "predResistance": false,
            "entropyInputLen": 128,
            "nonceLen": 64,
            "persoStringLen": 0,
            "additionalInputLen": 0,
            "returnedBitsLen": 640,
            "mode": "SHA-1",
            "tests": [
                    "tcId": 1,
                    "entropyInput": "7C79AD7B8553B5E2121D36F89FF27736",
                    "nonce": "DFB962EEFE162C4B",
                    "persoString": "",
                    "otherInput": [
                        {
                            "intendedUse": "reSeed",
                            "additionalInput": "",
                            "entropyInput": "5A2AE7B437CE784CCAA9CBE391DC8589"
                        },
                        {
                            "intendedUse": "generate",
                            "additionalInput": "",
                            "entropyInput": ""
                        },
                        {
                            "intendedUse": "generate",
                            "additionalInput": "",
                            "entropyInput": ""
                        }
                    ]

or
                    "tcId": 16,
                    "entropyInput": "B48FAD87CDEA68C97F39249EB80F056D",
                    "nonce": "98F0EAE7DAA5B8C4",
                    "persoString": "",
                    "otherInput": [
                        {
                            "intendedUse": "reSeed",
                            "additionalInput": "5B756D42777C18D90E6803369EAADB19",
                            "entropyInput": "254DA7159061E2C2B4FDD36F7C6FF117"
                        },
                        {
                            "intendedUse": "generate",
                            "additionalInput": "C353247EBB7C68B4421299EB28085C81",
                            "entropyInput": ""
                        },
                        {
                            "intendedUse": "generate",
                            "additionalInput": "5572865657A36088144AE96B8A8667D2",
                            "entropyInput": ""
                        }
                    ]

**Comment by bfussell** [comment]
The base registration works properly with openssl FOM. If you've made changes to the registration you'll need to provide that so we can investigate. If you're not using the openssl FOM, then you may have issues with your crypto module.

Regarding the comment "Has at most 2 elements", that statement is inaccurate we see 3 using the base registration.

**Comment by bfussell** [comment]
Looked a little deeper into this and determined that the current app and library implementation supports only the first Predictions Resistance Assurance Option from section 4.1 of the acvp_sub_drbg specification. You're attempting to use the second option which includes a reseed during testing and currently that is not supported.

Our open source implementation does not support every option available in the ACVP spec.

We will add a task to implement this, however I cannot commit to any timeline as we have many other higher priority tasks in our queue.
You are welcome to implement it yourself and we would welcome a PR if you would like to contribute back to the community.

Regards,

Barry

**Comment by harrywangca** [comment]
Just some clarification:

There are 2 issues:
1. The  drbg sample failure happened to "OpenSSL 1.1.1  11 Sep 2018", without any libacvp source change on revision 1728.
2. With my own module, I need to test "Prediction Resistance Not Enabled" case for drbg, which libacvp doesn't support at the moment. Looks like I will need to do it myself.

Thank you for your replies.
Harry

**Comment by bfussell** [comment]
The sample failure is due to the fact that openssl 1.1.1 has no FOM with HASH DRBG and therefore DRBG testing is disabled in libacvp since ACVP_NO_RUNTIME is not set. We do allow vector download for DRBG when ACVP_NO_RUNTIME is not set, but cannot support --sample because DRBG upload is required by the server in order to get sample results.

**Comment by harrywangca** [comment]
Thank you, Barry.

**Comment by harrywangca** [comment]
I have added the "Prediction Resistance Not Enabled"  support for drbg test. It's verified by running my own module. And I believe it won't break anything.

I don't know if I have the permission to create PR. I just attach the diff file here. Will appreciate it if you can review and merge it.
The diff is generated in trunk against svn revision 1730.

Harry
[diff.txt](https://github.com/cisco/libacvp/files/4968679/diff.txt)

**Comment by bfussell** [comment]
We've added the enhancement, all options from section 4.1 are now supported via PR #455
