### ISSUE TITLE
Missing pubExpMode

### ISSUE THREAD

**Issue by s-c-c** [cisco/libacvp#457]
https://github.com/cisco/libacvp/blob/5ae80820c77a06d146c6ebd2c663f97ff5e2df0d/src/acvp_rsa_keygen.c#L401
Maybe the name here should be pubExpMode

**Comment by bfussell** [comment]
The spec says pubExpMode, but in reality the server sends pubExp so our implementation uses pubExp.
An issue could be opened with NIST.
