### ISSUE TITLE
Any plan about PBKDF and other algorithms not supported?

### ISSUE THREAD

**Issue by s-c-c** [cisco/libacvp#458]

**Comment by abkarcher** [comment]
Hello,

We are balancing the need to add other features or bugfixes with the need for adding more algorithm support to the library - so it is beneficial when people let us know algorithms they need here so we can prioritize accordingly! We have internal stories to track many algorithms that have not yet been implemented.

Thanks,
Andrew

**Comment by s-c-c** [comment]
Can the libacvp library list the features supported by the algorithm in detail?

**Comment by abkarcher** [comment]
Hi,

I'm not entirely sure I understand the question, but README.md contains a list of all of the algorithms we do and do not currently support. 

For the ones we do support, when determining supported features and values, we try to follow the spec as listed here:
https://usnistgov.github.io/ACVP/

Hope this helps,
Andrew

**Comment by bfussell** [comment]
We will create a user story to add more detail to the table in our README.md and identify the options that are not supported.

**Comment by s-c-c** [comment]
oh, thank you very much!

**Comment by s-c-c** [comment]
for pbkdf alg, i can't find any symbol in json to determine whether it is pbkdf1 or pbkdf2. 
is it because in acvp pbkdf means pbkdf2 by default?

**Comment by bfussell** [comment]
I'm confused, are you asking questions about json definitions in the PBKDF spec, draft-celi-acvp-pbkdf.html ?

**Comment by s-c-c** [comment]
yes, in draft-ceil-acvp-pbkdf-00, there is no identifier to identify the alg is pbkdf1 or pbkdf2.

**Comment by bfussell** [comment]
Your question should be asked on the ACVP spec github, https://github.com/usnistgov/ACVP

**Comment by mtdownz** [comment]
Hi Barry and Andrew,
I have implemented the PBKDF but get the following error from the ACVP server. The JSON seems to be formatted okay? I see that it is missing the "capabilities" tag per section 5.3: https://usnistgov.github.io/ACVP/artifacts/draft-celi-acvp-pbkdf.txt
However, the example in the same document below the table does not include this tag. Not sure if this is the issue. Any thoughts would be greatly appreciated.

***ACVP [STATUS][acvp_login:2372]--> Login successful
***ACVP [STATUS][acvp_register:1883]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1891]--> Sending registration of capabilities...
***ACVP [INFO][acvp_register:1892]--> [{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"kdf-components","mode":"pbkdf","revision":"1.0","prereqVals":[{"algorithm":"SHA","valValue":"same"}],"iterationCount":[{"min":10,"max":1000,"increment":1}],"keyLen":[{"min":112,"max":1024,"increment":8}],"passwordLen":[{"min":8,"max":128,"increment":1}],"saltLen":[{"min":128,"max":1024,"increment":8}],"hashAlg":["SHA2-256"]}]}]
***ACVP [INFO][log_network_status:1467]--> POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

***ACVP [ERR][log_network_status:1491]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map kdf-components-pbkdf-1.0 - index 0 to an internal algorithm id."
    ]
  }
]
***ACVP [ERR][acvp_register:1903]--> Failed to send registration
***ACVP [ERR][acvp_run:3078]--> Failed to register with ACVP server

**Comment by bfussell** [comment]
I think you're hitting a documentation error described here:
 
https://github.com/usnistgov/ACVP/issues/707

There is a capabilities keyword that is not properly shown in the pbkdf example.
And quite possibly a consistency problem with the definition of the various KDF modes.
Look at the kdf mode ikev2 for a comparison, it uses "capabilities" similar to the way
pbkdf should use it.

Regards,

Barry

**Comment by mtdownz** [comment]
Hi Barry,
Thanks for the guidance. I added the "capabilities" in a similar way to the IKEV2 and that worked well. However, I am getting the same error. I'll post to the ACVP site to see if anyone has been successful in this area? Thanks!

***ACVP [STATUS][acvp_login:2372]--> Login successful
***ACVP [STATUS][acvp_register:1883]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1891]--> Sending registration of capabilities...
***ACVP [INFO][acvp_register:1892]--> [{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"kdf-components","revision":"1.0","mode":"pbkdf","prereqVals":[{"algorithm":"SHA","valValue":"same"}],"capabilities":[{"iterationCount":[{"min":10,"max":1000,"increment":1}],"keyLen":[{"min":112,"max":1024,"increment":8}],"passwordLen":[{"min":8,"max":128,"increment":1}],"saltLen":[{"min":128,"max":1024,"increment":8}],"hashAlg":["SHA2-256"]}]}]}]
***ACVP [INFO][log_network_status:1467]--> POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

***ACVP [ERR][log_network_status:1491]--> 400 error received from server. Message:
***ACVP [ERR][log_network_status:1492]--> [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map kdf-components-pbkdf-1.0 - index 0 to an internal algorithm id."
    ]
  }
]
***ACVP [ERR][acvp_register:1903]--> Failed to send registration
***ACVP [ERR][acvp_run:3078]--> Failed to register with ACVP server

**Comment by abkarcher** [comment]
Hi,

Looking here, https://usnistgov.github.io/ACVP/draft-celi-acvp-pbkdf.html, 
I tried some things and seem to have gotten it to work. PBKDF seems to have its own algorithm name instead of using kdf-compenents with a "mode". in addition, the field at the end should be named hmacAlg, not hashAlg. Heres the string that worked for me -

 [{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"PBKDF","revision":"1.0","prereqVals":[{"algorithm":"SHA","valValue":"same"}],"capabilities":[{"iterationCount":[{"min":10,"max":1000,"increment":1}],"keyLen":[{"min":112,"max":1024,"increment":8}],"passwordLen":[{"min":8,"max":128,"increment":1}],"saltLen":[{"min":128,"max":1024,"increment":8}],"hmacAlg":["SHA2-256"]}]}]}]

**Comment by mtdownz** [comment]
Hi Andrew,
It worked! Thank you so much for looking into to this for me. I'm sure a lot of folks will be having similar issues.
Martin.

**Comment by abkarcher** [comment]
No problem! As a reminder we would happily look at any PRs containing new functionality like the library end code for pbkdf if you have the time. :)

As the questions within the scope of libacvp have all been answered, I'll go ahead and close this for now.

Thanks,
Andrew
