### ISSUE TITLE
Unable to login -- "acvp_curl_http_post:726"

### ISSUE THREAD

**Issue by mongallen** [cisco/libacvp#459]
Hi Sir,

While connecting to the NIST demo server using libacvp acvp_app, I get following error. The session log is listed below.

$ ./app/acvp_app --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  certs/Demo.cer
    ACV_KEY_FILE:   certs/private.key

***ACVP [STATUS][acvp_login:2335]--> Logging in...
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSNAME (32 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSVERSION (64 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_ARCHITECTURE (16 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_PROCESSOR (64 char max.)
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2347]--> Login Send Failed
***ACVP [ERR][acvp_run:3025]--> Failed to login with ACVP server

My env setting is as follows:
$ set | grep ACV
ACV_API_CONTEXT=acvp/
ACV_CA_FILE=certs/mozzila_trust_anchors.pem
ACV_CERT_FILE=certs/my_Demo.cer
ACV_KEY_FILE=certs/private.key
ACV_PORT=443
ACV_SERVER=demo.acvts.nist.gov
ACV_TOTP_SEED="content of .txt file provided by NIST"
ACV_URI_PREFIX=/acvp/v1

Any help is much appreciated so thanks in advance!

**Comment by abkarcher** [comment]
Hello,

Do you get the same error if you use absolute paths to your CA/Cert/Key file locations? 

In addition, login will not be allowed without a valid TOTP seed (but that would give a different error).

Thanks,
Andrew

**Comment by mongallen** [comment]
If I use absolute paths as below, I still get the same error.

$ set | grep ACV
ACV_API_CONTEXT=acvp/
ACV_CA_FILE=/cygdrive/c/ACVPClient/libacvp-master/certs/mozzila_trust_anchors.pem
ACV_CERT_FILE=/cygdrive/c/ACVPClient/libacvp-master/certs/my_Demo.cer
ACV_KEY_FILE=/cygdrive/c/ACVPClient/libacvp-master/certs/private.key
ACV_PORT=443
ACV_SERVER=demo.acvts.nist.gov
ACV_TOTP_SEED="content of .txt file provided by NIST"
ACV_URI_PREFIX=/acvp/v1

***ACVP [STATUS][acvp_login:2335]--> Logging in...
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSNAME (32 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_OSVERSION (64 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_ARCHITECTURE (16 char max.)
***ACVP [WARN][acvp_http_user_agent_check_env_for_var:210]--> Unable to collect info for HTTP user-agent - please define ACV_OE_PROCESSOR (64 char max.)
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2347]--> Login Send Failed
***ACVP [ERR][acvp_run:3025]--> Failed to login with ACVP server

**Comment by abkarcher** [comment]
Hello,

This is an error I am only able to reproduce with an invalid or misplaced cert or key file.

However, we don't build or test on Cygwin (We have native visual studio projects now), and there are many factors in play there with how it is built, etc. Is it possible Cygwin does not have permissions to access the cert/key file, that the cert/key file has become corrupt, or that the cert/key file is not PEM encoded? 

A bad CA file gives a different error, and the rest of your environment looks correct.

Thanks,
Andrew

**Comment by mongallen** [comment]
Hi Andrew,

I setup liacvp in Ubuntu and it is working fine now.
Thank you so much for the help.

Allen
