### ISSUE TITLE
RSA SigVer should allow modulo 1024

### ISSUE THREAD

**Issue by harrywangca** [cisco/libacvp#464]
There is a check in acvp_rsa_sig_kat_handler_internal() to disallow modulo 1024 cases. According to the spec, 1024 should be allowed for sigVer as legacy signature support.

I have tried the 1024 sigVer test cases by modifying acvp_rsa_sig_kat_handler_internal(), the demo server can generate 1024 verctors and verify them.

Harry

**Comment by abkarcher** [comment]
Fixed in PR #467. Thanks for the catch! please feel free to let us know if you experience any other issues around that.
