### ISSUE TITLE
Any plan to support more in acvp_cap_kas_ffc_set_scheme()?

### ISSUE THREAD

**Issue by harrywangca** [cisco/libacvp#474]
Currently libacvp only allows  'dhEphem' for kas_ffc, and its kdf option only allows 'noKdfNoKc'. If registers with 'kdfNoKc', the registration will fail with:

  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "KAS-FFC-Component-1.0: KdfOption are required."
    ]
  }
]
***ACVP [ERR][acvp_register:1947]--> Failed to send registration
***ACVP [ERR][acvp_run:3201]--> Failed to register with ACVP server

Any plan to extend the support to this?

Also acvp_cap_kas_ffc_set_scheme() currently only handles 2 items in ACVP_KAS_FFC_PSET
    unsigned int set;
    ACVP_PARAM_LIST *sha;

Any plan to extend the support to the 3rd item:
    ACVP_KAS_FFC_MAC *mac;

Thanks.
Harry

**Comment by abkarcher** [comment]
Hello,

There are several places in the library where certain features are not supported for algorithms that are - we have internal stories to track improving our documentation on this.
I'll look into the possibility and feasibility of this specific instance when I have some time in the next week or so.

Thanks for the find,
Andrew

**Comment by mtdownz** [comment]
Barry/Andrew, from playing around with the KAS_FFC I noticed that the ACVP documentation appears to support both Full and Partial public key validation as part of the "Function Types":

Excerpt:
   *  fullVal - IUT can perform full public key validation ( [SP800-56a]
      section 5.6.2.3.1 / 5.6.2.3.3)

   *  partialVal - IUT can perform partial public key validation (
      [SP800-56a] section 5.6.2.3.2 / 5.6.2.3.4)

I notice that your code only support the fullVal as defined in ACVP_KAS_FFC_FUNC_FULL which appears to work okay. I added the "partialVal" in the appropriate places in your code but the ACVP server rejected this parameter. Do you know if the ACVP server currently supports the Partial Validation scheme at the moment? Is this why it is not currently in your code?

Thanks!

**Comment by bfussell** [comment]
The server supports everything in the specs as far as I know, unless there is an open feature request.  Our client supports what we had time to implement so far. Cisco does not fund us to to work on the client full time and we've prioritized those features required by our internal customers for their FIPS validations.

The server may be rejecting that because the registration options are different for that compared to what is in our app_main.c registration. I'd recommend comparing what you are generating to what is in the spec if you have not already.

Regards,

Barry

**Comment by mtdownz** [comment]
Sure, I completely understand. I just thought I would pick your brains before hitting up NIST. The JSON code going to the server appears good. 
Thanks.

**Comment by mtdownz** [comment]
Seems like this is an issue with the server:
https://github.com/usnistgov/ACVP/issues/409
ACVP should update their docs to remove the "partialVal" parameter option.

**Comment by mtdownz** [comment]
You guys might want to take a look at the updated spec that ironically is dated today:

https://usnistgov.github.io/ACVP/draft-hammett-acvp-kas-ffc-sp800-56ar3.txt

-- Table 3 removes the "mode" parameter (optional before) which would make ACVP_KAS_FFC_MODE_COMP now invalid (no "component" tag needed). Also, I noticed that ACVP_KAS_FFC_MODE_NOCOMP wasn't supported anyway by the server (returns rv=16: No matching capability found).
-- Table 3 also changed the revision from "1.0" to "Sp800-56Ar3"
-- Table 3 added fields "iutId" and "domainParameterGen" (domain with values)

Ironically, "partialVal" is still present -- maybe the update they have scheduled today @5:00pm on the demo server corrects this point?

**Comment by abkarcher** [comment]
Hello,

We have a story internally to track improving our documentation of what features are and aren't supported; I have completed some work on this but it is a lower priority at this time (digging through the spec and comparing to our codebase is more time consuming than it may sound!)

As this issue has been open for a while and we have this on our radar, I will be closing it for now. 

Thanks,
Andrew
