### ISSUE TITLE
Problem with logging in to the acvp demo server

### ISSUE THREAD

**Issue by IlayGussarsky** [cisco/libacvp#475]
Hi, 
After configuring everything and building the demo app, I've ran the command: `./app/acvp_app --sample --aes` to check that everything works but instead recieved an error:
```
# ./app/acvp_app --sample --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: acvp/v1/
    ACV_CA_FILE:    /home/docker/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/docker/WDC_Ilay_Gussarsky_Demo.cer
    ACV_KEY_FILE:   /home/docker/PRIVATEKEY.key

***ACVP [STATUS][acvp_login:2476]--> Logging in...
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 3 (URL using bad/illegal format or missing URL)

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2488]--> Login Send Failed
***ACVP [ERR][acvp_run:3167]--> Failed to login with ACVP server
```

I've checked and it seems that error code 3 of Curl means that there's a syntax error with the url and specifically the server url but it seems to be exactly what it should be.

Any thoughts?

Thanks!

**Comment by abkarcher** [comment]
Hello,

I believe you need a initial forward slash on the ACV_URI_PREFIX ("/acvp/v1")

You can see the actual URL it is failing to connect to using --info or --verbose.

Hope this helps,
Andrew

**Comment by IlayGussarsky** [comment]
Hi,
Thanks for replying (and so fast)!

I've added the slash (which helped I believe). Now it asks me for the PEM pass phrase, which I enter. Then it throws another error:
```
Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/docker/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/docker/WDC_Ilay_Gussarsky_Demo.cer
    ACV_KEY_FILE:   /home/docker/PRIVATEKEY.key

***ACVP [STATUS][acvp_login:2476]--> Logging in...
Enter PEM pass phrase:
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 35 (SSL connect error)

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2488]--> Login Send Failed
***ACVP [ERR][acvp_run:3167]--> Failed to login with ACVP server
```
This is probably not because of me entering the pass phrase incorrectly because when I entered "abc" or "def" it threw a differeent (but the same between incorrect phrases) error (notice error 58 instead of 35):
```# ./app/acvp_app --sample --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/docker/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/docker/WDC_Ilay_Gussarsky_Demo.cer
    ACV_KEY_FILE:   /home/docker/PRIVATEKEY.key

***ACVP [STATUS][acvp_login:2476]--> Logging in...
Enter PEM pass phrase:
***ACVP [ERR][acvp_curl_http_post:726]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2488]--> Login Send Failed
***ACVP [ERR][acvp_run:3167]--> Failed to login with ACVP server
```

What should I do now?
Thanks

**Comment by bfussell** [comment]
Second failure(58) is bad pass phrase I suspect. The first failure(35) looks like you don't have a path to the server.
Does your environment go through a proxy ? If so, you'll need to figure out what is needed there it's environment
specific. If not, could be a simple issue of network path. Have you checked to make sure you can reach the NIST server ?

There could also be issues with yout TOTP generation if your network time is no accurate or suffering from drift.
There are a few other issues opened on this subject that may be of help.

I just checked and the NIST server is up.

**Comment by bfussell** [comment]
It's more likely your key that is triggering a pass phrase request.  Here is a link showing how to change that.

https://futurestud.io/tutorials/how-to-remove-pem-password-from-ssl-certificate

Please review app/acvp_app --help output for command line options needed to download vectors to file

**Comment by IlayGussarsky** [comment]
This worked perfect, thank you!
