### ISSUE TITLE
Problem with using the FIPS compiled Openssl with VS2017 for acvp_app

### ISSUE THREAD

**Issue by rollingpanda007** [cisco/libacvp#476]
I compiled the fips-2.0.16 from openssl github. I then compiled the openssl1.0.2 against this fips installation. In the acvp_app, I specified the include path for including the fips specific header files such as fips.h etc, I also provided the right path for including the compiled fips library (fipscanister.lib). Furthermore, I also made changes to the additional directories path in the linker options in VS to point to the compiled libraries of openssl namely : libeayfips32.lib and ssleay32.lib. The libacvp solution builds perfectly and generates the the libacvp.lib. But on building the acvp_app, the following errors are obtained in VS2017. 
1>------ Rebuild All started: Project: acvp_app, Configuration: fom_legacy_ssl_no_safec x64 ------
1>app_aes.c
1>app_cli.c
1>app_cmac.c
1>app_des.c
1>app_drbg.c
1>app_dsa.c
1>app_ecdsa.c
1>app_hmac.c
1>app_kas.c
1>app_kdf.c
1>app_main.c
1>app_rsa.c
1>app_sha.c
1>app_utils.c
1>Generating Code...
1>safe_str_stub.c
1>safe_mem_stub.c
1>Generating Code...
1>mem_primitives_lib.h
1>safe_lib.h
1>safe_lib_errno.h
1>safe_mem_lib.h
1>safe_str_lib.h
1>Generating Code...
1>app_aes.obj : error LNK2019: unresolved external symbol EVP_CIPHER_CTX_set_flags referenced in function app_aes_handler
1>app_des.obj : error LNK2001: unresolved external symbol EVP_CIPHER_CTX_set_flags
1>app_aes.obj : error LNK2019: unresolved external symbol EVP_aes_128_wrap referenced in function app_aes_keywrap_handler
1>app_aes.obj : error LNK2019: unresolved external symbol EVP_aes_192_wrap referenced in function app_aes_keywrap_handler
1>app_aes.obj : error LNK2019: unresolved external symbol EVP_aes_256_wrap referenced in function app_aes_keywrap_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipherinit referenced in function app_aes_handler
1>app_des.obj : error LNK2001: unresolved external symbol FIPS_cipherinit
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipher referenced in function app_aes_handler
1>app_des.obj : error LNK2001: unresolved external symbol FIPS_cipher
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_cbc referenced in function app_aes_handler
1>app_cmac.obj : error LNK2001: unresolved external symbol FIPS_evp_aes_128_cbc
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_ccm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_cfb1 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_cfb128 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_cfb8 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_ctr referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_ecb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_gcm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_ofb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_128_xts referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_cbc referenced in function app_aes_handler
1>app_cmac.obj : error LNK2001: unresolved external symbol FIPS_evp_aes_192_cbc
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_ccm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_cfb1 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_cfb128 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_cfb8 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_ctr referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_ecb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_gcm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_192_ofb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_cbc referenced in function app_aes_handler
1>app_cmac.obj : error LNK2001: unresolved external symbol FIPS_evp_aes_256_cbc
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_ccm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_cfb1 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_cfb128 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_cfb8 referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_ctr referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_ecb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_gcm referenced in function app_aes_handler_aead
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_ofb referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_evp_aes_256_xts referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipher_ctx_new referenced in function app_aes_handler
1>app_des.obj : error LNK2001: unresolved external symbol FIPS_cipher_ctx_new
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipher_ctx_init referenced in function app_aes_handler
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipher_ctx_free referenced in function app_aes_cleanup
1>app_des.obj : error LNK2001: unresolved external symbol FIPS_cipher_ctx_free
1>app_aes.obj : error LNK2019: unresolved external symbol FIPS_cipher_ctx_ctrl referenced in function app_aes_handler_aead
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_cbc referenced in function app_cmac_handler
1>app_des.obj : error LNK2001: unresolved external symbol FIPS_evp_des_ede3_cbc
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_cmac_init referenced in function app_cmac_handler
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_cmac_update referenced in function app_cmac_handler
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_cmac_final referenced in function app_cmac_handler
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_cmac_ctx_new referenced in function app_cmac_handler
1>app_cmac.obj : error LNK2019: unresolved external symbol FIPS_cmac_ctx_free referenced in function app_cmac_handler
1>app_des.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_cfb1 referenced in function app_des_handler
1>app_des.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_cfb64 referenced in function app_des_handler
1>app_des.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_cfb8 referenced in function app_des_handler
1>app_des.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_ecb referenced in function app_des_handler
1>app_des.obj : error LNK2019: unresolved external symbol FIPS_evp_des_ede3_ofb referenced in function app_des_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol ERR_get_error referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol ERR_error_string referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_new referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_instantiate referenced in function app_drbg_handler
1>app_main.obj : error LNK2001: unresolved external symbol FIPS_drbg_instantiate
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_reseed referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_generate referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_uninstantiate referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_free referenced in function app_drbg_handler
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_set_callbacks referenced in function app_drbg_handler
1>app_main.obj : error LNK2001: unresolved external symbol FIPS_drbg_set_callbacks
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_get_app_data referenced in function drbg_test_entropy
1>app_drbg.obj : error LNK2019: unresolved external symbol FIPS_drbg_set_app_data referenced in function app_drbg_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol EVP_MD_size referenced in function app_dsa_handler
1>app_kas.obj : error LNK2001: unresolved external symbol EVP_MD_size
1>app_sha.obj : error LNK2019: unresolved external symbol FIPS_evp_sha1 referenced in function app_sha_handler
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha1
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha1
1>app_hmac.obj : error LNK2001: unresolved external symbol FIPS_evp_sha1
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha1
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_sha.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_hmac.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_evp_sha224
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_evp_sha256 referenced in function printf
1>app_sha.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_hmac.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_evp_sha256
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_evp_sha384 referenced in function printf
1>app_sha.obj : error LNK2001: unresolved external symbol FIPS_evp_sha384
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha384
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha384
1>app_hmac.obj : error LNK2001: unresolved external symbol FIPS_evp_sha384
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_evp_sha384
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_evp_sha512 referenced in function app_rsa_keygen_handler
1>app_sha.obj : error LNK2001: unresolved external symbol FIPS_evp_sha512
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha512
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_evp_sha512
1>app_hmac.obj : error LNK2001: unresolved external symbol FIPS_evp_sha512
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_evp_sha512
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_generate_key referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol fips_dsa_builtin_paramgen2 referenced in function app_dsa_handler
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_bn_new
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_bn_new
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_bn_new
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_bn_new
1>app_main.obj : error LNK2001: unresolved external symbol FIPS_bn_new
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_bn_free
1>app_dsa.obj : error LNK2001: unresolved external symbol FIPS_bn_free
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_bn_free
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_bn_free
1>app_main.obj : error LNK2001: unresolved external symbol FIPS_bn_free
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_bn_bin2bn referenced in function app_dsa_handler
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_bn_bin2bn
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_bn_bin2bn
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_bn_bin2bn
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_bn_bn2bin referenced in function app_dsa_handler
1>app_ecdsa.obj : error LNK2001: unresolved external symbol FIPS_bn_bn2bin
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_bn_bn2bin
1>app_rsa.obj : error LNK2001: unresolved external symbol FIPS_bn_bn2bin
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_new referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_free referenced in function app_dsa_cleanup
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_verify referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_sign referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_sig_new referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol FIPS_dsa_sig_free referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol fips_bn_cmp referenced in function app_dsa_handler
1>app_dsa.obj : error LNK2019: unresolved external symbol fips_bn_dup referenced in function app_dsa_handler
1>app_kas.obj : error LNK2001: unresolved external symbol fips_bn_dup
1>app_rsa.obj : error LNK2001: unresolved external symbol fips_bn_dup
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_generate_key referenced in function app_ecdsa_handler
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_generate_key
1>app_ecdsa.obj : error LNK2019: unresolved external symbol fips_bn_ctx_new referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol fips_bn_ctx_new
1>app_ecdsa.obj : error LNK2019: unresolved external symbol fips_bn_ctx_free referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol fips_bn_ctx_free
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_get0_private_key referenced in function app_ecdsa_handler
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_get0_private_key
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_get0_public_key referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_get0_public_key
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_get0_group referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_get0_group
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_group_method_of referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_group_method_of
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_method_get_field_type referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_method_get_field_type
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_point_get_affine_coordinates_gfp referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_point_get_affine_coordinates_gfp
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_point_get_affine_coordinates_gf2m referenced in function ec_get_pubkey
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_point_get_affine_coordinates_gf2m
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_new_by_curve_name referenced in function app_ecdsa_handler
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_free referenced in function app_ecdsa_cleanup
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_free
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ec_key_set_public_key_affine_coordinates referenced in function app_ecdsa_handler
1>app_kas.obj : error LNK2001: unresolved external symbol FIPS_ec_key_set_public_key_affine_coordinates
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ecdsa_sig_new referenced in function app_ecdsa_handler
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ecdsa_sig_free referenced in function app_ecdsa_handler
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ecdsa_sign referenced in function app_ecdsa_handler
1>app_ecdsa.obj : error LNK2019: unresolved external symbol FIPS_ecdsa_verify referenced in function app_ecdsa_handler
1>app_hmac.obj : error LNK2019: unresolved external symbol FIPS_hmac_ctx_cleanup referenced in function app_hmac_handler
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_hmac_ctx_cleanup
1>app_hmac.obj : error LNK2019: unresolved external symbol FIPS_hmac_init_ex referenced in function app_hmac_handler
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_hmac_init_ex
1>app_hmac.obj : error LNK2019: unresolved external symbol FIPS_hmac_update referenced in function app_hmac_handler
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_hmac_update
1>app_hmac.obj : error LNK2019: unresolved external symbol FIPS_hmac_final referenced in function app_hmac_handler
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_hmac_final
1>app_hmac.obj : error LNK2019: unresolved external symbol FIPS_hmac_ctx_init referenced in function app_hmac_handler
1>app_utils.obj : error LNK2001: unresolved external symbol FIPS_hmac_ctx_init
1>app_kas.obj : error LNK2019: unresolved external symbol fips_bn_ctx_get referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_bn_clear_free referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_bn_num_bits referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_point_new referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_point_free referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_key_set_group referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_group_new_by_curve_name referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol fips_ec_group_free referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_group_get_degree referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol fips_ec_point_set_affine_coordinates_gfp referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol fips_ec_point_set_affine_coordinates_gf2m referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_key_new referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_key_set_flags referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ec_key_set_private_key referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_ecdh_compute_key referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_dh_new referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_dh_free referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_dh_generate_key referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_dh_compute_key_padded referenced in function app_kas_ffc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_malloc referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_free referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_digest referenced in function app_kas_ecc_handler
1>app_kas.obj : error LNK2019: unresolved external symbol FIPS_openssl_cleanse referenced in function app_kas_ecc_handler
1>app_main.obj : error LNK2019: unresolved external symbol BN_bn2hex referenced in function enable_rsa
1>app_main.obj : error LNK2019: unresolved external symbol acvp_get_expected_results referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol FIPS_set_error_callbacks referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol FIPS_drbg_init referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol FIPS_get_default_drbg referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol FIPS_drbg_method referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol FIPS_rand_set_method referenced in function main
1>app_main.obj : error LNK2019: unresolved external symbol fips_bn_set_word referenced in function enable_rsa
1>app_rsa.obj : error LNK2001: unresolved external symbol fips_bn_set_word
1>app_rsa.obj : error LNK2019: unresolved external symbol RSA_new referenced in function app_rsa_sig_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol RSA_free referenced in function app_rsa_cleanup
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_new referenced in function app_rsa_keygen_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_free referenced in function app_rsa_keygen_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_sign referenced in function app_rsa_sig_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_verify referenced in function app_rsa_sig_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_x931_generate_key_ex referenced in function app_rsa_keygen_handler
1>app_rsa.obj : error LNK2019: unresolved external symbol FIPS_rsa_size referenced in function app_rsa_sig_handler
1>app_sha.obj : error LNK2019: unresolved external symbol EVP_DigestFinal referenced in function app_sha_handler
1>app_sha.obj : error LNK2019: unresolved external symbol FIPS_digestinit referenced in function app_sha_handler
1>app_sha.obj : error LNK2019: unresolved external symbol FIPS_digestupdate referenced in function app_sha_handler
1>app_sha.obj : error LNK2019: unresolved external symbol FIPS_md_ctx_create referenced in function app_sha_handler
1>app_sha.obj : error LNK2019: unresolved external symbol FIPS_md_ctx_destroy referenced in function app_sha_handler
1>app_utils.obj : error LNK2019: unresolved external symbol FIPS_hmac_ctx_set_flags referenced in function totp
1>C:\OpenSSL-FIPS-VS2010-32\lib\libeayfips32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>C:\openssl-fips-2.0.16\openssl-fips-2.0.16\lib\fipscanister.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>C:\OpenSSL-FIPS-VS2010-32\lib\ssleay32.lib : warning LNK4272: library machine type 'x86' conflicts with target machine type 'x64'
1>C:\Users\venkatachalam\Desktop\CAVP\GitStuff\ms\\build\acvp_app.exe : fatal error LNK1120: 148 unresolved externals
1>Done building project "acvp_app.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by abkarcher** [comment]
Hello,

There seems to be a conflict between the build architecture between your SSL/FOM builds and the libacvp build.
You are building for windows 64 bit, correct? And running out of the 64 bit visual studio command prompt?

Did you build your openSSL using the instructions in INSTALL.W64 within its release? VS2017 is indicating that you are trying to build a 64 bit libacvp with a 32bit FIPS/openSSL library.

Thanks,
Andrew

**Comment by rollingpanda007** [comment]
Hello!
These are the instructions I followed for building FIPS:
![Capture1](https://user-images.githubusercontent.com/69977178/90791340-5c3e0280-e309-11ea-8be3-12ddcdf8c173.PNG)
And these are the steps I followed for building openssl: 
![Capture2](https://user-images.githubusercontent.com/69977178/90791383-695af180-e309-11ea-9b9a-f952f1934b9e.PNG)

**Comment by abkarcher** [comment]
Hello,

Thanks for the info. Did you use a visual studio command prompt to build all of FOM/OpenSSL and libacvp? e.x. "x64 native tools command prompt for vs2017".  Or, you can call the environment setup script located in your visual studio installation folder from a regular command prompt (usually vcvars64.bat). Same outcome either way.

Basically, it cant find those symbols in the build process because in 32 bit on windows the symbols are prefixed with underscores (e.x. _FIPS_Malloc). So it seems that somehow 32 bit  FOM/OpenSSL libraries are being built.

Thanks,
Andrew

**Comment by rollingpanda007** [comment]
Hello! 

Building it using the Native tools command prompt solved it.
 
Thanks !
