### ISSUE TITLE
ACVP App build error Visual Studio 2017

### ISSUE THREAD

**Issue by rollingpanda007** [cisco/libacvp#477]
Hello!
On building the acvp_app, the following error shows up. The libacvp.lib path was correctly added in to acvp_app solution in VS2017.
1>------ Build started: Project: acvp_app, Configuration: fom_legacy_ssl_no_safec x64 ------
1>app_aes.c
1>app_cli.c
1>app_cmac.c
1>app_des.c
1>app_drbg.c
1>app_dsa.c
1>app_ecdsa.c
1>app_hmac.c
1>app_kas.c
1>app_kdf.c
1>app_main.c
1>app_rsa.c
1>app_sha.c
1>app_utils.c
1>Generating Code...
1>safe_str_stub.c
1>safe_mem_stub.c
1>Generating Code...
1>mem_primitives_lib.h
1>safe_lib.h
1>safe_lib_errno.h
1>safe_mem_lib.h
1>safe_str_lib.h
1>Generating Code...
1>app_main.obj : error LNK2019: unresolved external symbol acvp_get_expected_results referenced in function main
1>C:\Users\pohekar\Desktop\demo\libacvp\ms\\build\acvp_app.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "acvp_app.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**However, on commenting out the calls to the acvp_get_expected results, the build successfully passed. **

**Comment by abkarcher** [comment]
Hello,

There was a small issue with that, it is resolved in libacvp_1_1_0-throttle branch. I have not updated master branch yet, will be in the next few days.

Moving forward, the latest changes will usually be in the newest throttle branch before master which will be updated periodically.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Closing as issue is resolved. If unable to pull new code, issue can be resolved by adding "acvp_get_expected_results" to ms/resources/Source.def.

Thanks,
Andrew
