### ISSUE TITLE
Clarifications about the correct use of functions

### ISSUE THREAD

**Issue by IlayGussarsky** [cisco/libacvp#487]
Hi,
I've managed to get the app working. As I am extremely new to working with apps of this nature and specifically with the `libacvp`, I would love if someone could give me some more information about the use of the app other then what is given upon running `./app/acvp_app --help`. 

**Downloading:**
1. How do I download demo vectors (let's say for AES)? Is it using `./app/acvp_app --sample --aes` or is it something else? Also, where will the vectors be after I download them? (printed, saved to file, etc.)
2. When running the actual certification, is vector downloading the same?

**Uploading:**
1. In demo, how can I check if my result were correct? Is it done by using `--get_results` together with the name of the `testSession` file that was created when running `--sample`? Maybe they were given to me initially?
2. Upon actual certification, after downloading and processing the vectors, how do I upload them back to get my certification?

Thanks.

**Comment by abkarcher** [comment]
Hello,

So to clarify, what do you mean when you say "Demo vectors"? There's two possible meanings - you wish to connect to the demo server and perform testing there, or you wish to perform a sample session. The two are not mutually exclusive. The meaning of sample sessions is that they usually have many less tests and you can access expected results for them. You may not need to use a sample session if you are not trying to debug an issue with your crypto implementation and instead are just performing general testing; you simply just connect to the demo server.

NIST maintains two different URLs for testing - one for the Demo server and one for the formal testing/production server. Informal testing should always be done on the demo server.

In most cases, a regular test session is run doing something like `acvp_app --aes`. This performs an online session, meaning that the app downloads the vectors, processes them, and reuploads them all in one go. It will not save the test info anywhere, though if you add `--verbose` it will print much of the test case information to the log. It will automatically check the results at the end of the session, but you can use `get_results` later on to access them again with the created test session file.

If you want to save the vectors, you do `acvp_app --aes --vector_req <save_file_name>`. This will not process the vectors, only download and save them in JSON format to the given file. To process those vectors offline, you would do `acvp_app --aes --vector_req <save_file_name> --vector_rsp <resp_file_name>`. Finally, you would upload those results using `acvp_app --vector_upload <resp_file_name>`. The vector_upload command again will print the results at the end, but you can use get_results at a later point using the given test session file. 

If you do want to do a sample session, just using `--sample` alongside the other arguments is all you need. If it detects any failures at the end of the test session, it will print the expected results. You can get the expected results for a SAMPLE test session at any time (using the latest code) using `acvp_app --get_expected_results <testSession file>`.

Much of this info is in the README.md file, though with much more brief explanation. Hope this helps!

Andrew

**Comment by IlayGussarsky** [comment]
Hi,
Andrew, thanks for the answer! it was extremely helpful. 

However, I would love for a bit more information regarding the actual certification process (not Demo). Is that on the same server, using the same app? If so, which functions do I use? Else, what applications should I download (if any) and generally, how do I set up what I need to do that?

Thanks!

**Comment by abkarcher** [comment]
Hello,

Certifications are done on a different formal/production server with a different URL, using the same app. You would have different credentials (ACV_TOTP_SEED, ACV_CERT_FILE, and ACV_KEY_FILE) for this, and get all of the needed info from NIST.

The commands would be pretty much the same as running a non-sample session. The difference is (command wise) you would:
In an online session, add `--fips_validation <validation_metadata_file>` to the end of your run command, 
eg. `acvp_app --aes --hash --fips_validation val.json`.

In an offline session, add  `--fips_validation <validation_metadata_file>` to the end of your `--vector_upload <resp_filename>` command,
 e.g. `acvp_app --vector_upload resp.json --fips_validation val.json`.

The metadata can be a bit confusing. "Metadata" refers to the information regarding the vendor, module, and operating environment being validated, and has a specific format and requirements as part of the ACVP spec. The system requires you to post Vendor information to the (formal validation) server before requesting validation/certification. There are multiple samples and examples as well as a readme in the "metadata" folder to get started.

An online session downloads the JSON data from the server exactly like an offline session does. The difference is, instead of saving it to a file, it processes them within memory and uploads the results without needing any further commands.

You can test and perform these commands on demo too, if that helps - validation requests are automatically "approved" but are just for testing and no actual certs are given. 

Hope this helps,
Andrew

**Comment by IlayGussarsky** [comment]
Hey Andrew, Thanks for the useful information.

1. In an online session - how does the app know how and where to process the vectors before they are returned?
2. What is your recommendation for testing in Demo: online or offline testing?

**Comment by abkarcher** [comment]
1.) The app has its own functions for processing the vectors with openSSL. These functions perform all of the calls to libcrypto from within the app code. These can be seen in the "app" folder in source code, e.g. app_aes.c, or app_drbg.c.  When the app tells the library it is compatible with a certain algorithm, it provides the library with a pointer to the relevant function for processing the vectors for that algorithm. When the library gets a vector set, it separates them into the individual vectors (test cases) and feeds each test case to the provided function. The function inserts the results into the test case and gives it back to the library, which uploads the results when the set is complete.

 If someone were using a crypto library other than OpenSSL's libcrypto, they would have to create their own implementation in an app for processing those vectors.

2.) Offline testing is mostly used in situations where the device under test does not have access to the internet/the NIST server or is running on very limited hardware with very limited memory.  In my day-to-day, I almost always use online testing and would recommend the same unless you have to test devices that are not on the internet, are debugging an implementation, or want to keep very detailed raw files of the test cases being run.

Hope this makes sense!
Andrew

**Comment by IlayGussarsky** [comment]
Hi,
Some more questions:
1. In the Demo environment (and in the formal), where do I find component testing for RSA? (we'd like to do the specific certification of modulo size 2048 with prerequisites being none).
2.  My understanding is that `acvp_app --aes --vector_req <save_file_name> --vector_rsp <resp_file_name>` (with aes being just for the example) takes the file we saved using `acvp_app --aes --vector_req <save_file_name>` , processes them using OpenSSL as a default), and then saves the results (i.e: the correct values) in the `<save_file_name>` file. Is this correct?

**Comment by bfussell** [comment]
1. The component testing described in CAVS is referred to as primitive testing in ACVP, see the RSA specification here:
https://github.com/usnistgov/ACVP
Registration for signatrePrimitive does not require prerequisites, however decryptionPrimitive does.
Our library and app code does not support RSA primitive testing.

2. Your understanding is incorrect. ...and then saves the results (i.e: the correct values) in the <resp_file_name>, not the <save_file_name>

**Comment by IlayGussarsky** [comment]
Hi,
1. How do I use the app (both demo and in the formal certification) to get vectors for a specific type of an algorithm (e.g: AES-CBC and not all kinds of AES)? 
2. Is it possible to do the formal testing offline (downloading vectors, not online that downloads, processes and uploads the vectors all in one go)? 
3. If we would like to do component certification for components that the app doesn't support, do you have any suggestions as to what we should do?

Thanks for all the help

**Comment by bfussell** [comment]
1. You would have to comment out the other AES types in the code and re-build. We do not have command line options that are that granular.
2. Yes, juse --vector_req, --vector_rsp or --vector_upload command options and it will run offline using vector files.
3. This is opens source, you may modify and enhance what you need. We will consider adding new features, but cannot provide timelines. You may consider a consultant or contractor for this work if your company does not have the proper skill sets. Our team is not staffed to provide timely support for outside feature requests.

**Comment by IlayGussarsky** [comment]
Hi,
1. What is rebuilding, and how do I comment the other types? Will the demo just take the results I do give it and tell me if I'm right?
2. Upon formal testing, if I comment out some types of AES, will the app know to give me a specific certification to the types I did provide the answers to?

Thanks a lot.

**Comment by abkarcher** [comment]
1.) Rebuilding means to re-run "make clean" / "make" / "make install" (if install is applicable). All of the algorithm capabilities tested are defined in the enable_* functions in app_main.c in the "app" folder (e.g. enable_aes, enable_hash, etc). Going into those functions and deleting or commenting out (adding a // to front of line) the functions and their parameters you do not need will stop them from being tested.

2.) If you are performing a certification on a test session, it will only certify the algorithms tested for that test session. So if you modify the algorithms being tested in app_main.c, rebuild, re-run with a new test session, and request a certification, it would be  a certification for the algorithms you requested (as per modifications to app_main.c)

Hope this helps,
Andrew

2,)

**Comment by IlayGussarsky** [comment]
This was incredibly insightful (and worked).
Do you know of a way to remove from SHA the certification of the null (of length 0) input in the app_main.c file? We'd like to certify non-null inputs only.

Thanks again :)

**Comment by bfussell** [comment]
Data lengths are generally defined in the algorithm capabilities using a domain, min/max/increment like this:

    rv = acvp_cap_hash_set_domain(ctx, ACVP_HASH_SHA1, ACVP_HASH_MESSAGE_LEN, 0, 65528, 8);

Just change that 0 to whatever minimum you support.

All capabilties are defined in the ACVP specs here:

https://github.com/usnistgov/ACVP

**Comment by nssathyan** [comment]
Hi,
I am looking to enable only the SHA384 algorithm.  I have changed the enable_hash function to enable the capabilities for SHA384.  I tried running in the offline mode with the vectors downloaded for the hash algorithms.  But I keep getting an error as follows:
***ACVP [STATUS][acvp_run_vectors_from_file:868]--> Beginning offline processing of vector sets...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 369664
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: SHA-1
***ACVP [ERR][acvp_hash_kat_handler:489]--> ACVP server requesting unsupported capability
***ACVP [ERR][acvp_run_vectors_from_file:956]--> KAT dispatch error

Is there something else that I need to change to make sure the execution skips other SHA tests and reaches SHA384!?  Please help

Regards,
Sathya.

**Comment by bfussell** [comment]
It appears you downloaded the vectors before changing the enable_hash function and your vector files have other SHA types in it.

You need to download new files so they only have SHA384 in them,

**Comment by nssathyan** [comment]
> It appears you downloaded the vectors before changing the enable_hash function and your vector files have other SHA types in it.
> 
> You need to download new files so they only have SHA384 in them,

Thank you Barry!  I did as mentioned by you and now I am able to run only the SHA384 tests.

Regards,
Sathya.
