### ISSUE TITLE
RSA operations with modulo 1024

### ISSUE THREAD

**Issue by davyrouillard** [cisco/libacvp#494]
Hi, 
I see in the app_main.c file that "mod 4096 isn't supported by the server just yet" .
Is it really a problem on the server side or in the app source code ? How  can I know  the current limitation of the demo server ?
Thanks you in advance,
Davy

**Comment by bfussell** [comment]
4096 is supported by server, app and libacvp. That comment is out of date.
Capabilities of the demo server are defined in the specs and README here:

https://github.com/usnistgov/ACVP

libacvp capabilites are listed in our README, however we are working to make them more granular so specific option and parameter support is also defined.

**Comment by davyrouillard** [comment]
OK, thank you so much for the help.
