### ISSUE TITLE
***ACVP [ERR][acvp_curl_http_post:690]--> Error setting curl option CURLOPT_CERTINFO, stopping

### ISSUE THREAD

**Issue by Swapnay** [cisco/libacvp#501]
The openssl used:
```
openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017
```

1. I had  installed openssl headers using `yum install openssl-devel.x86_64` and curl headers using `yum install curl-devel`
2. ```
]whereis openssl
openssl: /usr/bin/openssl /usr/lib64/openssl /usr/include/openssl /opt/splunkforwarder/bin/openssl /usr/share/man/man1/openssl.1ssl.gz
```
2.```
whereis curl
curl: /usr/bin/curl /usr/include/curl /usr/share/man/man1/curl.1.gz
```
3.Configure command used.
`./configure --with-ssl-dir=/usr/include/openssl --with-libcurl-dir=/usr/include/curl --prefix=/mi/`

At the end when `./app/acvp_app --verbose --rsa` run, I see the below error and app stops.

```
***ACVP [ERR][acvp_curl_http_post:690]--> Error setting curl option CURLOPT_CERTINFO, stopping
***ACVP [INFO][log_network_status:1464]--> POST Login...
	Status: 0
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

***ACVP [ERR][log_network_status:1489]--> Received no response from server.
***ACVP [STATUS][acvp_login:2520]--> Login Send Failed
***ACVP [ERR][acvp_run:3199]--> Failed to login with ACVP server



```

I see this error crv = curl_easy_setopt(hnd, CURLOPT_CERTINFO, 1L);

**Comment by bfussell** [comment]
What value are you using for ACV_CA_FILE ? Please inlcude all out from your command line invocation.

**Comment by Swapnay** [comment]
Thanks Barry for such a quick response.
```
ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /libacvp/certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  /libacvp/certs/Mobileiron_Swapna_Yeruvala_Demo.cer
    ACV_KEY_FILE:   /libacvp/certs/demo.key

```

**Comment by Swapnay** [comment]
To my understanding CA and certificate validation goes fine, its with setting certificate chain information?

**Comment by abkarcher** [comment]
In the past, we have had odd issues using the nist CA file, which is why we also include the mozilla one. Could you try setting it to the included mozilla_trust_anchors file and see if the issue persists? (I only ever use the Mozilla one locally).

Outside of that, could you also provide what version of libcurl is being used?

Thanks,
Andrew

**Comment by Swapnay** [comment]
`curl -V
curl 7.29.0 (x86_64-redhat-linux-gnu) libcurl/7.29.0 NSS/3.44 zlib/1.2.7 libidn/1.28 libssh2/1.8.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz unix-sockets`

I still see the issue after changing the CA file environment variable.

**Comment by abkarcher** [comment]
Hello,

It seems that that version of curl is a bit old (~7-8 years) and does not support the CERTINFO option. We designed libacvp to be compatible with Curl 7.61.0 or later (this is not currently mentioned in our documentation and I will update it soon). On most platforms I use regularly the package is called "libcurl-devel" not curl-devel, maybe that is a different thing?

Thanks,
Andrew

**Comment by Swapnay** [comment]
Hello,

I still see the issue.
`]curl -V
curl 7.67.0 (x86_64-pc-linux-gnu) libcurl/7.67.0 OpenSSL/1.0.2k-fips zlib/1.2.7
Release-Date: 2019-11-06
Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS HTTPS-proxy IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets`

Now the configure:

`./configure --with-ssl-dir=/usr/include/openssl --with-libcurl-dir=/usr/local/include/curl`

 Curl:
`which curl
/usr/local/bin/curl`

`whereis curl
curl: /usr/bin/curl /usr/local/bin/curl /usr/share/man/man1/curl.1.gz
`
Openssl:
``
whereis openssl
openssl: /usr/bin/openssl /usr/lib64/openssl /usr/include/openssl /opt/splunkforwarder/bin/openssl /usr/share/man/man1/openssl.1ssl.gz`

`openssl version
OpenSSL 1.0.2k-fips  26 Jan 2017`



```

**Comment by Swapnay** [comment]
Please note that curl was built from sources

**Comment by abkarcher** [comment]
Hello,

if you do `ldd acvp_app`, does it show the path to the newly-built new version of curl an older version included with your OS? you may need to set LD_LIBRARY_PATH to avoid linking to a different version of curl automatically if there are multiple versions of curl on your machine.

Thanks,
Andrew

**Comment by Swapnay** [comment]
todo ldd acvp_app do i have to be a particular path?

`$LD_LIBRARY_PATH
/usr/include/openssl:/usr/local/include/curl:/usr/local/staf/lib:`

**Comment by Swapnay** [comment]
Hello Andrew,
I see
`ldd acvp_app
	not a dynamic executable
`

**Comment by abkarcher** [comment]
should be in same directory as acvp_app file (app/acvp_app as per your configure/run line) or you can probably just include path in command (`ldd /path/to/src/app/acvp_app`)

It would be odd if it was not a dynamic executable as you did not include any offline arguments in the `configure` line.  Also, did you rebuild acvp after building the new curl (and point `configure` to the new curl)?

Thanks,
Andrew

**Comment by Swapnay** [comment]
thats correct.I am doing this entirely in new CentOs 7. https://github.com/cisco/libacvp/issues/501#issuecomment-698630235 has all the new details.

thanks,
Swapna

**Comment by abkarcher** [comment]
Hello,

From the source directory, could you do `ldd .libs/acvp_app` to see if it is linking to the correct version of libcurl?
If that doesn't work, the file may also be under `ldd app/.libs/acvp_app`.

Thanks,
Andrew

**Comment by Swapnay** [comment]
Hi Andrew,

Looks like code construct include and lib directory path out of --with-libcurl-dir. changing it to /usr/local/. helped.
Now i see libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007fb889868000). Thanks for helping.
For FIPS Openssl, is there any closed/open tickets i should be looking at for more  context ? 

Thanks,
Swapna

**Comment by abkarcher** [comment]
Hello,

Generally, to test for fips (Specifically, using a FOM/openSSL fom) you would add --with-fom-dir at configure time to point to the FOM. You likely also would need to use --disable-kdf unless you are using a custom module which includes KDF support. 

for formal FIPS validations, you would run a session including the argument `--fips_validation <metadata_file>.json`. There are various examples of metadata in the metadata folder and more info in the readme.

Thanks,
Andrew
