### ISSUE TITLE
ephemeralPublicIut is short for epui

### ISSUE THREAD

**Issue by s-c-c** [cisco/libacvp#504]
https://github.com/cisco/libacvp/blob/ed190aaa224af7893d8e53fd5288def0c7029108/src/acvp_kas_ffc.c#L52

Just like in line 348, epui is used for json_object_get_string(testobj, "ephemeralPublicIut");

**Comment by bfussell** [comment]
Those cases are different test types and one is the input and the other is the output, therefore different names were used to distinguish between the two.
