### ISSUE TITLE
Multiple test sessions certification

### ISSUE THREAD

**Issue by davyrouillard** [cisco/libacvp#508]
Hi,
The following point is more of a question than an issue. 
I would like to validate separately various algorithms of the same off-line IUT (for example AES and HASH algorithms).

Vectors are obtained with the following commands:
```
 acvp_app --aes --vector_req aes_req.json
 acvp_app --hash --vector_req hash_req.json
```

In this case, vectors are generated over multiple test sessions. After computing the answers on the IUT, how must I send back them to the server for validation ? Is it possible to certify each test session separately in the following way:
```
 acvp_app --vector_upload aes_rsp.json --fips_validation val.json
 acvp_app --vector_upload hash_rsp.json --fips_validation val.json
```

Or must all the algorithms be certified in a single test session ?

Thanks.

**Comment by abkarcher** [comment]
Hello,

Short answer: Yes, that should work.

Long answer:
The NIST ACVP server is supposedly able to automatically group test sessions into one certificate if you use the exact same metadata (see https://github.com/usnistgov/ACVP/issues/969).

Libacvp automatically queries the server with the provided metadata file to see if there is a match (and covers the progress of these queries in --verbose mode). So, the first time you run with certain metadata, libacvp will post it to the server when requesting certification. The second time it should find the data posted the first time and use that to request certification.

If, for some reason, the sessions are not grouped in the same cert, NIST should be able to help resolve it (and please let us know so we can look into it on our end, as there have been lots of changes to metadata processing over the last few months).

Thanks,
Andrew

**Comment by davyrouillard** [comment]
Thanks you very much for your answer. This closes a rather worrying point for me. I will keep you informed if something wrong happen :-).
Have a good day.
Davy
