### ISSUE TITLE
How to set kdfOption in KAS_ECC 

### ISSUE THREAD

**Issue by davyrouillard** [cisco/libacvp#512]
Hi,
I'm trying to get a vector set for KAS_ECC with KDF Concatenation like in the  [specification example](https://usnistgov.github.io/ACVP/draft-fussell-acvp-kas-ecc.html#name-example-kas-ecc-capabilitie). I found how to set the  KDF option to the value 'KdfNoKc' using the following call:

`rv = acvp_cap_kas_ecc_set_scheme(ctx, ACVP_KAS_ECC_COMP, ACVP_KAS_ECC_MODE_COMPONENT, ACVP_KAS_ECC_EPHEMERAL_UNIFIED, ACVP_KAS_ECC_KDF, 0, ACVP_KAS_ECC_KDFNOKC);`

 But I do not understand how to set the option "concatenation" for the KDF ?
Thanks,
Davy

**Comment by abkarcher** [comment]
Hello,

Unfortunately this is a feature we do not currently have support for (similar to https://github.com/cisco/libacvp/issues/474). We will try to look into it when we have some time.

Thanks,
Andrew

**Comment by davyrouillard** [comment]
OK, thanks you. Should I left this issue opened or close it?

**Comment by abkarcher** [comment]
I'll take care of it, Thanks!

Andrew
