### ISSUE TITLE
Using libacvp with Crypto libraries other than libcrypto

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#543]
Hi,

While using libacvp for say SHA384, do we still need to use the EVP* functions to make sure the right return values of the "md" (message digest) are sent back to the NIST server!?  Or is it ok we just populate the "md_len" and "md" and send this back!

Please suggest.

Regards,
Sathya.

**Comment by abkarcher** [comment]
Hello,

ACVP is crypto platform agnostic and the EVP functions are not needed if you are using a different crypto library - you simply need to populate the test case fields.

Thanks,
Andrew

**Comment by nssathyan** [comment]
> Hello,
> 
> ACVP is crypto module agnostic and the EVP functions are not needed if you are using a different crypto library - you simply need to populate the test case fields.
> 
> Thanks,
> Andrew

Hi Andrew,

Thank you!

Sathya.
