### ISSUE TITLE
Few queries regarding ACVP_NO_RUNTIME and sample vectors

### ISSUE THREAD

**Issue by yvasavi** [cisco/libacvp#545]
The README file under \libacvp-master\ introduces two building methods for the cases of Runtime and non-Runtime application respectively. Currently, we are using OpenSSL 1.0.2o-fips 27 Mar 2018 as the crypto module running in our testing machine that will be used to talk with ACVP server.  I have few questions

1. Should we build in Runtime or non-runtime mode in the OpenSSL 1.0.2o-fips 27 Mar 2018 . Is there anyway to check if we have FOM already ? 

2. We have sent for the certificate request to NIST server. We are yet to get the certificate to download the vectors. Can we get sample vectors to start testing the client app ?

**Comment by bfussell** [comment]
1. To test the openssl FOM and all the FIPS relative algorithms, you should build in non-runtime mode.

2. That's a good question and one that NIST may be willing to help with.  Right now you have to get the certificate before you can use libacvp to download sample vectors.  Usually they provide the certificate pretty quickly, but it may be worth opening an issue on their github, https://github.com/usnistgov/ACVP, to see if they can provide sample vectors or to expedite your certificate.

**Comment by yvasavi** [comment]
Hi @bfussell 

Thank you for the reply

When i try to build in non-runtime mode, i get this error
mv -f .deps/acvp_app-app_utils.Tpo .deps/acvp_app-app_utils.Po
make[1]: *** No rule to make target `/usr/lib64//lib/fipscanister.o', needed by `acvp_app'.  Stop.
make[1]: Leaving directory `/src/mgmt-rbt_sh/mgmt/appliances/rbt_sh/src/bin/libacvp-1.2.0/app'
make: *** [all-recursive] Error 1

I don't seem to find fipscanister.o. should i still get fipscanister.o even though we have fips enabled openssl. can you please help clarify. if so where do we get it from.

[admin@oak-vsh367 ~]# openssl version
OpenSSL 1.0.2o-fips  27 Mar 2018

We have fips enabled openssl in our system.
$ nm -D libcrypto.so.1.0.2o | grep -i fips_text_*
00000000000ca9d0 T FIPS_text_end
000000000007c800 T FIPS_text_start
$ nm -D libcrypto.so.1.0.2o | grep -i fips_rodata*
00000000001ef2e0 R FIPS_rodata_end
00000000001e4000 R FIPS_rodata_start
$ nm -D libcrypto.so.1.0.2o | Grep -i fips_signature*
-bash: Grep: command not found
$ nm -D libcrypto.so.1.0.2o | grep -i fips_signature*
00000000004a9520 B FIPS_signature
$ nm -D libcrypto.so.1.0.2o | grep -i fips_incore*
000000000007c9f0 T FIPS_incore_fingerprint


Thanks,
Vasavi

**Comment by bfussell** [comment]
fipscanister.o is the openssl FOM, please review the openssl documentation on building their FOM here:
https://www.openssl.org/docs/fips/UserGuide-2.0.pdf

README.FIPS in the FOM code base here:
https://github.com/openssl/openssl/tree/OpenSSL-fips-2_0-stable

**Comment by yvasavi** [comment]
@bfussell  Thank you for your response.

1. we got the fipscanister.o that was used to compile the openssl fips package. Installed in the build and pointed to it by --fom-dir option. can you please correct my understanding here.
     a) we got the error  
vy@pyrite:~$ screen -r
app_kdf.c:14:25: error: openssl/kdf.h: No such file or directory
make[1]: *** [acvp_app-app_kdf.o] Error 1

we have to test only HMAC/DSA/DRBG/AES/TDES/RSA/ECDSA/SHA.  I have added undef OPENSSL_KDF_SUPPORT in couple of files.  Is this ok or required for any of the above protocols.

 b) do we need canister header files ? or fips enabled openssl header files will do ? 

2. while running algorithms like rsa/dsa/ecdsa we see few chatty messages like. can you please let us understand what is going wrong here.
[admin@oak-vsh367 ~]# ./acvp_app --dsa
 
Using the following parameters:
 
    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    mozzila_trust_anchors.pem
    ACV_CERT_FILE:  Riverbed_Ramana_Pillalamarri_Demo.cer
    ACV_KEY_FILE:   riverbed-private1.key
 
***ACVP [STATUS][acvp_login:2497]--> Logging in...
***ACVP [STATUS][acvp_login:2517]--> Login successful
***ACVP [STATUS][acvp_register:1951]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1959]--> Sending registration of capabilities...
***ACVP [STATUS][acvp_register:1968]--> Successfully sent registration and received list of vector set URLs
***ACVP [STATUS][acvp_register:1969]--> Test session URL: /acvp/v1/testSessions/133300
***ACVP [STATUS][acvp_run:3262]--> Beginning to download and process vector sets...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_dispatch_vector_set:2673]--> Processing vector set: 413340
***ACVP [STATUS][acvp_dispatch_vector_set:2674]--> Algorithm: DSA
***ACVP [STATUS][acvp_process_vector_set:2722]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2644]--> Posting vector set responses for vsId 413340...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2443]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_dispatch_vector_set:2673]--> Processing vector set: 413341
***ACVP [STATUS][acvp_dispatch_vector_set:2674]--> Algorithm: DSA
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
ERROR:0A07E071:lib=10,func=126,reason=113:file=dsa_gen.c:line=592
***ACVP [STATUS][acvp_process_vector_set:2722]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2644]--> Posting vector set responses for vsId 413341...
***ACVP [STATUS][acvp_dispatch_vector_set:2673]--> Processing vector set: 413342
***ACVP [STATUS][acvp_dispatch_vector_set:2674]--> Algorithm: DSA
***ACVP [STATUS][acvp_process_vector_set:2722]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2644]--> Posting vector set responses for vsId 413342...
***ACVP [STATUS][acvp_dispatch_vector_set:2673]--> Processing vector set: 413343
***ACVP [STATUS][acvp_dispatch_vector_set:2674]--> Algorithm: DSA
***ACVP [STATUS][acvp_process_vector_set:2722]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2644]--> Posting vector set responses for vsId 413343...
***ACVP [STATUS][acvp_dispatch_vector_set:2673]--> Processing vector set: 413344
***ACVP [STATUS][acvp_dispatch_vector_set:2674]--> Algorithm: DSA
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
***ACVP [STATUS][acvp_process_vector_set:2722]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2644]--> Posting vector set responses for vsId 413344...
***ACVP [STATUS][acvp_run:3281]--> Tests complete, checking results...
***ACVP [STATUS][acvp_get_result_test_session:2892]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2445]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2892]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2445]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2875]--> Passed all vectors in test session!

Thanks in advance,
Vasavi.

**Comment by bfussell** [comment]
app_kdf.c:14:25: error: openssl/kdf.h: No such file or directory
That's a bug, that line should be removed. I'll make a PR for it.

The messages like this:
ERROR:0A071003:lib=10,func=113,reason=3:file=dsa_ossl.c:line=428
are negative test cases, for example where a signature verify fails. Those are supposed to happen.

**Comment by yvasavi** [comment]
Thanks @bfussell 

I see that RSA keygen fails because openssl FOM 2.X does not have support for 186-4 RSA key gen. 

Can you please let me know if acvp client library/client server supports 186-2 RSA key gen. 

Thanks,
Vasavi.

**Comment by bfussell** [comment]
We don't support 186-2 and I see nothing in the ACVP specification that says it supports 186-2.

https://github.com/usnistgov/ACVP/blob/master/src/rsa/sections/05-keygen-capabilities.adoc

You may consider asking NIST on their github, https://github.com/usnistgov/ACVP

**Comment by yvasavi** [comment]
Hi @bfussell 

I am trying to get it working with few sample vectors shared by a testing Vendor. We could connect to demo server and get the tests passed.

I get following error in offline mode

[admin@oak-vsh379 ~]# ./acvp_app --aes --vector_req vectorsets/390988_ACVP-AES-CBC.json --vector_rsp 1.json --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    mozzila_trust_anchors.pem
    ACV_CERT_FILE:  Riverbed_Ramana_Pillalamarri_Demo.cer
    ACV_KEY_FILE:   riverbed-private1.key

***ACVP [STATUS][acvp_run_vectors_from_file:856]--> Beginning offline processing of vector sets...
***ACVP [WARN][acvp_run_vectors_from_file:890]--> Missing session URL, results will not be POSTed to server.

We want to get the json file response. Can you please provide any pointers on what could be going wrong

Thanks,
Vasavi

**Comment by bfussell** [comment]
Vasavi,

Our client implementation requires a specific format when processing vectors from a file. In general that means the first section of the file must include the jwt used, url of the testSession isSample state and a list of the vectorSets all in json format.  The next sections are the list of vectors each beginning with the vsId and algorithm. Looks like the testing vendor is not providing the format that our client expects.  Are they using our client as well ? If not, you would have to modify our code to work for their format or ask them to match our format.  Below is an example of our format.

Regards,
Barry

[ {
    "jwt": "eyjnoJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0c0lkIjoiMTM2NzYyIiwidnNJZCI6Ils0MjY5NDIsNDI2OTQzXSIsInN1YiI6IkU9YmZ1c3NlbGxAY2lzY28uY29tLCBDTj1BQ1ZQX0Npc2NvLCBPVT1TVE8sIE89Q2lzY28sIEw9UlRQLCBTPU5DLCBDPVVTIiwibmJmIjoxNjEwNDY1Mjc3LCJleHAiOjE2MTA0NjcwNzcsImlhdCI6MTYxMDQ2NTI3NywiaXNzIjoiTklTVCBBQ1ZQIERFTU8ifQ.jODM7VZyTEvIybyYvi4jHa6y5Dlgvt4OfbdqOE2BauI",
    "url": "\/acvp\/v1\/testSessions\/136762",
    "isSample": false,
    "vectorSetUrls": [
        "\/acvp\/v1\/testSessions\/136762\/vectorSets\/426942",
        "\/acvp\/v1\/testSessions\/136762\/vectorSets\/426943"
    ]
}, {
    "vsId": 426942,
    "algorithm": "RSA",
    "mode": "sigGen",
    "revision": "FIPS186-4",
    "isSample": false,
    "testGroups": [
 .......

}, {
    "vsId": 426943,
    "algorithm": "RSA",
    "mode": "sigVer",
    "revision": "FIPS186-4",
    "isSample": false,
    "testGroups": [
.....
]

**Comment by abkarcher** [comment]
Hello,

Are there any more questions regarding this issue, or may I close it?

Thanks,
Andrew

**Comment by yvasavi** [comment]
Yeah closing the issue.

Thanks for the help
