### ISSUE TITLE
Capability settings in HMAC SHA algorithms

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#546]
Hi,

I would like to have test vectors only for Mac length 48 bytes for HMAC_SHA2_384 and Mac length 64 bytes for HMAC_SHA2_512.  Please let me know how this setting can be done in the enable_hmac.  

Regards,
Sathya.

**Comment by bfussell** [comment]
Use set_parm instead of set_domain in enable_hmac() in app_main,.c
    rv = acvp_cap_hmac_set_parm(ctx, ACVP_HMAC_SHA2_384, ACVP_HMAC_MACLEN, 48);
    rv = acvp_cap_hmac_set_parm(ctx, ACVP_HMAC_SHA2_512, ACVP_HMAC_MACLEN, 64);

**Comment by nssathyan** [comment]
Hi Barry,

Thank you for the inputs.

Regards,
Sathya.
