### ISSUE TITLE
Plan of supporting DELETE command

### ISSUE THREAD

**Issue by luckywqe** [cisco/libacvp#548]
Hi 

Does libacvp have the plan to support DELETE command describing in the ACVP specification? such as 

12.16.5. Cancel Test Session
DELETE /testSessions/{testSessionId}

12.17.3. Cancel Testing of a Vector Set
DELETE /testSessions/{testSessionId}/vectorSets/{vectorSetId}

Thanks,
Sean

**Comment by bfussell** [comment]
It's not presently on our backlog, but I'll add it. I can't promise the priority will be high.

**Comment by luckywqe** [comment]
Thanks Barry, adding this issue on the backlog is good enough. For me, most normal use cases do not need DELETE command; however, the command is useful while trying to recover unused vector-sets points. Hopefully this command can be supported after high priority issues are done.
