### ISSUE TITLE
set_domain function for AES

### ISSUE THREAD

**Issue by davyrouillard** [cisco/libacvp#550]
Hi,
To set some parameters for AES capabilities ](https://pages.nist.gov/ACVP/draft-celi-acvp-symmetric.html#name-block-cipher-algorithm-capa) (for example payloadLen or aadLen), it would be useful to have a function to set domain values (just like acvp_cap_hash_set_domain, acvp_cap_hmac_set_domain). But I can not find it in the source code. Is there any reason for that (except the lack of time ;-)?
Is it  intended for a  future version ?
Thanks you.
Davy

**Comment by abkarcher** [comment]
Hello,

work is largely done in a branch for it, I anticipate having it integrated into a future version. When it was originally completed the server had not yet supported it.

Thanks,
Andrew

**Comment by davyrouillard** [comment]
That's a good news. I look forward to this version.
Have a good day,
Davy
