### ISSUE TITLE
AES-GCM IV 

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#562]
Hi, 
As per my understanding, the IV for AES GCM tests (when "ivgen" is 8.2.1) is to be generated by the device under test.  Is this correct?  It that is so, while sending the response back to the NIST server, are we also supposed to send the IV that is generated along with the CT!?  

Also, how is the Tag generated in these cases!?

Regards,
Sathya.

**Comment by bfussell** [comment]
For testing to meet 8.2.1, the NIST server generates the IV.
For testing to meet 8.2.2, the unit under test generates and returns the IV.
When using isSample, the NIST server always generates the IV regardless of whether 8.2.1 or 8.2.2 is used.

Tag generation is part of the AES-GCM algorithm specification, see https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf

**Comment by nssathyan** [comment]
> For testing to meet 8.2.1, the NIST server generates the IV.
> For testing to meet 8.2.2, the unit under test generates and returns the IV.
> When using isSample, the NIST server always generates the IV regardless of whether 8.2.1 or 8.2.2 is used.
> 
> Tag generation is part of the AES-GCM algorithm specification, see https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf

Thank you the response!

Sathya.
