### ISSUE TITLE
Additional DomainParameterGroups for KAS-FFC ?

### ISSUE THREAD

**Issue by b0bsmith** [cisco/libacvp#563]
Are there plans to add additional 'domain parameter group' support to KAS-FFC ?
eg:  **MODP=2048**, MODP-3072, MODP-4096, MODP-6144, MODP-8192, 
       **ffdhe2048**, ffdhe3072, ffdhe4096, ffdhe6144, ffdhe8192, 

If I'm reading the code correctly, currently there's support for FB and FC.

**Comment by bfussell** [comment]
Looking into these currently. Hope to have a PR ready later today.

**Comment by abkarcher** [comment]
Hello,

This is available in release 1.3.0.

Thanks,
Andrew
