### ISSUE TITLE
Support for Safe primes Algorithms

### ISSUE THREAD

**Issue by GeoffGats** [cisco/libacvp#564]
Do you have plans for adding safeprimes keygen/keyver support?

**Comment by bfussell** [comment]
We don't have timeline, but it is on the backlog. 
Just added the safe primes to KAS-FFC-SSC so it doesn't look terribly involved to add those.

**Comment by abkarcher** [comment]
Hello,

This is available in release 1.3.0.

Thanks,
Andrew
