### ISSUE TITLE
Query on AES-GCM

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#576]
Hi, 
For the following capability settings on AES-GCM
            "direction": "decrypt",
            "keyLen": 256,
            "ivLen": 96,
            "ivGen": "external",
            "ivGenMode": "8.2.1",
            "payloadLen": 128,
            "aadLen": 128,
            "tagLen": 64,
I extracted offline test vectors and ran them with my device.  For each of the tests in the output vector (file name provided with --vector_rsp), there is an entry "testPassed": true.  I assume this means that the test is a pass.  But when I run the tests with the NIST server (online tests),  all the tests return with "Plain text not matching" error.  Can you please suggest what I might have missed ?  There are cases with only AAD or PT/CT which pass the tests with the NIST server.  It is only this combination of AAD and PT/CT that seems to end up with failures.

Regards,
Sathya.

**Comment by abkarcher** [comment]
Hello,

There are multiple types of tests for AES. AFT tests are where the CT/PT and other info is sent to the server and grades the tests.

There are also VAL tests which have a "testPassed" field. This is not in indication of whether the test case itself passed or failed. Rather, the server sends both the CT and the PT, where sometimes it sends incorrect CT/PT. The client then performs the operation and compares the server provided result with the result it calculated, and sends whether the comparison matched to the server. thats what "testPassed" is - not that your client calculated the correct result, but if it calculated the same result that the server provided.

Hopefully this helps,
Andrew

**Comment by nssathyan** [comment]
> Hello,
> NOTE: I have made multiple edits to this response as I have double checked my answer
> 
> There are only some tests which have a "testPassed" field. This is not in indication of whether the test case itself passed or failed. This is a result of random negative testing from the server where the decrypt operation is expected to fail. (It has different meanings for tests of different algorithms).
> 
> So for some AES algorithms having a "testPassed" true simply means your crypto module performed an operation successfully, not that the test case passed. The server sometimes expects test operations to fail and tests for it (in which case the server would expect testPassed: false)
> 
> Hopefully this helps,
> Andrew

Thanks a lot Andrew!  This information was really helpful.

Regards,
Sathya.
