### ISSUE TITLE
libacvp cant accsee to demo server

### ISSUE THREAD

**Issue by aradhyula** [cisco/libacvp#582]
Error Message: Curl failed with code 58 (Problem with the local SSL certificate)

Any clue on this? libacvp-master code base is based on Feb 19tyh.  

./app/acvp_app --aes --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/acvp.nist.gov.crt
    ACV_CERT_FILE:  XXXXXXXXXXXXXXX_ACVTSDemo.cer
    ACV_KEY_FILE:   XXXXXXdomain.key

***ACVP [INFO][acvp_http_user_agent_handler:1515]--> HTTP User-Agent: libacvp/1.0;Linux;3.10.0-1062.1.1.el7.x86_64;x86_64;Intel(R) Xeon(R) CPU E5-2660 v4 @ 2.00GHz;GCC/9.1.0

***ACVP [STATUS][acvp_login:2521]--> Logging in...
***ACVP [ERR][acvp_curl_http_post:353]--> Curl failed with code 58 (Problem with the local SSL certificate)

***ACVP [INFO][log_network_status:1079]--> POST Login...
        Status: 0
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp: Recieved

***ACVP [ERR][log_network_status:1105]--> Received no response from server.
***ACVP [STATUS][acvp_login:2533]--> Login Send Failed
***ACVP [ERR][acvp_run:3219]--> Failed to login with ACVP server

Information:
OpenSSL and Curl Versions:
OpenSSL 1.0.2m  2 Nov 2017
curl 7.70.0 (x86_64-pc-linux-gnu) libcurl/7.70.0 OpenSSL/1.0.1h zlib/1.2.7

Steps to build ACVP:
make clean
./configure --with-ssl-dir=/tools/cfr/openssl/1.0.2m/include --with-libcurl-dir=/tools/cfr/curl/7.70.0/include/
make
./app/acvp_app --aes --verbose

NIST has provided the totp and certificate files. 

I did go through earlier issue that is reported https://github.com/cisco/libacvp/issues/126

**Comment by abkarcher** [comment]
Hello,

2 things to try -

1. We have hit-or-miss luck with the NIST CA file. have you tried the included Mozilla CA file?
2. is acvp_app linking to the correct versions of curl/ssl at runtime? (`ldd ./app/acvp_app`)

These issues are a bit harder to debug.

Thanks,
Andrew

**Comment by aradhyula** [comment]
Thanks Andre for the response. No luck after using Mozilla CA file. 
1. Same issue even after changing ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
2. LD_LIBRARY_PATH set to correct versions.
 icds3.0:bash-4.2$ echo $LD_LIBRARY_PATH
/tools/cfr/curl/7.70.0/lib/:/tools/cfr/openssl/1.0.2m/lib:/lib:/usr/lib:

 icds3.0:bash-4.2$ ldd ./app/acvp_app
        not a dynamic executable

**Comment by abkarcher** [comment]
Hello,

It is odd that LDD would say it is not a dynamic executable, as you didnt use --enable-static or --enable-offline; but with LD_LIBRARY_PATH set it should be a non-issue. 

Usually this error from Curl indicates that it cannot locate a cert/key file, that the files are invalid, or that the files are incorrectly formatted.  Assuming none of those are true, you may want to reach out to NIST and confirm that your cert and key are valid with them. 

Another thing to try, if it is not done already, is building curl with the same version of SSL that libacvp is linked to (curl config uses --with-ssl=/dir). I cannot imagine why this would be a cause, but that would be the only other case I can think of where this would be related to the libacvp client and not the cert or key. 

Thanks,
Andrew

**Comment by aradhyula** [comment]
Thanks Andrew for your help with quick responses. Now, everything is working. 
Summary:
1. I had issue with key: In our flow, keytool is used to to generate the CSR along with key air. I have extracted the private key and correct key used now..
2. export ACV_CA_FILE=certs/mozzila_trust_anchors.pem (As Andrew suggested)


Any reason for scripts/nist_setup.sh is not using ACV_CA_FILE=certs/mozzila_trust_anchors.pem as default? 
When do we need to use ACV_CA_FILE=certs/acvp.nist.gov.crt?

**Comment by abkarcher** [comment]
Hello,

I believe the CA is not set to mozilla by default as the NIST one seems to work for some (most?) people; I will make note to add some comments to the setup script/readme regarding the CA though. As for when to use which CA for those not using their own files: I would say for anyone for which the NIST CA works, that should be used; otherwise, Mozilla CA is fine.

Andrew

**Comment by aradhyula** [comment]
Thanks Andrew. Closing this issue.
