### ISSUE TITLE
Stuck on "200 OK KAT values not ready, server requests we wait 30 seconds and try again..."

### ISSUE THREAD

**Issue by corkeee** [cisco/libacvp#586]
I run the CMD `.\acvp_app --aes --vector_req .\aes_req.json --sample` on Windows 10 after the acvp_app was built. But the program will always stuck like this,

> Using the following parameters:
    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    .\mozzila_trust_anchors.pem
    ACV_CERT_FILE:  .\xxxx_xxxx_xxxx_demo.cer
    ACV_KEY_FILE:   .\privatekey.key

>***ACVP [STATUS][acvp_login:2521]--> Logging in...
***ACVP [STATUS][acvp_login:2541]--> Login successful
***ACVP [STATUS][acvp_register:1975]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1983]--> Sending registration of capabilities...
***ACVP [STATUS][acvp_register:1992]--> Successfully sent registration and received list of vector set URLs
***ACVP [STATUS][acvp_register:1993]--> Test session URL: /acvp/v1/testSessions/166390
***ACVP [STATUS][acvp_run:3286]--> Beginning to download and process vector sets...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2467]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...

Did this mean the demo server is busy/down? Or there were issues with my compiled executables or environment?

**Comment by abkarcher** [comment]
Hello,

The NIST server has been experiencing heavy load lately and thus this is normal for now.  You can come back to the session later to see if the tests are generated yet running the exact same arguments you used plus "--resume_session testSession_166390.json"

Andrew

**Comment by corkeee** [comment]
> Hello,
> 
> The NIST server has been experiencing heavy load lately and thus this is normal for now. You can come back to the session later to see if the tests are generated yet running the exact same arguments you used plus "--resume_session testSession_166390.json"
> 
> Andrew

**Comment by corkeee** [comment]
> Hello,
> 
> The NIST server has been experiencing heavy load lately and thus this is normal for now. You can come back to the session later to see if the tests are generated yet running the exact same arguments you used plus "--resume_session testSession_166390.json"
> 
> Andrew

Hi, 
Thanks for the reply. Do you know how long should I expect to receive the file? I've run this for the whole afternoon, but still stuck here.

**Comment by abkarcher** [comment]
Hello,

Thats a hard question to answer - when its not busy it usually takes 1-2 minutes, but lately it can take up to 12 hours or more. I would guess being able to download it by tomorrow morning ET easily- but that may be a better question for NIST. There was some recent discussion about it here:

https://github.com/usnistgov/ACVP/issues/1123

The server is as slammed today as I have ever seen it that I can remember.

Thanks,
Andrew

**Comment by corkeee** [comment]
Hi Andrew,

Thanks for the information. 

I got the test vector this morning. Will close this issue.
