### ISSUE TITLE
DRBG with libacvp

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#589]
Hi,

To be able to process DRBG vectors with libacvp, I could understand that the "ACVP_NO_RUNTIME" macro has to be defined in the project!  Is this a right understanding?

Also, once this macro is enabled, it looks for <openssl/fips.h>.  Do we have to then build the openssl code with FIPS compatibility to run the DRBG tests?  Please clarify!

Regards,
Sathya.

**Comment by bfussell** [comment]
That' correct. This libacvp implementation is based on openssl and their FIPS Object Module(FOM).

**Comment by nssathyan** [comment]
> That' correct. This libacvp implementation is based on openssl and their FIPS Object Module(FOM).

Thank you Barry.  I have used "openssl-fips-2.0.8" and "openssl-1.0.1i" and rebuilt the libcrypto and libssl.  I see this error while building libacvp.

app_aes.c:480:46: error: EVP_CIPHER_CTX_FLAG_WRAP_ALLOW undeclared (first use in this function)
         EVP_CIPHER_CTX_set_flags(cipher_ctx, EVP_CIPHER_CTX_FLAG_WRAP_ALLOW);

This is the configure I have done on the libacvp code:
./configure --with-ssl-dir=/usr/local/ssl --with-libcurl-dir=/usr/lib64  CFLAGS='-DACVP_NO_RUNTIME -g' --with-fom-dir=/usr/local/ssl/fips-2.0


Please suggest what I am doing wrong here!

Regards,
Sathya.

**Comment by bfussell** [comment]
That flag exists in openssl 1.0.2, not 1.0.1

**Comment by nssathyan** [comment]
> That flag exists in openssl 1.0.2, not 1.0.1
> If you need to test 1.0.1 just comment out the AES Wrap registration in app_main.c and the app code in app_aes.c

Thanks again Barry.  I have tried different versions of FIPS and OpenSSL and used it to build libacvp.  Unfortunately, I haven't been able to get the libacvp built.  I see this error message when I build libacvp:
/usr/local/ssl/include/openssl/macros.h:150:4: error: #error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"
 #  error "OPENSSL_API_COMPAT expresses an impossible API compatibility level"

The configure option I used for libacvp is :
./configure --with-ssl-dir=/usr/local/ssl  CFLAGS='-DACVP_NO_RUNTIME -DOPENSSL_FIPS=1 -g' --with-fom-dir=/usr/local/ssl/fips-2.0  -with-libcurl-dir=/usr/lib64

Can you please suggest what versions of FIPS and OpenSSL would work with libacvp?

I have used "openssl-fips-2.0.2" and "openssl-1.0.2u" and had the libcrypto and libssl built successfully.  

Regards,
Sathya.

**Comment by bfussell** [comment]
I don't think that error was introduced until openssl 1.1.X, . You're pointing your paths on the command line to /usr/local are you sure you've installed the fom and openssl you built there ? Or is it possible you're using what is in your distro and that is based on openssl 1.1.X. Same with your curl version. It has to match the openssl you're using with libacvp, so it has to be compiled with a 1.0.2 openssl.

Any 1.0.2 version will work, we use them often. I just pulled the latest OpenSSL_1_0_2-stable and OpenSSL-fips-2_0-stable and it built and worked properly. My curl was built with a 1.0.2 openssl as well.

Won't hurt, but these are not needed on the command line: CFLAGS='-DACVP_NO_RUNTIME -DOPENSSL_FIPS=1 -g' they will be generated automatically based on the fact that you have --with-fom-dir

**Comment by nssathyan** [comment]
> I don't think that error was introduced until openssl 1.1.X, . You're pointing your paths on the command line to /usr/local are you sure you've installed the fom and openssl you built there ? Or is it possible you're using what is in your distro and that is based on openssl 1.1.X. Same with your curl version. It has to match the openssl you're using with libacvp, so it has to be compiled with a 1.0.2 openssl.
> 
> Any 1.0.2 version will work, we use them often. I just pulled the latest OpenSSL_1_0_2-stable and OpenSSL-fips-2_0-stable and it built and worked properly. My curl was built with a 1.0.2 openssl as well.
> 
> Won't hurt, but these are not needed on the command line: CFLAGS='-DACVP_NO_RUNTIME -DOPENSSL_FIPS=1 -g' they will be generated automatically based on the fact that you have --with-fom-dir

Many thanks Barry.  I was able to get libacvp built with FOM and run it for DRBG using OpenSSL.  The one change I had to do in addition to what you suggested is this :
./configure --with-ssl-dir=/usr/local/ssl --with-fom-dir=/usr/local/ssl/fips-2.0 --with-libcurl-dir=/usr/local **--disable-kdf**

aes_kdf.c seemed to be giving me those incompatibility errors.

Thanks again.
Sathya.

**Comment by abkarcher** [comment]
Hello,

As your issue seems to have been resolved, I am closing this, but feel free to reopen if you run into more issues with this instance.

Thanks,
Andrew
