### ISSUE TITLE
ACVP-AES-XTS fails if vectorset json file has tweak mode as number

### ISSUE THREAD

**Issue by sumeetaci** [cisco/libacvp#590]
I ran one test file with algorithm ACVP-AES-XTS. Part of the json file:
.... 
   "tgId": 1,
    "testType": "AFT",
    "direction": "encrypt",
    "keyLen": 256,
    "payloadLen": 256,
    "tweakMode": "number",
....

It failed with error as "crypto module failed the operation". In verbose mode, it gave more details:
Unsupported tweak mode 224 2
***ACVP [ERR][acvp_aes_kat_handler:1263]--> ERROR: crypto module failed the operation
***ACVP [ERR][acvp_run_vectors_from_file:968]--> KAT dispatch error

Any idea to solve this issue? Thanks in advance.

**Comment by abkarcher** [comment]
Hello,

Our app handler for AES testing does not currently support that tweak mode. This is not included in our capability registration by default.
I am not sure if OpenSSL supports this; I will look into it. 

Thanks,
Andrew

**Comment by abkarcher** [comment]
This is not supported at this time and thus is not included in our acvp_app registration

Thanks,
Andrew
