### ISSUE TITLE
CTRDRBG (AES-256) runtime issue

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#593]
Hi,

With the capabilities for CTRDRBG as follows, I see a an error message while running the app/app_acvp:

Capabilities:
    // ACVP_CTRDRBG
    **rv = acvp_cap_drbg_enable(ctx, ACVP_CTRDRBG, &app_drbg_handler);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_set_prereq(ctx, ACVP_CTRDRBG,
                                  ACVP_PREREQ_AES, value);
    CHECK_ENABLE_CAP_RV(rv);
    rv = acvp_cap_drbg_set_parm(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                ACVP_DRBG_DER_FUNC_ENABLED, 0);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_parm(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                ACVP_DRBG_PRED_RESIST_ENABLED, 0);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_parm(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                ACVP_DRBG_RESEED_ENABLED, 1);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_parm(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                ACVP_DRBG_RET_BITS_LEN, 256);
    CHECK_ENABLE_CAP_RV(rv);

    //Add length range
    rv = acvp_cap_drbg_set_length(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                  ACVP_DRBG_ENTROPY_LEN, (int)384, (int)0, (int)384);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_length(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                  ACVP_DRBG_NONCE_LEN, (int)0, (int)0, (int)128);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_length(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                  ACVP_DRBG_PERSO_LEN, (int)0, (int)256, (int)256);
    CHECK_ENABLE_CAP_RV(rv);

    rv = acvp_cap_drbg_set_length(ctx, ACVP_CTRDRBG, ACVP_DRBG_AES_256,
                                  ACVP_DRBG_ADD_IN_LEN, (int)0, (int)256, (int)256);
    CHECK_ENABLE_CAP_RV(rv);**

Output while running DRBG tests:

***ACVP [INFO][acvp_drbg_kat_handler:327]-->         Test case: 0
***ACVP [INFO][acvp_drbg_kat_handler:328]-->              tcId: 1
***ACVP [INFO][acvp_drbg_kat_handler:329]-->              entropyInput: 823707AEAABFB3A9D9A0380DB2484BEB238BE1479CE23EEE88B7A8A4FBC0085EFA9A90EEC039FBACEC33E6F412F0715F
***ACVP [INFO][acvp_drbg_kat_handler:330]-->              perso_string:
***ACVP [INFO][acvp_drbg_kat_handler:331]-->              nonce: CAA59703B62467BAB6B8323EAD240979
***ACVP [INFO][acvp_drbg_kat_handler:352]--> Found new DRBG Prediction Input...
entropy data len 0 < min_len: 48
ERROR:2D07406D:lib=45,func=116,reason=109:file=fips_drbg_lib.c:line=284
ERROR: failed to instantiate DRBG ctx
***ACVP [ERR][acvp_drbg_kat_handler:537]--> crypto module failed the operation
***ACVP [ERR][acvp_run_vectors_from_file:956]--> KAT dispatch error

Is there something that I am doing wrong with the capabilities to get this error?

Regards,
Sathya.

**Comment by bfussell** [comment]
FIx has been committed, will be released in libacvp 1.4.0
