### ISSUE TITLE
Test query

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [cisco/libacvp#597]
What is this test directory ?  what is  this runtest binary will test ?  please explain.

**Comment by abkarcher** [comment]
Runtest runs the unit tests for libacvp. This tests much of the codebase of libacvp to ensure it is working as intended. It is unrelated to the actual crypto testing that libacvp was designed for.

Hope this helps,
Andrew

**Comment by Nagarjuna-jantali** [comment]
> Runtest runs the unit tests for libacvp. This tests much of the codebase of libacvp to ensure it is working as intended. It is unrelated to the actual crypto testing that libacvp was designed for.
> 
> Hope this helps,
> Andrew

Thanks Andrew
