### ISSUE TITLE
 runtime and non-runtime testing queries. 

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [cisco/libacvp#598]
Hi,

I  have couple of  questions.

1.   Please explain the difference between runtime and non-runtime testing . can i test all algorithms in both modes ?
2.  I am using openssl-1.0.2l-fips ( Built with openssl-1.0.2l + openssl-2.0.16(FOM)). 
We have options:
  --with-ssl-dir          location of OpenSSL install folder, defaults to
                          /usr/local/ssl
  --with-fom-dir          Path to FOM install directory

     i.  For runtime testing we have only  --with-ssl-dir  option available , if i give openssl-1.0.2l-fips path here  , does app uses openssl-1.0.2l fips  library for testing?  do i need to call FIPS_mode_set(1) in app_main.c to use FOM at runtime?
     ii. For non -runtime testing we have both options available --with-ssl-dir  and --with-fom-dir .  For first option if i give openssl-1.0.2l-fips path and for --with-fom-dir  if i give  FOM install dir .  algorithm testing done on which library ?

Regards,
Nagarjun

**Comment by abkarcher** [comment]
Hello,

Some algorithms (e.g. DSA) are not able to be tested with the APIs available in openSSL. They need access to internal APIs which would not normally be available or allowed when running software. This is where non-runtime comes in. It links directly to the FOM to allow these algorithms to be tested.

If you use runtime mode, it will only let you test functions that are able to be tested without access to the internal APIs (e.g. SHA, AES). You would need to call FIPS_mode_set to use fips crypto - it will use openSSL crypto by default. Regardless, you will not have access to several algorithms.

Using non-runtime mode (configuring using --with-fom-dir), algorithms will be run using the FOM library crypto, and you will be able to test most of the algorithms libacvp supports. (there are still many algorithms that libacvp supports but openssl/openSSL FOM do not support - these do not appear in acvp_app).

Hope this helps,
Andrew

**Comment by Nagarjuna-jantali** [comment]
> Hello,
> 
> Some algorithms (e.g. DSA) are not able to be tested with the APIs available in openSSL. They need access to internal APIs which would not normally be available or allowed when running software. This is where non-runtime comes in. It links directly to the FOM to allow these algorithms to be tested.
> 
> If you use runtime mode, it will only let you test functions that are able to be tested without access to the internal APIs (e.g. SHA, AES). You would need to call FIPS_mode_set to use fips crypto - it will use openSSL crypto by default. Regardless, you will not have access to several algorithms.
> 
> Using non-runtime mode (configuring using --with-fom-dir), algorithms will be run using the FOM library crypto, and you will be able to test most of the algorithms libacvp supports. (there are still many algorithms that libacvp supports but openssl/openSSL FOM do not support - these do not appear in acvp_app).
> 
> Hope this helps,
> Andrew

Can i have list of algorithms can be tested at runtime and non-runtime?
What are internal APIs your are referring to can you give an example ?

**Comment by bfussell** [comment]
The easiest way to locate the non-runtime algorithms is search the app/ and src/ directory for ACVP_NO_RUNTIME.
RSA key generation API requires exposing the random seed as part of the API which should never be done for production runtime code, rsa_generate_key_internal().

**Comment by abkarcher** [comment]
Hello,

As it seems the questions have been answered I will be closing this issue for now; please feel free to reopen if you have any more questions specific to this issue. Thanks!

Andrew
