### ISSUE TITLE
SHA algorithm needs testing

### ISSUE THREAD

**Issue by jfigus** [cisco/libacvp#6]
eb6580e5b407d7cfd8323935685044dc78b3c334 completes the initial code for SHA algorithms.  However, this code is untested.  Is anyone aware of a ACVP server that implements SHA that could be used for testing?

**Comment by bfussell** [comment]
Hope to get Sam back after this week, so he will be looking at the server side starting with SHA.

Barry

**Comment by jfigus** [comment]
I created a sanity job to at least compile & link the v0.3_dev branch.  The results can be monitored here:
https://openssl-sanity.cisco.com:8443/view/libacvp/job/libacvp_v0.3_dev/

**Comment by bfussell** [comment]
SHA implemented in server and tested.
