### ISSUE TITLE
Queries regarding offline testing

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [cisco/libacvp#603]
Hello

Currently for offline testing we configure :

export FIPSLD_CC=gcc     (or whatever compiler is being used)
./configure --with-ssl-dir=<ciscossl install> --with-fom-dir=<fom install> --prefix=<libacvp install> --enable-static --enable-offline

if i configure: without FOM, is giving compilation error

./configure --with-ssl-dir=/home/nagarjun/FIPS/usr/local/ssl  --prefix=/home/nagarjun/offline/v2/libacvp-libacvp_1_4_0-throttle  --enable-static --enable-offline

Making all in safe_c_stub
make[1]: Entering directory '/home/nagarjun/offline/v2/libacvp-libacvp_1_4_0-throttle/safe_c_stub'
Making all in lib
make[2]: Entering directory '/home/nagarjun/offline/v2/libacvp-libacvp_1_4_0-throttle/safe_c_stub/lib'
/bin/bash ../../libtool  --tag=CC   --mode=compile /bin/fipsld -DPACKAGE_NAME=\"libacvp\" -DPACKAGE_TARNAME=\"libacvp\" -DPACKAGE_VERSION=\"1.3.1\" -DPACKAGE_STRING=\"libacvp\ 1.3.1\" -DPACKAGE_BUGREPORT=\"https://github.com/cisco/libacvp/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libacvp\" -DVERSION=\"1.3.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I.    -I../include -fPIC -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,noexecstack -DACVP_OFFLINE -MT ../src/libsafe_lib_la-safe_mem_stub.lo -MD -MP -MF ../src/.deps/libsafe_lib_la-safe_mem_stub.Tpo -c -o ../src/libsafe_lib_la-safe_mem_stub.lo `test -f '../src/safe_mem_stub.c' || echo './'`../src/safe_mem_stub.c
libtool: compile:  /bin/fipsld -DPACKAGE_NAME=\"libacvp\" -DPACKAGE_TARNAME=\"libacvp\" -DPACKAGE_VERSION=\"1.3.1\" "-DPACKAGE_STRING=\"libacvp 1.3.1\"" -DPACKAGE_BUGREPORT=\"https://github.com/cisco/libacvp/issues\" -DPACKAGE_URL=\"\" -DPACKAGE=\"libacvp\" -DVERSION=\"1.3.1\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -I. -I../include -fPIC -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,noexecstack -DACVP_OFFLINE -MT ../src/libsafe_lib_la-safe_mem_stub.lo -MD -MP -MF ../src/.deps/libsafe_lib_la-safe_mem_stub.Tpo -c ../src/safe_mem_stub.c  -fPIC -DPIC -o ../src/.libs/libsafe_lib_la-safe_mem_stub.o
../../libtool: line 970: /bin/fipsld: No such file or directory
Makefile:426: recipe for target '../src/libsafe_lib_la-safe_mem_stub.lo' failed
make[2]: *** [../src/libsafe_lib_la-safe_mem_stub.lo] Error 1
make[2]: Leaving directory '/home/nagarjun/offline/v2/libacvp-libacvp_1_4_0-throttle/safe_c_stub/lib'
Makefile:361: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/nagarjun/offline/v2/libacvp-libacvp_1_4_0-throttle/safe_c_stub'
Makefile:454: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

1.  Here we are giving FOM path, Does only non-runtime testing is supported in offline mode ?
2.  What is the way if i want to test  openssl-1.1.1 in offline mode ?

Regards
Nagarjun

**Comment by abkarcher** [comment]
Currently, only non runtime testing is supported in offline mode. We are not aware of a use case for needing to test just openSSL in offline mode. If there is one, we can make an internal case for it but it would be low priority at this time. 

You could just create a regular build and use it offline with the same steps, as the offline steps still work in a regular build.

Thanks,
Andrew

**Comment by bfussell** [comment]
Since openssl 1.1.1 does not have a FOM, unless you have created one, there are no APIs to test the algorithms that are limited to offline mode.

**Comment by abkarcher** [comment]
Hello,

As it seems the questions have been answered I will be closing this issue for now; please feel free to reopen if you have any more questions specific to this issue. Thanks!

Andrew
