### ISSUE TITLE
PBKDF set with wrong prereq

### ISSUE THREAD

**Issue by joymcg** [cisco/libacvp#605]
https://github.com/cisco/libacvp/blob/2eac4259d4df79028da3b9be6b67e0c3c5f9729e/app/app_main.c#L1500

Hi,
   I found this line have an issue. It sets the wrong prereq, it shoud be ACVP_PREREQ_HMAC or ACVP_PREREQ_DRBG

**Comment by abkarcher** [comment]
Hello,

Thanks for the find! This was resolved in #606.

Thanks,
Andrew
