### ISSUE TITLE
Error connecting to the demo server

### ISSUE THREAD

**Issue by InternetFreedom** [cisco/libacvp#608]
Hello,
I tried connecting to the demo server
./app/acvp_app --aes  --sample --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  certs/XXXXX.cer
    ACV_KEY_FILE:   certs/PRIVATEKEY.key

***ACVP [INFO][acvp_http_user_agent_handler:1515]--> HTTP User-Agent: libacvp/1.0;Linux;4.4.0-17763-Microsoft;x86_64;Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz;GCC/9.3.0

***ACVP [STATUS][acvp_login:2521]--> Logging in...
Failed to decode TOTP seed
Enter PEM pass phrase:
***ACVP [ERR][acvp_curl_http_post:353]--> Curl failed with code 35 (SSL connect error)

***ACVP [INFO][log_network_status:1079]--> POST Login...
        Status: 0
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp: Recieved

***ACVP [ERR][log_network_status:1105]--> Received no response from server.
***ACVP [STATUS][acvp_login:2533]--> Login Send Failed
***ACVP [ERR][acvp_run:3219]--> Failed to login with ACVP server

 I got two errors:
1. Failed to decode TOTP seed
2. Curl failed with code 35 (SSL connect error)

I tried  using the curl command to see if I can connect to the server:
curl -i -v -X POST "https://acvts.nist.gov/acvp/validation/acvp/register" --cacert -H "Content-Type: application/json"  --cert certs/XXXXX.cer --key certs/PRIVATEKEY.key

*   Trying 2600:1f18:268d:1d01:acfb:16e5:57b4:96ac...
*   Trying 52.204.191.193...
* Connected to acvts.nist.gov (52.204.191.193) port 443 (#0)
* ALPN, offering http/1.1
Enter PEM pass phrase:
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* error setting certificate verify locations:
  CAfile: -H
  CApath: none
* Closing connection 0
curl: (77) error setting certificate verify locations:
  CAfile: -H
  CApath: none
*   Trying 23.217.138.110...
* Connected to Content-Type (23.217.138.110) port 80 (#1)
> POST /json HTTP/1.1
> Host: Content-Type
> User-Agent: curl/7.46.0
> Accept: */*
>
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< X-Correlation-Id: aaaaaaaa
X-Correlation-Id: aaaaaaaa
< Date: Fri, 23 Apr 2021 05:04:11 GMT
Date: Fri, 23 Apr 2021 05:04:11 GMT
< Content-Length: 0
Content-Length: 0
< Connection: close
Connection: close

<
* Closing connection 1

How can I fix this? 
Thank you

**Comment by bfussell** [comment]
Have you set the environment variable ACVP_TOTP_SEED with the value provided by NIST ?

**Comment by InternetFreedom** [comment]
Yes, I set the variable  export ACV_TOTP_SEED=certs/XXX_Demo_totp.txt

**Comment by abkarcher** [comment]
Hello,

ACVP_TOTP_SEED should be set to the seed directly as opposed to a file containing the seed.

Thanks,
Andrew

**Comment by InternetFreedom** [comment]
That fixed it. 
Thank you
