### ISSUE TITLE
Support for Two-Factor Authentication and Authorization ?

### ISSUE THREAD

**Issue by nettalpr** [cisco/libacvp#61]
Hi,
does your code support the Two-Factor Authentication and Authorization recently introduced for accessing and working with the NIST Automated Cryptographic Validation Testing Services ?
Thanks Reiner

**Comment by bfussell** [comment]
Not yet, we are working on it but have been busy working on other support issues.
Hopefully we will be able to get back on it next week.

**Comment by bfussell** [comment]
It's there now and uses an environment variable, ACV_TOTP_SEED, to set it.
