### ISSUE TITLE
Question about offline static linked testing

### ISSUE THREAD

**Issue by InternetFreedom** [cisco/libacvp#611]
Hi,

When libacvp client is built on a different system than the target in offline mode with static linking. If the version of FOM on the build system is different from the FOM on the target system , the test will still pass even if the FOM on the target system is corrupt or not implemented properly or even if there is no FOM on the target system because we are actually testing our the FOM from the build system. 
My question is how can we show assurance that our implementation (target system) is done correctly since we are testing a different openssl library than the one found on the target?

Thank you

**Comment by bfussell** [comment]
Static offline mode pulls the FOM into acvp_app, just like the old openssl test harness executables did for CAVS.
