### ISSUE TITLE
Question: Downloading existing vectors from previous session?

### ISSUE THREAD

**Issue by mtdownz** [cisco/libacvp#619]
Do you support the re-downloading of vectors from a previous or existing test session? It doesn't appear that this feature is implemented?

Thanks
Martin

**Comment by abkarcher** [comment]
Hello,

This is doable, though not currently documented. Running

`acvp_app --resume_session testSession_XXXXX.json --vector_req <filename>.json`

It won't process or submit anything, only redownload all the vector sets to a file.

Documentation improvements are WIP.

Thanks,
Andrew

**Comment by mtdownz** [comment]
Andrew thank you very much! Works great! For the clarity of this thread you also need the --<alg name> 

acvp_app --<alg name> --resume_session testSession_XXXXX.json --vector_req <filename>.json
