### ISSUE TITLE
SP800-90B Keyed Conditioning Component Keys

### ISSUE THREAD

**Issue by dj-on-github** [cisco/libacvp#624]
Hardware implementations of the keyed SP8900-90B conditioning components (HMAC, CBC-MAC, CMAC) tend to use fixed keys, since there is no place for the key to come from and the actual security requirement is independence of the key from the input data. E.G. Intel uses AES-CBC-MAC with k = {AES_0(1) || AES_0(2)} as a suitable NUMS value. Fixing this value in the hardware saves a lot of gates through synthesizing out the unused key schedule hardware. So it's what is done.

The format E.G. 7.2.1 in https://pages.nist.gov/ACVP/draft-celi-acvp-conditioning-components.txt) doesn't seem to provide a field for specifying a fixed key value in the algorithm description. So the resulting key as described in 9.2 would likely be impossible to use.

**Comment by bfussell** [comment]
This github is an implementation based on the ACVP specifications, not the source for the specifications. If you have comments about specifications or drafts please direct your comments to the author in question or the github that contains the specifications.

**Comment by dj-on-github** [comment]
Yes. I figured that was probably the case. NIST already knows what I think.
I've made this comment in the CMUF working group and Alan R
acknowledged it.
I expect NIST to make accommodation for fixed keys in an update to the acvp
specs. We shall see how speedy they are.

Thanks,
DJ
