### ISSUE TITLE
segmentation fault on MacOS

### ISSUE THREAD

**Issue by livebe01** [cisco/libacvp#640]
I'm trying to get libacvp / acvp_app to run on MacOS. I've tried to follow the install / configuration instructions in the README closely, but I'm getting a segmentation fault and can't seem to get past it. I perform steps 1 and 2 in the [Running](https://github.com/cisco/libacvp/blob/main/README.md#running) section of the Readme. For step 3 I run `./app/acvp_app --help` and get a seg fault. I didn't notice anything unusual in the ./configure and make steps. If anyone has any pointers, questions, or ideas about what I might try, please let me know! Thanks!

**Comment by abkarcher** [comment]
Hello,
 This was an issue with specifically the help command from the 1.4.0 release and has been fixed in the libacvp_1_4_0-throttle branch. Could you pull the latest from there and see if it resolves your issue? 
 
Thanks and sorry for the inconvenience,
Andrew

**Comment by livebe01** [comment]
Thanks! I'll give that a try!

**Comment by livebe01** [comment]
Much more better, thank you!
