### ISSUE TITLE
ACVP [STATUS][acvp_login:2509]--> Logging in... segmentation fault

### ISSUE THREAD

**Issue by gmarkan** [cisco/libacvp#648]
Hello

I am having issues connecting to the server after compiling the program

export LD_LIBRARY_PATH=/usr/local/acvp/lib:/usr/local/lib:/usr/local/ssl/lib:$LD_LIBRARY_PATH

./scripts/nist_setup.sh
 app/acvp_app --aes --verbose

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/mchp/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/mchp/libacvp/certs/Microchip_Goutham_Markandeya_Demo.cer
    ACV_KEY_FILE:   /home/mchp/libacvp/certs/Private_nopasscode.key

***ACVP [STATUS][acvp_login:2509]--> Logging in...
***ACVP [INFO][acvp_http_user_agent_handler:483]--> HTTP User-Agent: libacvp/1.0;Linux;4.4.0-210-generic;x86_64;Intel(R) Xeon(R) CPU E5-2609 v3 @ 1.90GHz;GCC/5.3.1

Segmentation fault (core dumped)
****************************************************************************************************

I did single-stepping to see where execution is hitting segmentation fault, it failing in
File : acvp_transport.c
Function: acvp_curl_http_post -->calls--> curl_easy_perform(hnd)

As soon as the execution reaches curl_easy_perform, I get a segmentation fault

curl version =curl 7.73.0 (x86_64-pc-linux-gnu) libcurl/7.73.0 OpenSSL/1.0.2g-fips zlib/1.2.8
openssl version = OpenSSL 1.1.1g 21 Apr 2020
libacvp commmit ID= 96326606965

Any suggestions on how to solve this issue? 
Thanks in Advance!!

**Comment by abkarcher** [comment]
Hello,

Could you provide the command you used to configure libacvp for compiling?
I am investigating this. 

An initial note: It looks like libcurl is linked to a different version of OpenSSL than libacvp is. are there multiple versions of libcurl on your system that could be causing conflicts? We generally run all of our builds with libcurl built against the same version of OpenSSL as libacvp. Providing the output of `ldd app/.libs/acvp_app` may provide some insight.

Thanks,
Andrew

**Comment by gmarkan** [comment]
Hello,

Thanks for the quick response, I could be having multiple versions of libcurl, how can I check to make sure curl 7.73.0 is linked correctly to openssl. Here is the output...

 ldd app/.libs/acvp_app
        linux-vdso.so.1 =>  (0x00007fff57df5000)
        libacvp.so.0 => /usr/local/acvp/lib/libacvp.so.0 (0x00007fdf9631b000)
        libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007fdf95e28000)
        libpci.so.3 => /lib/x86_64-linux-gnu/libpci.so.3 (0x00007fdf95c1b000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdf959fe000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdf95634000)
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007fdf953b6000)
        libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007fdf95122000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fdf94f1e000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fdf94d04000)
        libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007fdf94ae9000)
        libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007fdf967a3000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdf965bb000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fdf94881000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fdf9443c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fdf94234000)

ldd src/.libs/libacvp.so
        linux-vdso.so.1 =>  (0x00007fffa15fe000)
        libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f7276314000)
        libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007f7276080000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7275e63000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7275a99000)
        libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7275831000)
        libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f72753ec000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f72751d2000)
        libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007f7274cdf000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f7276832000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f7274adb000)

**Comment by abkarcher** [comment]
Hello,

Consolidating that list to look at the key dependencies here - 
```
ldd app/.libs/acvp_app
libacvp.so.0 => /usr/local/acvp/lib/libacvp.so.0 (0x00007fdf9631b000)
libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007fdf95e28000)
libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007fdf953b6000)
libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007fdf95122000)
libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fdf94881000)
libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fdf9443c000)

ldd src/.libs/libacvp.so
libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f7276314000)
libssl.so.1.1 => /usr/local/lib/libssl.so.1.1 (0x00007f7276080000)
libssl.so.1.0.0 => /lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f7275831000)
libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f72753ec000)
libcrypto.so.1.1 => /usr/local/lib/libcrypto.so.1.1 (0x00007f7274cdf000)
```

It looks like the app and library are both trying to link to two different verisons of OpenSSL (libcrypto/libssl) at the same time, which is likely where the problem is coming from. 

I would build libcurl from source (https://curl.se/download.html)  and use the "--with-ssl=path/to/ssl" configuration option to point to the version of OpenSSL you are trying to test. LD_LIBRARY_PATH should then include both the OpenSSL you are triyng to test as well as the version of libcurl built against it. This should remove the double-linking.
In addition, you could try using murl from the libacvp source; but I would recommend against it unless building libcurl is not an option. I hope this all makes sense and helps.

Thanks,
Andrew

**Comment by gmarkan** [comment]
Thanks for the quick response and help. I'm able to login successfully now.
root@mchp:/home/mchp/libacvp# app/acvp_app --aes

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/mchp/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/mchp/libacvp/certs/Microchip_Goutham_Markandeya_Demo.cer
    ACV_KEY_FILE:   /home/mchp/libacvp/certs/Private_nopasscode.key

***ACVP [STATUS][acvp_login:2509]--> Logging in...
***ACVP [STATUS][acvp_login:2529]--> Login successful
***ACVP [STATUS][acvp_register:1963]--> Building registration of capabilities...
***ACVP [STATUS][acvp_register:1971]--> Sending registration of capabilities...
***ACVP [STATUS][acvp_register:1980]--> Successfully sent registration and received list of vector set URLs
***ACVP [STATUS][acvp_register:1981]--> Test session URL: /acvp/v1/testSessions/195492
***ACVP [STATUS][acvp_run:3267]--> Beginning to download and process vector sets...
***ACVP [STATUS][acvp_retry_handler:2455]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_retry_handler:2455]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670532
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-GCM
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670532...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670533
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-ECB
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670533...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670534
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CBC
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670534...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670535
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CFB1
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670535...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670536
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CFB8
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670536...
***ACVP [STATUS][acvp_retry_handler:2455]--> 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670537
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CFB128
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670537...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670538
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-OFB
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670538...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670539
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CCM
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670539...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670540
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-KW
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670540...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670541
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-XTS
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670541...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670542
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-CTR
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670542...
***ACVP [STATUS][acvp_dispatch_vector_set:2685]--> Processing vector set: 670543
***ACVP [STATUS][acvp_dispatch_vector_set:2686]--> Algorithm: ACVP-AES-GMAC
***ACVP [STATUS][acvp_process_vector_set:2734]--> Successfully processed vector set
***ACVP [STATUS][acvp_process_vsid:2656]--> Posting vector set responses for vsId 670543...
***ACVP [STATUS][acvp_run:3286]--> Tests complete, checking results...
***ACVP [STATUS][acvp_get_result_test_session:2900]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2457]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2900]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2457]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2900]--> TestSession results incomplete...
***ACVP [STATUS][acvp_retry_handler:2457]--> 200 OK results not ready, waiting 30 seconds and trying again...
***ACVP [STATUS][acvp_get_result_test_session:2883]--> Passed all vectors in test session!
