### ISSUE TITLE
No ACVP_NO_RUNTIME option for KAS-KDF

### ISSUE THREAD

**Issue by sdzeng1010** [cisco/libacvp#661]
Is there a specific reason why the following code is not included in "app/app_kas_kdf.c" (as in, say, "app/app_aes.c")?

#ifdef ACVP_NO_RUNTIME
# include "app_fips_lcl.h"
#endif

Without the above, the KAS-KDF test will not call into FOM even in a --with-fom-dir build.

Thank you!

**Comment by abkarcher** [comment]
Hello,

Nope, that was a mix up on my part. Thanks for the find, I'll get it resolved ASAP.

Thanks,
Andrew

**Comment by sdzeng1010** [comment]
Thank you for the quick response.
