### ISSUE TITLE
XTS-AES & CMAC-AES

### ISSUE THREAD

**Issue by mtdownz** [cisco/libacvp#688]
It appears that XTS and CMAC and some other implementations are only designed to support a 'domain' of values for the input message length/payload (e.g. min, max, inc.). Is there are parameter that would allow a single value to be set for the message length (e.g. via acvp_cap_sym_cipher_set_parm)?

Thanks!

**Comment by abkarcher** [comment]
Hello,

I vaguely recall reading somewhere that using domains for those values as defined in the spec would be the only "officially" supported way on the NIST server for the long term. That being said, using acvp_cap_sym_cipher_set_parm should work for setting ACVP_SYM_CIPH_PTLEN/IVLEN/etc as long as you have not called acvp_cap_sym_cipher_set_domain first. Same thing for CMAC, should just be able to swap the domain call with the parm call. If it does not work, please let me know what error(s) you get. Thanks!

Andrew

**Comment by mtdownz** [comment]
That worked perfectly!

Thank you very much for your help!

**Comment by mtdownz** [comment]
Hi Andrew,

Do you have a similar recommendation for CMAC? I'm having the same issue.

Thanks,
Martin

**Comment by abkarcher** [comment]
Hi,

It looks like you can just replace     

`rv = acvp_cap_cmac_set_domain(ctx, ACVP_CMAC_AES, ACVP_CMAC_MSGLEN, 0, 65536, 8);`

with

`rv = acvp_cap_cmac_set_parm(ctx, ACVP_CMAC_AES, ACVP_CMAC_MSGLEN, 256);`

And that should do it. Let me know if you have any issues with that.

Thanks,
Andrew

**Comment by mtdownz** [comment]
That worked.
Thanks Andrew!
