### ISSUE TITLE
Wrong variable 'sch_val' is used to get a JSON object for KAS2 role

### ISSUE THREAD

**Issue by sider-bughunter** [cisco/libacvp#694]
I have noticed that the `sch_val` variable is used to get a JSON object for KAS2 role in [this code block](https://github.com/cisco/libacvp/blob/ac5f8c314f20a183eb10e9a30d847cd31ad1dfa0/src/acvp_build_register.c#L3311-L3315). There is a similar code block for KAS1 just above. The attached image is the difference between them. The `role_val` for KAS2 would be left unchanged and the `KAS2` element would always be set to an initial value. (correct me if I am wrong)

![image](https://user-images.githubusercontent.com/83890001/168030690-4a18c88f-133d-415c-bae9-5fdb5dd7acb1.png)

**Comment by abkarcher** [comment]
Hello,

Yep, you're right! Funnily enough I just resolved this in our [3.0 work. ](https://github.com/cisco/libacvp/pull/693/files#diff-1e1a28095e8d59d57823de6b13dc9e7d9b21d48bd0b213015c35310c219a328aL3373)

I will get a fix submitted to our regular branch shortly. Thanks!

Andrew

**Comment by abkarcher** [comment]
Resolved in #695. Thanks again!

Andrew
