### ISSUE TITLE
LDT support for SHA

### ISSUE THREAD

**Issue by pablodelara** [cisco/libacvp#719]
Hi,

Any plans to support Large Data Test (LDT) for SHA? https://pages.nist.gov/ACVP/draft-celi-acvp-sha.html#name-test-types-and-test-coverag

Thanks!
Pablo

**Comment by bfussell** [comment]
At present there there are no plans, however I will put it on our backlog. Lot's of other tasks with higher priority at this point for our team.

Regards,

Barry

**Comment by pablodelara** [comment]
Thanks @bfussell!
