### ISSUE TITLE
Non-runtime algorithms in offline mode

### ISSUE THREAD

**Issue by ashahhosse** [cisco/libacvp#728]
Hi,

We are testing with 1.1.1g that is “fipsified”, and we are having issues with running some of the algorithms, namely the non-runtime algorithms (e.g. ECDSA, KAS, DRBG) you had mentioned in this comment: https://github.com/cisco/libacvp/issues/340#issuecomment-567916477

For the item noted as Option C in the comment noted above, what kind of modification(s) is/are needed to the src/acvp*.c items in this case to make this work?

**Comment by abkarcher** [comment]
Hello,

You should not need to make any modifications to the src folder to test these algorithms. the src folder contains only the library/parsing side, which is equipped to handle testing these. The library creates a test case structure which is used in the application to get inputs/outputs from the crypto implementation being tested.

Your modifications would need to go into the app/app_<alg>.c files for these, and your registration in app/app_main.c would need to be modified to match your fipsified 1.1.1 capabilities. 

Happy to answer any other questions. 

Hopefully this helps,
Andrew

**Comment by ashahhosse** [comment]
Thanks, Andrew.  

In the case of DRBG for example when you mean modifications, what would need to be merged/changed in app_drbg.c?  Do we need to place our DRBG OpenSSL functionality within this app_drbg.c file or somehow link to the OpenSSL APIs?  We get this error when trying to run the test with the vector:

***ACVP [ERR][acvp_drbg_kat_handler:537]--> crypto module failed the operation
***ACVP [ERR][acvp_run_vectors_from_file:1035]--> KAT dispatch error

**Comment by ashahhosse** [comment]
Sorry, accidentally pressed close on this when submitting.

**Comment by abkarcher** [comment]
So continuing with DRBG as the example here,

DRBG test cases require you setting provided nonces, entropy values, etc. and generating output dependent on those. These types of APIs are not usually available in OpenSSL by default. If you look at the code for running DRBG in OpenSSL 1.0.2  (noteably, end of life)  in app_drbg.c we link the app directly into the FOM object and call internal APIs that are not publicly accessible to run these tests.

You would have to make sure your version of OpenSSL has the APIs needed to set and run tests with these values. This likely would require some development; you also don't really want these APIs easily accessible in a production build for obvious reasons. 

Then, you would need to add code to app_drbg.c that takes the values in the test case structure we provide, feed it into your modified OpenSSL APIs, and then place the output back into the test structure.

Andrew

**Comment by abkarcher** [comment]
Hello!

Closing this, but feel free to reopen if you have any more related questions. Thanks!

Andrew
