### ISSUE TITLE
Unable to deserialize body into two objects

### ISSUE THREAD

**Issue by gmuthukr** [cisco/libacvp#741]
Hi,
I would like to create new test session specifically with some changes in earlier testSession file created by acvp_app.
For eg:
./app/acvp_app --drbg --vector_req req.json --sample

The above command created testSession_XYZ.json file along with req.json test vectors. I believe testSession file was master file describing capabilities for which req.json was created.

I wanted to modify testSession file a bit for my requirements and regenerate test vectors. But even before that, I thought of
verifying manual registration functionality if it works as:

To note, I did not modify yet testSession file at this stage.
./app/acvp_app --drbg --manual_registration testSession_XYZ.json --vector_req req.json

I got an error which mentions
{
  "error": "Invalid JSON provided.",
  "context": [
      "Unable to deserialize body into two objects"
   ]
}

Is there some step wrong I am doing here ? or any pointer for how I can get testvectors created for my testSession file.

**Comment by abkarcher** [comment]
Hello!

libacvp is not currently equipped to use testSession files as manual registration files. You would have to modify a copy of the test session file; the capabilities registration file needs to be formatted exactly like the NIST server expects it. This involves changing the very beginning of the file, and maybe a bracket or two at the end.
```
[
    {"acvVersion": 1.0},
    {
      "algorithms": [{
        "algorithm": "ACVP-AES-GCM",
        "revision": "1.0"
        ....
        ....
      }]
    }
]
```

Hope this helps,
Andrew

**Comment by gmuthukr** [comment]
Thanks Andrew. It worked. Just a minor correction in above suggestion.
1.0 has to be "1.0".
