### ISSUE TITLE
 undefined reference to `FIPS_mode

### ISSUE THREAD

**Issue by chenchudhcs** [cisco/libacvp#760]
Installed dependencies

1. autotools --- version 20220109.1

2.gcc&make ----12.9ubuntu3

3.curl ------  7.81.0-1ubuntu1.7

4.openssl ----- OpenSSL 3.0.2 15 

5.ntp --------  1:4.2.8p15+dfsg-1ubuntu2 

after make command i am seeing this error 

mv -f .deps/acvp_app-app_utils.Tpo .deps/acvp_app-app_utils.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -g -fPIE -I../include -I/usr/include/openssl//include  -I/home/sysint/CAVP/cisco/libacvp/safe_c_stub/include -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,noexecstack -L../src/.libs -lacvp -L/usr/include/openssl//lib -lcrypto    -o acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o
libtool: link: gcc -g -fPIE -I../include -I/usr/include/openssl//include -I/home/sysint/CAVP/cisco/libacvp/safe_c_stub/include -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z -Wl,noexecstack -o .libs/acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o  -L/home/sysint/CAVP/cisco/libacvp/src/.libs /home/sysint/CAVP/cisco/libacvp/src/.libs/libacvp.so -L/usr/include/x86_64-linux-gnu/curl//lib -lcurl -L/usr/include/openssl//lib -lcrypto -Wl,-rpath -Wl,/usr/local/acvp/lib
/usr/bin/ld: acvp_app-app_cli.o: in function `print_version_info':
**/home/sysint/CAVP/cisco/libacvp/app/app_cli.c:194: undefined reference to `FIPS_mode'**
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:557: acvp_app] Error 1
make[1]: Leaving directory '/home/sysint/CAVP/cisco/libacvp/app'

![Capture_1](https://user-images.githubusercontent.com/58893647/214966036-0dabe2dc-1ea9-47ff-97bb-18565b53514a.PNG)

can some one help me out please how to fix this issues.

**Comment by abkarcher** [comment]
Hi,

Which version or branch are you using?

only libacvp_1_TBD_throttle branch works with OpenSSL 3.X; release is not out yet but testing is working.

Thanks,
Andrew

**Comment by chenchudhcs** [comment]
main branch i am using it 

can you help me out which one is working?

**Comment by abkarcher** [comment]
Hi,

"libacvp_1_TBD_throttle" branch works with OpenSSL 3+.

Thanks,
Andrew

**Comment by chenchudhcs** [comment]
mv -f .deps/acvp_app-app_utils.Tpo .deps/acvp_app-app_utils.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -g -fPIE -I../include -I/usr/include/openssl//include  -I/home/sysint/CAVP/git/libacvp/safe_c_stub/include  -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,noexecstack -L../src/.libs -lacvp -L/usr/include/openssl//lib -lcrypto    -o acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_kmac.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o
libtool: link: gcc -g -fPIE -I../include -I/usr/include/openssl//include -I/home/sysint/CAVP/git/libacvp/safe_c_stub/include -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z -Wl,noexecstack -o .libs/acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_kmac.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o  -L/home/sysint/CAVP/git/libacvp/src/.libs /home/sysint/CAVP/git/libacvp/src/.libs/libacvp.so -L/usr/include/x86_64-linux-gnu/curl//lib -lcurl -L/usr/include/openssl//lib -lcrypto -Wl,-rpath -Wl,/usr/local/acvp/lib
make[1]: Leaving directory '/home/sysint/CAVP/git/libacvp/app'
make[1]: Entering directory '/home/sysint/CAVP/git/libacvp'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/home/sysint/CAVP/git/libacvp'

**Comment by chenchudhcs** [comment]
after using libacvp_1_TBD_throttle" branch

its showing failure error

Crypto module returned failure code when running quick digest.
Error occured when testing FIPS at startup (rv = 10). Please verify the FIPS provider is
properly installed and configured. Exiting...

**Comment by abkarcher** [comment]
Hi,

This means that there is an issue with the configuration of OpenSSL and the FIPS provider causing crypto to fail. Please make sure your openssl.cfg file is set up to include and activate the FIPS provider section.

If you don't want to test FIPS, you can use the "--disable-fips" argument at run time and it should run algorithms regularly, but you _must not_ validate using this.

Thanks,
Andrew

**Comment by chenchudhcs** [comment]
# For FIPS
# Optionally include a file that is generated by the OpenSSL fipsinstall
# application. This file contains configuration data required by the OpenSSL
# fips provider. It contains a named section e.g. [fips_sect] which is
# referenced from the [provider_sect] below.
# Refer to the OpenSSL security policy for more information.
# .include fipsmodule.cnf

[openssl_init]
providers = provider_sect
ssl_conf = ssl_sect

# List of providers to load
[provider_sect]
default = default_sect
# The fips section name should match the section name inside the
# included fipsmodule.cnf.
# fips = fips_sect

# If no providers are activated explicitly, the default one is activated implicitly.
# See man 7 OSSL_PROVIDER-default for more details.
#
# If you add a section explicitly activating any other provider(s), you most
# probably need to explicitly activate the default provider, otherwise it
# becomes unavailable in openssl.  As a consequence applications depending on
# OpenSSL may not work correctly which could lead to significant system
# problems including inability to remotely access the system.
[default_sect]
# activate = 1

**Comment by chenchudhcs** [comment]
# For FIPS in openssl.cfg file

can you help me out how to fix this 


**Crypto module returned failure code when running quick digest.
Error occured when testing FIPS at startup (rv = 10). Please verify the FIPS provider is
properly installed and configured. Exiting...** 

![image](https://user-images.githubusercontent.com/58893647/215920939-8ceedbae-aa49-4a3d-8030-c6f81c0971d9.png)

**Comment by abkarcher** [comment]
Hello,

For information about how to configure and enable the default and FIPS providers, please review the OpenSSL documentation.
https://www.openssl.org/docs/man3.0/man7/fips_module.html
libacvp expects the FIPS provider (and the default provider if using online builds) to be activated by default via the configuration.

For more questions about how to configure OpenSSL, it may be best to reach out to their community. It is not prudent for us to assist with general OpenSSL configuration at this time, as people's requirements vary from case to case and the best practices from the OpenSSL side will change over time. (worth noting that libacvp support for 3.0 is not quite officially released yet!)

Thanks,
Andrew

**Comment by chenchudhcs** [comment]
Hello 
i am using libacvp_1_TBD_throttle" branch 

OpenSSL 3.0.2

after make command i am seeing this error

mv -f .deps/acvp_app-app_utils.Tpo .deps/acvp_app-app_utils.Po
/bin/bash ../libtool --tag=CC --mode=link gcc -g -fPIE -I../include -I/usr/include/openssl//include -I/home/sysint/CAVP/cisco/libacvp/safe_c_stub/include -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z,noexecstack -L../src/.libs -lacvp -L/usr/include/openssl//lib -lcrypto -o acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o
libtool: link: gcc -g -fPIE -I../include -I/usr/include/openssl//include -I/home/sysint/CAVP/cisco/libacvp/safe_c_stub/include -g -O2 -Wall -fstack-protector-all -D_FORTIFY_SOURCE=2 -Wl,-z -Wl,noexecstack -o .libs/acvp_app acvp_app-app_main.o acvp_app-app_aes.o acvp_app-app_cli.o acvp_app-app_cmac.o acvp_app-app_des.o acvp_app-app_drbg.o acvp_app-app_dsa.o acvp_app-app_ecdsa.o acvp_app-app_hmac.o acvp_app-app_kas.o acvp_app-app_kdf.o acvp_app-app_kda.o acvp_app-app_rsa.o acvp_app-app_sha.o acvp_app-app_utils.o -L/home/sysint/CAVP/cisco/libacvp/src/.libs /home/sysint/CAVP/cisco/libacvp/src/.libs/libacvp.so -L/usr/include/x86_64-linux-gnu/curl//lib -lcurl -L/usr/include/openssl//lib -lcrypto -Wl,-rpath -Wl,/usr/local/acvp/lib
/usr/bin/ld: acvp_app-app_cli.o: in function print_version_info': **/home/sysint/CAVP/cisco/libacvp/app/app_cli.c:194: undefined reference to FIPS_mode'**
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:557: acvp_app] Error 1
make[1]: Leaving directory '/home/sysint/CAVP/cisco/libacvp/app'


![image](https://user-images.githubusercontent.com/58893647/218930459-a8d60857-fbf7-4b8b-bbef-df12fd666b1a.png)

**Comment by abkarcher** [comment]
Hello,

For the error you received, FIPS_mode only appears at that line in the 1_5_0-throttle branch. Please double check you are on the TBD branch, and that you re-ran configure and `make clean` after changing branches.

Otherwise, The TBD branch only compiles with FIPS_mode symbols if the version of OpenSSL being linked is 1.1.1 or lower.  Are you providing the correct path to your OpenSSL 3.0 install when configuring libacvp?

Thanks,
Andrew

**Comment by chenchudhcs** [comment]
Hi 

git branch libacvp_1_5_0-throttle i am using 

![image](https://user-images.githubusercontent.com/58893647/219141288-0b586153-55f8-4711-92a9-17b1dd194079.png)
still i am getting  **### undefined reference to `FIPS_mode' and undefined reference to `EVP_MD_size'** 

![image](https://user-images.githubusercontent.com/58893647/219141390-19c7fad6-fb66-4b48-9211-67a76bf2b4fb.png)


yes i am  providing the right path to your OpenSSL 3.0 install with configuring libacvp 

./configure --with-ssl-dir=/usr/lib/ssl --with-libcurl-dir=/usr/include/x86_64-linux-gnu/curl/

![image](https://user-images.githubusercontent.com/58893647/219141813-d5bd1965-1107-41cd-a2f3-f9c03473a5da.png)

OpenSSL 3.0.2 support for this branch? 

![image](https://user-images.githubusercontent.com/58893647/219142319-bd98ecae-1c5e-41f9-ab77-f1db03fa04cb.png)



can you please help me to fix this problem. 

Thanks,
Chenchu

**Comment by abkarcher** [comment]
You should not be on the 1_5_0-throttle branch for OpenSSL 3.X. You should be on the 1_TBD_throttle branch. 

The error you got in the previous message seemed to come from the 1_5_0-throttle branch. please make sure you run `make clean` and `Configure`  with the correct arguments when you  switch to the libacvp_1_TBD_throttle branch.

If you run `make` and switch branches without running `make clean` you will be left with partial build objects from two different versions of libacvp and that will cause issues.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Closing for now, if you have any further issues with building please ensure the correct branch is pulled and the working environment is clean. 

Thanks,
Andrew
