### ISSUE TITLE
JSON val parse error (acvp_post_data: 3251)

### ISSUE THREAD

**Issue by w-olds** [cisco/libacvp#765]
environment
Demo

testSessionId
N/A

vsId
N/A

Algorithm registration
N/A

Endpoint in which the error is experienced
https://demo.acvts.nist.gov/acvp/v1/login POST

Expected behavior
Access token is received in JSON response

Additional context

wolds@wolds-dev-u22:~/dev/acvt/libacvp$ ./app/acvp_app --post ./app/login_metadata.txt

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    /home/wolds/dev/acvt/libacvp/certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  /home/wolds/dev/acvt/libacvp/certs/CloudSoftwareGroup_Walt_Olds_Demo.cer
    ACV_KEY_FILE:   /home/wolds/dev/acvt/libacvp/certs/CloudSoftwareGroup_Walt_Olds_Demo.key

***ACVP [STATUS][acvp_login:2723]--> Logging in...
Enter PEM pass phrase:
***ACVP [STATUS][acvp_login:2743]--> Login successful
***ACVP [ERR][acvp_post_data:3251]--> JSON val parse error
wolds@wolds-dev-u22:  ~/dev/acvt/libacvp$ cat ./app/login_metadata.txt
/acvp/v1/login
wolds@wolds-dev-u22:  ~/dev/acvt/libacvp$

**Comment by abkarcher** [comment]
Hello,

The post command is intended for use with metadata resources and not for logins. It may work, but that is not its intended use. The object you are trying to post does not match the expected format; please see the examples in the metadata folder. The file must contain valid JSON for a given URL and the payload to be sent (for the sake of login, you need a payload with a TOTP.)

**Generally, if you are just trying to do basic ACVP interactions**, Using any of the algorithm commands, test session commands, or a --get command (e.g. --get /acvp/v1/algorithms) will cause libacvp to login automatically. Libacvp is not designed for manually interacting with individual endpoint on the ACV server and we are unable to support using it this way currently.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hi,

Closing this for now, feel free to reopen if you have further questions after checking the existing docs/examples.

Thanks,
Andrew
