### ISSUE TITLE
Planning for LMS support?

### ISSUE THREAD

**Issue by crypto4a** [cisco/libacvp#766]
Is there a plan to add support for the LMS algorithm at some point in the near future now that it's available on the ACVP demo server?

**Comment by abkarcher** [comment]
Hello!

I have LMS support near complete; I am trying to verify all is working as expected using an implementation currently but if I am unable to I will have support committed to the libacvp_1_TBD_throttle branch the first half of next week.

Thanks,
Andrew

**Comment by crypto4a** [comment]
Hi Andrew,

Thanks for the update, and the hard work to get this functionality included.

**Comment by abkarcher** [comment]
Hello!

Sorry for the wait. LMS library support has been committed to the libacvp_1_TBD_throttle branch. (This will become the libacvp 2.0 release in next few months).

The registration is conditionally compiled by defining ACVPAPP_LMS_SUPPORT. the app_lms.c file contains a comment briefly describing the outputs for each test case.

Unit tests will come soon when I get them completed. 

I will close this for now but please do not hesitate to reopen if you hit any issues or have any questions!

Andrew
