### ISSUE TITLE
testSession_xxxxx.json is not written to when using manual_registration

### ISSUE THREAD

**Issue by waynethorsted** [cisco/libacvp#779]
I have a json request file that contains the tests I want run.  I issue the following commands:
 ./app/acvp_app  --verbose --sample --manual_registration ../MyRequest.json -r Sample_Vectors.json
 ./app/acvp_app --verbose  --get_expected_results testSession_<session #>.json --save_to ../expected.json

The problem is that the testSession file only contains:
[ {
    "url": "\/acvp\/v1\/testSessions\/405318",
    "jwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0c0lkIjoiNDA1MzE4IiwidnNJZCI6IlsxNjUzMzQ0XSIsInN1YiI6IkU9d2F5bmUudGhvcnN0ZWRAY25leGxhYnMuY29tLCBDTj1Mb25nbW9udCwgT1U9TG9uZ21vbnQsIE8
9Q05FWCwgTD1Mb25nbW9udCwgUz1Db2xvcmFkbywgQz1VUyIsIm5iZiI6MTY4NDg2Mjc4MCwiZXhwIjoxNjg0ODY0NTgwLCJpYXQiOjE2ODQ4NjI3ODAsImlzcyI6Ik5JU1QgQUNWUCBERU1PIn0.75bbw8d7prEfRRKHK0bFffyXKIEUJyr1mj6
mHCjNa8U",
    "isSample": true
} ]

This is the request file:
[
    {
        "acvVersion": "1.0"
    },
    {
        "isSample": false,
        "algorithms": [
            {
                "algorithm": "ACVP-AES-XTS",
                "revision": "2.0",
                "dataUnitLenMatchesPayload": true,
                "direction": [
                  "encrypt",
                  "decrypt"
                ],
                "keyLen": [
                  256
                ],
                "payloadLen": [
                  32768,
                  32832
                ],
                "tweakMode": [
                  "number"
                ]
            }
        ]
    }
]

Am I doing this wrong?

Thank you,
Wayne Thorsted

**Comment by abkarcher** [comment]
Hello!

The test session file looks correct. It should only contain the info about the test session and the registration; it is only referenced when libacvp needs to ingest the URL and JWT (auth bearer) for a test session. All the requested vectors are saved in Sample_Vectors.json, and the expected results should be saved in expected.json. What issue are you experiencing? 

(Also, please try to avoid posting JWT/any other credentials).

Thanks,
Andrew

**Comment by waynethorsted** [comment]
Thank you Andrew.  I knew about not posting credentials.  Sorry about that.
So maybe I'm doing something wrong, I'm new to this.  When I request the expected results, specifying the test session I get the following:

admin@0482:~/nist/libacvp$ ./app/acvp_app --verbose --get_expected_results testSession_405318.json --save_to ../expected.json

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE:  certs/CNEX_Wayne_Thorsted_Demo.cer
    ACV_KEY_FILE:   certs/CNEX_Wayne_Thorsted_Demo.key

***ACVP [INFO][acvp_http_user_agent_handler:1667]--> HTTP User-Agent: libacvp/1.5.3;Linux;5.15.0-71-generic;x86_64;Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz;GCC/11.3.0

***ACVP [STATUS][acvp_login:2734]--> Logging in...
***ACVP [INFO][log_network_status:1224]--> POST Login...
        Status: 200
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp: Recieved

***ACVP [STATUS][acvp_login:2754]--> Login successful
***ACVP [INFO][log_network_status:1212]--> GET Vector Set Result...
        Status: 200
        Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/405318/results
        Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": false,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/405318/vectorSets/1653344",
        "status": "unreceived"
      }
    ]
  }
]

***ACVP [STATUS][acvp_get_expected_results:1380]--> Beginning output of expected results...
***ACVP [INFO][log_network_status:1216]--> GET Vector Set Sample...
        Status: 404
        Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/405318/vectorSets/1653344/expected
        Resp:
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-ee1ed0386989d621ee8f2358b2c4ea96-5269ecaccb9c4bdd-00"
}

***ACVP [ERR][log_network_status:1256]--> 404 error received from server. Message:
***ACVP [ERR][log_network_status:1257]--> {
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.4",
  "title": "Not Found",
  "status": 404,
  "traceId": "00-ee1ed0386989d621ee8f2358b2c4ea96-5269ecaccb9c4bdd-00"
}
***ACVP [ERR][acvp_get_expected_results:1433]--> Error retrieving expected results from server
admin@0482:~/nist/libacvp$

The expected.json file only contains:
[ {
    "jwt": 
"<the jwt string>"
    "url": "\/acvp\/v1\/testSessions\/405318"
}

**Comment by abkarcher** [comment]
Thanks for the extra info. I think I see what is happening here; you've stumbled upon a bug!

The manual registration file needs to include the`"isSample": true` key in the second object (right above the algorithms array). Right now its set to false.

We don't acknowledge the --sample CLI flag when communicating with NIST when manual regstration is used, since the manual registration is sent unaltered to the NIST server. However, we do use that flag when creating the test session file. The end result is that NIST does not create it as a sample session but we mark it as a sample. 

I will get a fix for this into the code asap but altering your request file as I mentioned above (from `false` to `true`) should make it work as expected. Fix will be in the next 1.5.X release.

The 2.0 work (not yet released but usable) has a different format for manual registration and thus sample flag should work as expected.

Hopefully this all makes sense, but definitely let me know if you have any more questions. Thanks for the find!

Andrew

**Comment by abkarcher** [comment]
Great! Issue is fixed with #780 and will be in the next release.

Thanks again for reporting!

Andrew
