### ISSUE TITLE
libacvp version

### ISSUE THREAD

**Issue by pablodelara** [cisco/libacvp#796]
Hello! Is it possible to get the libacvp version at compile time (e.g. macro storing the version in acvp.h header file)?
I see a couple of functions to retrieve the version at run time, but I am looking for something to use an #ifdef in the code, since there's been some API breakages in v2.0 (e.g. "acvp_create_test_session").
Thanks!

**Comment by pablodelara** [comment]
Thanks for your reply. Is it possible to check for an API at compile time? From what I can read, it is not possible. Thanks!

**Comment by abkarcher** [comment]
Addressed in #808. Now have access to all version number defines including ACVP_LIBRARY_VERSION_MAJOR, ACVP_LIBRARY_VERSION_MINOR, and  ACVP_LIBRARY_VERSION_PATCH. Will be released in 2.1.0. 

For versions prior to this, there isn't an easy quick way to do it sadly. Perhaps ou can use shell scripts to look for the version string in the source files and set cflags accordingly while configuring.

Closing, but feel free to reopen if any further questions pop up.

Thanks,
Andrew
