### ISSUE TITLE
Removing OpenSSL 1.1.1 Support from future acvp_app release

### ISSUE THREAD

**Issue by abkarcher** [cisco/libacvp#797]
Hello,

I wanted to make an open note about removing application support for OpenSSL 1.1.1 in an upcoming minor release. Due to the lack of an official FIPS module for OpenSSL 1.1.1 its support in the application is, in my opinion, too generic to be largely useful and is redundant. It is also increasingly difficult to support registrations for so many OpenSSL versions with the upcoming ones.

If any users strongly feel it should remain included, please leave a comment here. It will still be possible for users to maintain their own harnesses for 1.1.1 as it has been.

Thanks,
Andrew

**Comment by Moatasem-Elsayed** [comment]
is there any way to revert that and try to run on openssl version 1.1.1 ?
