### ISSUE TITLE
RSA Decryption Primitive Support in libacvp

### ISSUE THREAD

**Issue by mgpirret** [cisco/libacvp#798]
ACVP has revised the RSA decryption primitive. 

Going forward, the existing 1.0 RSA decryption primitive testing ([as specified here](https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-decryptionprimitive-v10)) is only be approved in a limited context. Instead there is now a new format / version for the RSA decryption primitive ([specified here](https://pages.nist.gov/ACVP/draft-celi-acvp-rsa.html#name-rsa-decryptionprimitive-sp8)). 

Currently, only the 1.0 decryption primitive is supported in libacvp. Are there any plans to update the libacvp library to support the newer RSA decryption primitive format?

**Comment by abkarcher** [comment]
Hello,

I am looking at this (and signature primitive revision 2) now. Depending on the details it may be a quick patch release or the next minor release. 

Thanks for bringing this to my attention!
Andrew

**Comment by abkarcher** [comment]
Well, I did hit several roadblocks :) Support for the new revisions is in the 2.1.0 throttle branch. There is a small hiccup I will fix in the coming days after some back and forth with the server folks. I have also tried to maintain testing support for the old revisions using an extra parameter setting.  This will make it into the 2.1.0 release in January; as soon as I fix the hiccup, testing should be possible using the 2.1.0 branch though UTs and stuff have not yet been updated.

Will close this for now, feel free to reopen if you experience any issues or have further questions.

Thanks,
Andrew
