### ISSUE TITLE
Error setting curl option CURLOPT_SSL_VERSION, stopping

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#800]
Hi,
I have valid certificates to the NIST demo server and have also changed the nist_setup.sh file with the path and TOTP to the certificates.  But on trying to login, I see the following error:

Error setting curl option CURLOPT_SSL_VERSION, stopping

Can you please help me understand what I could have done wrong?

Regards,
Sathya.

**Comment by nssathyan** [comment]
Hi Andrew, 
I have used libcurl 4.7.0 and openSSL 1.1.0.  I built openssl with the FIPS support fips 2.0.

**Comment by abkarcher** [comment]
Hello,

Closing this as the issue seems identified. If any further questions pop up, feel free to reopen.

Thanks,
Andrew
