### ISSUE TITLE
Fail to download vector file randomly from demo server

### ISSUE THREAD

**Issue by kevniau** [cisco/libacvp#809]
Hi,

I use this command to register and download vector file
`
./acvp_app --verbose --manual_registration  /capabilities/ACVP-AES-CBC-CS1.json --vector_req vector-ACVP-AES-CBC-CS1.json
`

The command fail randomly to download the vector file from demo server. 
When it fails, I got the follow error. What is Error 3 ??

```
[ACVP]: Received vsid_url=/acvp/v1/testSessions/480916/vectorSets/2135461
[ACVP]: Successfully sent registration and received list of vector set URLs
[ACVP]: Test session URL: /acvp/v1/testSessions/480916
[ACVP]: Beginning to download and process vector sets...
[ACVP]: GET Vector Set...
	Status: 200
	Url: [https://demo.acvts.nist.gov:443/acvp/v1/testSessions/480916/vectorSets/2135461](https://demo.acvts.nist.gov/acvp/v1/testSessions/480916/vectorSets/2135461)
	Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "retry": 30
  }
]

[ACVP]: 200 OK KAT values not ready, server requests we wait 30 seconds and try again...
[ACVP]: GET Vector Set...
	Status: 0
	Url: [https://demo.acvts.nist.gov:443/acvp/v1/testSessions/480916/vectorSets/2135461](https://demo.acvts.nist.gov/acvp/v1/testSessions/480916/vectorSets/2135461)
	Resp:


[ACVP][31m[ERROR][0m: Received no response from server.
[ACVP][31m[ERROR][0m: Unable to process vector set! Error: 3
[ACVP][31m[ERROR][0m: Failed to process vectors
```

**Comment by abkarcher** [comment]
Hello,

Could you please share what platform you are running on, and what curl version you are using? 
It is odd that the URL is formatted that way in the logs.

For this error to occur, either something would be wrong with the URL, or your network infrastructure is blocking or dropping the connection. "3" just refers to ACVP_TRANSPORT_FAIL, the error that occurs when any network action fails.

Thanks!
Andrew

**Comment by kevniau** [comment]
Hi Andrew,

Thank you for the reply. I setup a pipeline script  in Jenkin to retrieve the vectors files for 71 capabilities files . 
We found only 2/3 success to retrieve vector files and 1/3 fail with Error 3. Those fail algorithms  just randomly. 

I use --verbose flag in command line, you can see the response **_Status: 0_** and ### **_Resp_** is empty.
Looks like server does not return anything!!!

```
[ACVP]: GET Vector Set...
	Status: 0
	Url: [https://demo.acvts.nist.gov:443/acvp/v1/testSessions/480916/vectorSets/2135461](https://demo.acvts.nist.gov/acvp/v1/testSessions/480916/vectorSets/2135461)
	Resp:
```

NAME="SLES"
VERSION="15-SP2"
VERSION_ID="15.2"
PRETTY_NAME="SUSE Linux Enterprise Server 15 SP2"

curl --version
curl 7.66.0 

./acvp_app --version
ACVP library version(protocol version): libacvp_oss-2.0.0(1.0)

        Runtime mode: yes
           FIPS mode: no
Compiled SSL version: OpenSSL 1.1.1l-fips  24 Aug 2021 SUSE release SUSE_OPENSSL_RELEASE
  Linked SSL version: OpenSSL 1.1.1d-fips  10 Sep 2019

**Comment by abkarcher** [comment]
Hi,

Due to the randomness in the failures, I think it is likely due to a network configuration or momentary blips on the ACVP server. We don't have multi-threading or anything in ACVP app, so there is very little randomness in the process. 

We  have seen cases of business networks flagging ACVP traffic as unusual, or blocking it completely from the start. Perhaps you could reach out to the ACVP server with details about the failed request and see if they got it on their end.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hello!

I'll go ahead and close this for inactivity, but please feel free to re-open if you think there is something going on here that libacvp is causing. Thanks!

Andrew
