### ISSUE TITLE
HTTP response: 401

### ISSUE THREAD

**Issue by iabent** [cisco/libacvp#82]
Hey guys, I'm hoping you have an idea of what I could be missing.

I generated my RSA key pair along with the CSR and sent it off to NIST. Got my TOTP seed and certificate back from them so thought I would be good to go. I am using a Centos 7 machine as my client, openssl 1.0.2k-fips, TLSv1.2 and curl is installed and working.

My nist_setup.sh file looks like this:
#!/bin/bash
export ACV_URI_PREFIX=acvp/
export ACV_CA_FILE=certs/demo_cert_ACVP.crt     <- Grabbed using "openssl s_client"
export ACV_KEY_FILE=certs/acvp.key                      <- RSA private key used for the CSR
export ACV_CERT_FILE=certs/demo.cer                   <- NIST certificate returned to me
export ACV_TOTP_SEED=(long string of text)          <- Contents of my seed.txt from NIST
export ACV_PORT=443
export ACV_SERVER=demo.acvts.nist.gov

But when I run "./acvp_app -info" I get the following:
./acvp_app -info
Using the following parameters:
    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: acvp/
    ACV_CA_FILE:    certs/demo_cert_ACVP.crt
    ACV_CERT_FILE:  certs/demo.cer
    ACV_KEY_FILE:   certs/acvp.key
POST [
    {
        "acvVersion": "0.4"
    },
    {
        "password": (digits)
    }
]
***ACVP [INFO][acvp_curl_log_peer_cert:84]--> TLS peer presented the following 0 certificates...
***ACVP [ERR][acvp_curl_http_post:280]--> HTTP response: 401
***ACVP [ERR][acvp_send_login:541]--> Unable to register with ACVP server. curl rv=401
***ACVP [STATUS][acvp_register:5142]--> Login Response Failed {
  "acv_version" : "0.4",
  "error" : "The supplied one time password could not be verified"
}
***ACVP [STATUS][acvp_register:5145]--> Login Send Failed
Failed to register with ACVP server (rv=3)

And I'm a bit confused. Any idea what could possibly be causing the password to not be verified? Tried a few changes, but otherwise I *should* have everything I need.

Thanks so much! Any help is very appreciated :)

**Comment by bfussell** [comment]
First thing that comes to mind is that there could be too much drift in your time.
You could dump the time you read and compare with a website that keeps the
current unix time to see how close you are.

Barry

**Comment by iabent** [comment]
Hey! Thanks for the reply.

My machine's time seems to be on point. Opened up this website: https://time.is/Unix_time_now and, with it open on my laptop monitor, entered "date +%s" on my Centos machine. The 10 digits matched exactly. Time delays have caused me many headaches before so it was a great suggestion!

**Comment by iabent** [comment]
Hello again,

Tried grabbing new CA files from the NIST server, re-downloading this tool (as it was updated since) and made sure the machine's time was still on point but I am still running into this issue. Any other ideas? Still "The supplied one time password could not be verified".

Thanks so much!

**Comment by bfussell** [comment]
are you using a temporary TOTP seed or have you obtained a permanent seed from NIST ?

**Comment by iabent** [comment]
Permanent from what I can tell. I was sent a seed .txt file from NIST (along with the cert file in response to my CSR) and tried to use it immediately in the nist_setup.sh script but got that error. 

Is there a way to use the tool without a seed? I can contact the guys at NIST to get a new seed to see if that is indeed the problem, but I was under the impression that the seed.txt file they sent me was a permanent seed.

Thank you though!

**Comment by bfussell** [comment]
Tough to say what the issue is without debugging myself. NIST is supposed to have some debugging built in to help isolate TOTP failures. When we were working thru some issues a while back they said they could provide some intermediate values during the password calculation that may help identify where your password is failing. You'd have to dump those or gdb and check them in the client.

You can ask NIST about not using a seed, they allowed that back in April not sure if they will now.

**Comment by iabent** [comment]
Awesome! Thanks for the information :) Wanted to see if there was anything glaringly obvious that I was missing but it looks like I have some digging to do. 

Thank you for your time. I'll be in contact if I have any more questions.

**Comment by iabent** [comment]
Hey again, a quick question:

When I added the seed to the "ACV_TOTP_SEED=" section, do I need to add anything special to it? Or is it simply the contents of my seed.txt file? Example: If the contents in seed.txt was "helloworld" should my nist_setup.sh look like this:

ACV_TOTP_SEED=helloworld
^what I'm using now
or something like

ACV_TOTP_SEED="helloworld"

After talking with NIST my seed is permanent and they sent me a new one just in case (I say "new" loosely as the contents of the txt file is identical to the one I had before). \

Thanks so much!

**Comment by elliemdaw** [comment]
I usually have mine within quotes and it works just fine!

**Comment by bfussell** [comment]
Hmmm I don't use quotes with mine, I guess it depends on your environment.
When I do a printenv it doesn't show any quotes, for example:

> printenv | grep TOTP

ACV_TOTP_SEED=8oKN5afcvwa1A5hdRJ/VIKBqZO4Ky5qnTMFptZKsq6n=

(note that is not my "real" seed)

**Comment by iabent** [comment]
Hey, just wanted to update this issue to let you know it works now :) Harold Booth (of NIST) mentioned that it might have been an issue with my seed containing a null byte. So, after some great vacation, I grabbed the latest libacvp code and ran it without a problem!

Thanks for you time!

**Comment by elliemdaw** [comment]
Awesome, thanks for letting us know! Glad it works!

**Comment by bfussell** [comment]
That's correct, there was a bug in the TOTP password generation code that didnot handle null bytes properly. That was fixed with this commit:

https://github.com/cisco/libacvp/commit/cf02b77370e822310e588fef8e7c5e9e68326817

**Comment by iabent** [comment]
May not be the best place to ask this but:

Is there a place where the libacvp client stores the vs_id assigned by the NIST server? I get a long list of "Received vs_id=11902/11903/etc" in the output but I was wondering if there was a way to find the mapping easily (for example: vs_id:11902=AES-GCM, vs_id:11903=AES-ECB, etc) or do I need to go through the output itself to find them? (As I did for those 2)

Thanks so much!

**Comment by elliemdaw** [comment]
The library doesn't currently have API to give that information in a consolidated way. The best way for now is to just sort through the output

**Comment by Rasstrelnikov** [comment]
Thanks for the response, it looks like I don't have any option but to contact NIST.

**Comment by iabent** [comment]
Hello again! Sorry for all the questions here, is there a better way to ask one-shot questions about libacvp?

I just wanted to know if there is a location where the vector sets are downloaded to and if they are stored in any way? I would like to have the JSON files to try and use with our module and if they are already on my client machine that would save me doing the manual POST and GETs.

Thanks you!

**Comment by elliemdaw** [comment]
No worries, here is fine for now! The way the library and example application are set up currently, the vectors are not stored on the machine. This is a feature we have on our backlog.

As a workaround, you can set the log level to verbose (our example app does this with the -verbose runtime option) and the vector set JSONs will print to the console and then you could save them from there.

Thank you!

**Comment by iabent** [comment]
Hello again :) Been a while but I hope you are doing well. I have no issue, just a question (Not sure if there is a better place to post questions yet):

Do you have a list of all the Algorithms, modes and lengths that are run by this demo? My team wanted to check the list against our product to see if there are any gaps that would need to be addressed. If not I can start to comb through the code (lhl.h looks to be pretty comprehensive with the defines so I can start there and cross reference the various .c files)

Thanks again!
