### ISSUE TITLE
DSA tgId and tcId missing from some test cases

### ISSUE THREAD

**Issue by RandallSteck** [cisco/libacvp#841]
The tgId and tcId are fields present in the ACVP_DSA_TC structure, but they are not populated on all test cases.  The acvp_dsa.c parsers are incomplete in adding this data to all TCs.

The PQG tests take a long time to complete, and the tcId increment is useful to demonstrate progress in testing.

I have a patch ready for submission that populates the two fields for all test cases.  From which branch would you like me to generate to PR?

**Comment by abkarcher** [comment]
2.2.0 currently would be great for any changes that are not related to an immediate breakage of testing with the NIST server. Thanks!

**Comment by RandallSteck** [comment]
PR submitted
