### ISSUE TITLE
Allow some fields to be missing on offline mode

### ISSUE THREAD

**Issue by pablodelara** [cisco/libacvp#855]
It looks like a few fields in the request json file need to be present, when the library is compiled in offline mode.
- url
- jwt
- vectorSetUrls

When these fields are missing, they all cause the same warning:
"Missing X, results will not be POSTed to server"

And then the execution stops. Since these are not needed in offline mode (no server is involved), I think it makes sense to continue with the parsing of the file and with the rest of the execution.

Thanks!

**Comment by abkarcher** [comment]
Hi,

We have the API available for the future 2.2.0 release, and will have a separate app CLI option to run vector set files not generated by libacvp. Closing, but feel free to re-open if you have any further questions. Thanks!

Andrew

**Comment by pablodelara** [comment]
Hi @abkarcher. Could you specify which API you are referring to? I am using "acvp_run_vectors_from_file" and I am still getting those warnings. Is there a new one? Thanks!

**Comment by pablodelara** [comment]
Never mind, I just saw it :) (acvp_run_vectors_from_file_offline). When are you planning on releasing 2.2.0? Thanks!

**Comment by abkarcher** [comment]
Hello,

It is likely at least a month or two, maybe more, unfortunately; there is some more code restructuring to finish up and I also need to finish up ML-KEM/ML-DSA/etc support.

 In the mean time, it is possible to simply add those fields to run tests, and remove afterwards, see here:
 
 https://github.com/cisco/libacvp/issues/592#issuecomment-822854657
 
 Thanks,
 Andrew
