### ISSUE TITLE
CURLOPT_SSL_VERSION error

### ISSUE THREAD

**Issue by nssathyan** [cisco/libacvp#859]
Hi,
I have been able to run the NIST demo server earlier, but off late have been seeing this error.  Please let me know what could be wrong

***ACVP [STATUS][acvp_login:2723]--> Logging in...
***ACVP [ERR][acvp_curl_http_post:317]--> Error setting curl option CURLOPT_SSL_VERSION, stopping
***ACVP [INFO][log_network_status:1216]--> POST Login...
        Status: 0
        Url: https://demo.acvts.nist.gov:443/acvp/v1/login
        Resp: Recieved

**Comment by abkarcher** [comment]
Hi,

Could you provide some basic info about the platform you are running on, including the version of libcurl and what ssl library it is using?

Thanks,
Andrew

**Comment by nssathyan** [comment]
Hi @abkarcher - We are running this build on 18.04.1-Ubuntu with libcurl version 7.73.0 and OpenSSL 1.0.2u.  I rebuilt the FIPS, OpenSSL and curl and now I am able to connect to the NIST demo server.  Thank you for the help.

Sathya.
