### ISSUE TITLE
Errors in FIPS186-5 mode

### ISSUE THREAD

**Issue by spramanik-infoblox** [cisco/libacvp#860]
I want to run tests in FIPS186-5 mode. The release notes for v2.1.0 [here](https://github.com/cisco/libacvp/releases) say that support for 186-5 is not enabled by default. I specified `CFLAGS="-DACVP_FIPS186_5"` in configure and built it but when I run the app I get this error : 

```
bash-4.0# ./acvp_app --rsa

...

[ACVP][ERROR]: Cap entry not found.
Failed to register capability with libacvp (rv=11: No matching capability found)
```
Is this the right way to build for 186-5 support ? I built v2.1.1 with openssl 3.3.1

**Comment by abkarcher** [comment]
Hi,

Currently released versions of acvp_app do not have full 186-5 support as there is currently no validated version of OpenSSL FIPS provider that is 186-5 compliant. The code is there as an example to help developers and to allow us to easily enable it for upcoming versions. 

If there is a need to run 186-5 tests on modules not validated for 186-5, it will require making changes to the code to adjust the capabilities registration, and ensure all of the relevant handler functions are compiled and can accommodate it. It is not something we are able to support ourselves at this time, unfortunately. 

Thanks,
Andrew

**Comment by spramanik-infoblox** [comment]
@abkarcher,  thank you for the information.
