### ISSUE TITLE
FIPS Provider Help 

### ISSUE THREAD

**Issue by chenchudhcs** [cisco/libacvp#868]
Hello 

i am getting FIPS provider error can some one please help me how to fix this below error. 

CAVP/libacvp$ ./app/acvp_app --rsa

**Crypto module returned failure code when running quick digest.
Error occured when testing FIPS at startup (rv = 10). Please verify the FIPS provider is
properly installed and configured. Exiting...**

/CAVP/libacvp$ ./app/acvp_app --version 

 **ACVP library version: libacvp_oss-2.1.1
ACVP protocol version: 1.0

 Compiled SSL version: OpenSSL 3.0.0 7 sep 2021
   Linked SSL version: OpenSSL 3.0.2 15 Mar 2022

       FIPS requested: yes
FIPS Provider Version: (null)**

--------------- Openssl version ------------- 

/etc/ssl$ openssl version -v
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
 
 conf file -- 
[openssl.zip](https://github.com/user-attachments/files/17250199/openssl.zip)

**Comment by abkarcher** [comment]
Hi,

Apologies for the delay responding here. Could you please see the response in #863?  the null fips provider string means that the app was unable to detect a configured and loaded fips provider at all. Please ensure openssl is configured to load that provider.

Thanks,
Andrew

**Comment by abkarcher** [comment]
Hello,

I am closing this issue, but feel free to reopen if you have any further questions.

Thanks,
Andrew
