### ISSUE TITLE
RSA 186-5 support

### ISSUE THREAD

**Issue by RandallSteck** [cisco/libacvp#873]
I need to add FIPS 186-5 support for RSA.  I can add it as a simple global config selection for all of RSA (186-4 or 186-5 as an enum), but that limits usage to one or the other.  I'd prefer to add it in a way where both can be tested in one session.  Therefor, I propose to extend RSA in a similar manner to DRBG with the addition of a "cap group" structure.  There would be one cap group associated with each standard, and the RSA capabilities functions would be extended to require this parameter.  The RSA register functions would output multiple json stanzas, one for each cap group.

Is this a solution you would be comfortable with?  If so, can I make the PR against 2.2.0?

**Comment by abkarcher** [comment]
Hey Randy,

I am not sure I follow - we have support for 186-5 for RSA (at least, the variations we can test). They have been in since 2.1.0. Is there something missing? 186-5 is tested by default and 186-4 is testable with a parameter set for revision. the fp_dev.c registration (used to test OpenSSL FPs past 3.1.2 which hadn't been alg tested yet) tests RSA fips 186-5.

Thanks,
Andrew

**Comment by RandallSteck** [comment]
Andrew --

I'm sorry - I see the 186-5 support.  Just a bad read of the code.

It's implemented to apply per-type, and the uniqueness of the RSA_SIG_CAP list entries is also by type, so one can only test either 186-4 or 186-5 (for each type) in a single live session (or in a single saved cap file).  I need to test both revisions in the same session, and/or have both appear in a saved capabilities file.  For that I need the capabilities lists to hold entries for both revisions at the same time.

Based on how it's currently implemented, I propose to change the uniqueness of the ACVP_RSA_SIG_CAP entries for SigGen and SigVer to a tuple of (type, revision).  All the functions beginning "acvp_cap_rsa_sig*" would need to be modified to add the revision as an input, and the contents of functions in acvp_capabilities.c and acvp_build_register.c would need to be changed to use the new uniqueness in many places such as lookup/duplicate, writing JSON caps, etc.

Is this change something you would support and merge, or something I should maintain in my own fork?  Do you have a suggestion for a better way to implement this?

Thanks,
Randy

**Comment by RandallSteck** [comment]
Andrew,

All I can say is that I have a client that has specifically requested to test under both revisions.  I've already met the requirement by modifying my local copy based on 2.0.0.  My approach is similar enough to yours with macros to switch between them.  I can output a capabilities file for both, with a re-compile between, and manually stitch them in a text editor to get a full capabilities file.  

This recompile-and-stitch is the work I was trying to save with the change, but I think it's a bridge too far.  I agree the changes to the API are drastic.  I can adapt the IUT side of my code to match your API when I re-base on 2.2.0.

I'll drop the request.  Thanks for the discussion.

Randy
