### ISSUE TITLE
Support for SLH-DSA

### ISSUE THREAD

**Issue by RandallSteck** [cisco/libacvp#874]
Is anyone working on adding support for SLH-DSA (FIPS 205)?  I have a client that needs this tested, and wanted to see if there's any ongoing work before I tackle it.

Thanks!

**Comment by abkarcher** [comment]
Hi Randy,

I have begun work on it and should have it done within the next week and a half (hopefully less) in the 2.2.0 branch.

Thanks,
Andrew

**Comment by RandallSteck** [comment]
Awesome, thanks

**Comment by RandallSteck** [comment]
Closing, I'll monitor 2.2.0 for updates.

**Comment by abkarcher** [comment]
Just an update - should have this in on Tuesday. Apologies for the wait.
