### ISSUE TITLE
PQC support in libacvp

### ISSUE THREAD

**Issue by portland5089** [cisco/libacvp#875]
ACVP server already supports test vector for PQC algorithm like ML-DSA
https://pages.nist.gov/ACVP/draft-celi-acvp-ml-dsa.html
Do we have plan to support it in client side?

Thanks

Dong

**Comment by abkarcher** [comment]
Hello,

- LMS is currently supported in recent releases
- ML-KEM support is complete and functional in the 2.2.0 branch, not yet released
  - Supports liboqs testing (for time being)
- ML-DSA will get a small fix in the 2.2.0 branch tomorrow and should be complete then, not yet released
  - Waiting on oqs ML-DSA implementation updates to support testing
- SLH-DSA work should be completed in the next week or so in the 2.2.0 branch

2.2.0 will likely be released by end of year if not earlier, but the branch is generally kept in a working state. There are a few platforms that might not function properly at the moment (e.g. Windows).

Thanks,
Andrew
