### ISSUE TITLE
--manual_registration error

### ISSUE THREAD

**Issue by jenna-zheng-xq** [cisco/libacvp#878]
Hi, 

Could you please help me on this --manual_registration error? Thank you so much
I am trying to download some test vector for our project debug/verfiy purpose. and when I ran this command, I got errors

./app/acvp_app --verbose --sample --manual_registration cmac_aes.json -r cmac_req_vector.json

Using the following parameters:

    ACV_SERVER:     demo.acvts.nist.gov
    ACV_PORT:       443
    ACV_URI_PREFIX: /acvp/v1/
    ACV_CA_FILE:    certs/mozzila_trust_anchors.pem
    ACV_CERT_FILE: My cer
    ACV_KEY_FILE:  My key

[ACVP]: HTTP User-Agent: libacvp/2.1.1;Linux;4.18.0-372.9.1.el8.x86_64;x86_64;AMD Ryzen Threadripper PRO 3945WX 12-Cores;GCC/8.5.0

[ACVP]: Logging in...
[ACVP]: POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

[ACVP]: Login successful
[ACVP]: Reading capabilities registration file...
[ACVP]: Sending registration of capabilities...
[ACVP]: [{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"acvVersion":"1.0"},{"isSample":true,"algorithms":[{"algorithm":"CMAC-AES","revision":"1.0","direction":["gen"],"msgLen":[128],"macLen":[128],"keyLen":[128,256]}]}]}]
[ACVP]: POST Registration...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions
	Resp: Recieved

[ACVP][ERROR]: 400 error received from server. Message:
[ACVP][ERROR]: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Unable to map - - index 0 to an internal algorithm id.",
      "Unable to map - - index 1 to an internal algorithm id."
    ]
  }
]
[ACVP][ERROR]: Failed to send registration
[ACVP][ERROR]: Failed to register with ACVP server

here is my registeration json file looks like:
[
  {
    "acvVersion": "1.0"
  },
  {
      "isSample": true,
      "algorithms": [
        {
          "algorithm": "CMAC-AES",
          "revision":  "1.0",
          "direction": [
            "gen"
          ],
          "msgLen": [
            128
          ],
          "macLen": [
            128
          ],
          "keyLen": [
            128,
            256
          ]
        }
      ]
  }
]

**Comment by bfussell** [comment]
Your registration file should not have the version preamble and isSample. Those items will be added by the client app. You also should have the prereqVals even though the server doesn't check them. Your file should look like this:

[{"algorithm":"CMAC-AES","revision":"1.0",
                 "prereqVals":[{"algorithm":"AES","valValue":"same"}],
                 "capabilities":[{"direction":["gen"],
                 "msgLen":[128],
                 "macLen":[128],
                 "keyLen":[128,256]}]}]

**Comment by jenna-zheng-xq** [comment]
Hi, 
Thank you so much, after I modified format as your reply, it works now. 
Another question, do we have option to download the response at same time? Then I can send both req and resp to client to debug more efficiently.

**Comment by abkarcher** [comment]
By response, do you mean expected responses in the case of sample sessions? That is not an option currently.
To get expected options you just have to do `--get_expected_results <testSession_file> --save_to <filename>`

Thanks,
Andrew

**Comment by jenna-zheng-xq** [comment]
Hi, Andew

Thanks for your help. I will close this issue.

Jenna
