### ISSUE TITLE
[ACVP][ERROR]: Refreshed + retried, HTTP transport fails. curl rc=400

### ISSUE THREAD

**Issue by jenna-zheng-xq** [cisco/libacvp#881]
Hi, 

I have successfully ran some offline tests for few days.
But today, I keep getting this error. [ACVP][ERROR]: Refreshed + retried, HTTP transport fails. curl rc=400
Could you please guide me how to solve this?

Thank you
Jenna

[ACVP]: Sending responses for vector set 2675493
[ACVP][WARNING]: JWT authorization has timed out, curl rc=401. Refreshing session...
[ACVP]: Logging in...
[ACVP]: POST Login...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/login
	Resp: Recieved

[ACVP]: Login successful
[ACVP]: Refresh successful, attempting to continue...

HTTP PUT:

[{"acvVersion":"1.0"},{"vsId":2675493,"algorithm":"KDF","testGroups":[{"tgId":1,"tests":[{"tcId":1,"keyOut":"951B460544FEC2B7569DF8DDDAC94F7D","fixedData":"000000000000000000000000000000"},{"tcId":2,"keyOut":"3705B645EDFF317C4CBD502A09D918E3","fixedData":"000000000000000000000000000000"}]},{"tgId":2,"tests":[{"tcId":3,"keyOut":"6030F8C6DA2E5CFA1D8282C81FCADD764EA1FE99C19F5FC5A220F41CA596DCE1","fixedData":"000000000000000000000000000000"},{"tcId":4,"keyOut":"7421E5833DA36AEE56AB53A1673264E48B581892DA2637F19054D7D89EF7B144","fixedData":"000000000000000000000000000000"}]},{"tgId":3,"tests":[{"tcId":5,"keyOut":"038A45A63213EACFD43B899BCABB099A","fixedData":"000000000000000000000000000000"},{"tcId":6,"keyOut":"BA5F2A0C02EEE57DD209BB8E57046AC7","fixedData":"000000000000000000000000000000"}]},{"tgId":4,"tests":[{"tcId":7,"keyOut":"13C67989065685833945A337B253D91A3741797670C8358441A5A320A1C02583","fixedData":"000000000000000000000000000000"},{"tcId":8,"keyOut":"162265618503F90A0F4CEE23E6E7F9A2B6574939DF863690CD1C06AFED1E6771","fixedData":"000000000000000000000000000000"}]}]}]
[ACVP][ERROR]: Refreshed + retried, HTTP transport fails. curl rc=400

[ACVP]: POST Response Submission...
	Status: 400
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/560521/vectorSets/2675493/results
	Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027failed\u0027 or \u0060error\u0060 status.",
      "Unable to submit results when vector set in \u0027passed\u0027 status."
    ]
  }
]

[ACVP][ERROR]: 400 error received from server. Message:
[ACVP][ERROR]: [
  {
    "acvVersion": "1.0"
  },
  {
    "error": "Validation error(s) on JSON payload.",
    "context": [
      "Vector set not in \u0027failed\u0027 or \u0060error\u0060 status.",
      "Unable to submit results when vector set in \u0027passed\u0027 status."
    ]
  }
]
[ACVP][ERROR]: Failed to submit test results for vector set - skipping...
[ACVP]: Tests complete, checking results...
[ACVP]: GET Vector Set Result...
	Status: 200
	Url: https://demo.acvts.nist.gov:443/acvp/v1/testSessions/560521/results
	Resp:
[
  {
    "acvVersion": "1.0"
  },
  {
    "passed": true,
    "results": [
      {
        "vectorSetUrl": "/acvp/v1/testSessions/560521/vectorSets/2675493",
        "status": "passed"
      }
    ]
  }
]

[ACVP]: Passed all vectors in test session!

**Comment by abkarcher** [comment]
Hi,

The server error is indicating that you cannot re-submit results for test sessions that have already passed. The log messaging is a bit misleading there and I will make a note to clean that up.

Thanks,
Andrew

**Comment by jenna-zheng-xq** [comment]
Hi, Andrew
Thank you for the help
